/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapco.work_notice_contacts;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class notice_contact_type extends SuperVO {
	private java.lang.String pk_contact_type;
	private java.lang.String notice_style;
	private java.lang.String ye_type;
	private java.lang.String report_type;
	private java.lang.String data_type;
	private java.lang.String report_psn;
	private java.lang.String report_org;
	private java.lang.String report_visualorg;
	private nc.vo.pub.lang.UFDate report_date;
	private java.lang.String remark;
	private java.lang.String vdef1;
	private java.lang.Integer enablestate;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String vdef2;
	private java.lang.String vdef3;
	private java.lang.String vdef4;
	private java.lang.String vdef5;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.vo.scapco.work_notice_contacts.notice_contact_info[] id_contact_info;

	public static final String PK_CONTACT_TYPE = "pk_contact_type";
	public static final String NOTICE_STYLE = "notice_style";
	public static final String YE_TYPE = "ye_type";
	public static final String REPORT_TYPE = "report_type";
	public static final String DATA_TYPE = "data_type";
	public static final String REPORT_PSN = "report_psn";
	public static final String REPORT_ORG = "report_org";
	public static final String REPORT_VISUALORG = "report_visualorg";
	public static final String REPORT_DATE = "report_date";
	public static final String REMARK = "remark";
	public static final String VDEF1 = "vdef1";
	public static final String ENABLESTATE = "enablestate";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF5 = "vdef5";
			
	/**
	 * 属性pk_contact_type的Getter方法.属性名：联系人类别主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_contact_type () {
		return pk_contact_type;
	}   
	/**
	 * 属性pk_contact_type的Setter方法.属性名：联系人类别主键
	 * 创建日期:
	 * @param newPk_contact_type java.lang.String
	 */
	public void setPk_contact_type (java.lang.String newPk_contact_type ) {
	 	this.pk_contact_type = newPk_contact_type;
	} 	  
	/**
	 * 属性notice_style的Getter方法.属性名：通知类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_style () {
		return notice_style;
	}   
	/**
	 * 属性notice_style的Setter方法.属性名：通知类型
	 * 创建日期:
	 * @param newNotice_style java.lang.String
	 */
	public void setNotice_style (java.lang.String newNotice_style ) {
	 	this.notice_style = newNotice_style;
	} 	  
	/**
	 * 属性ye_type的Getter方法.属性名：业务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getYe_type () {
		return ye_type;
	}   
	/**
	 * 属性ye_type的Setter方法.属性名：业务类型
	 * 创建日期:
	 * @param newYe_type java.lang.String
	 */
	public void setYe_type (java.lang.String newYe_type ) {
	 	this.ye_type = newYe_type;
	} 	  
	/**
	 * 属性report_type的Getter方法.属性名：报告类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_type () {
		return report_type;
	}   
	/**
	 * 属性report_type的Setter方法.属性名：报告类型
	 * 创建日期:
	 * @param newReport_type java.lang.String
	 */
	public void setReport_type (java.lang.String newReport_type ) {
	 	this.report_type = newReport_type;
	} 	  
	/**
	 * 属性data_type的Getter方法.属性名：资料类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getData_type () {
		return data_type;
	}   
	/**
	 * 属性data_type的Setter方法.属性名：资料类型
	 * 创建日期:
	 * @param newData_type java.lang.String
	 */
	public void setData_type (java.lang.String newData_type ) {
	 	this.data_type = newData_type;
	} 	  
	/**
	 * 属性report_psn的Getter方法.属性名：填表人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_psn () {
		return report_psn;
	}   
	/**
	 * 属性report_psn的Setter方法.属性名：填表人
	 * 创建日期:
	 * @param newReport_psn java.lang.String
	 */
	public void setReport_psn (java.lang.String newReport_psn ) {
	 	this.report_psn = newReport_psn;
	} 	  
	/**
	 * 属性report_org的Getter方法.属性名：填表单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_org () {
		return report_org;
	}   
	/**
	 * 属性report_org的Setter方法.属性名：填表单位
	 * 创建日期:
	 * @param newReport_org java.lang.String
	 */
	public void setReport_org (java.lang.String newReport_org ) {
	 	this.report_org = newReport_org;
	} 	  
	/**
	 * 属性report_visualorg的Getter方法.属性名：填表组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_visualorg () {
		return report_visualorg;
	}   
	/**
	 * 属性report_visualorg的Setter方法.属性名：填表组织
	 * 创建日期:
	 * @param newReport_visualorg java.lang.String
	 */
	public void setReport_visualorg (java.lang.String newReport_visualorg ) {
	 	this.report_visualorg = newReport_visualorg;
	} 	  
	/**
	 * 属性report_date的Getter方法.属性名：填报时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getReport_date () {
		return report_date;
	}   
	/**
	 * 属性report_date的Setter方法.属性名：填报时间
	 * 创建日期:
	 * @param newReport_date nc.vo.pub.lang.UFDate
	 */
	public void setReport_date (nc.vo.pub.lang.UFDate newReport_date ) {
	 	this.report_date = newReport_date;
	} 	  
	/**
	 * 属性remark的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newRemark java.lang.String
	 */
	public void setRemark (java.lang.String newRemark ) {
	 	this.remark = newRemark;
	} 	  
	/**
	 * 属性vdef1的Getter方法.属性名：备用字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.属性名：备用字段1
	 * 创建日期:
	 * @param newVdef1 java.lang.String
	 */
	public void setVdef1 (java.lang.String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性enablestate的Getter方法.属性名：是否启用
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEnablestate () {
		return enablestate;
	}   
	/**
	 * 属性enablestate的Setter方法.属性名：是否启用
	 * 创建日期:
	 * @param newEnablestate java.lang.Integer
	 */
	public void setEnablestate (java.lang.Integer newEnablestate ) {
	 	this.enablestate = newEnablestate;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性vdef2的Getter方法.属性名：备用字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.属性名：备用字段2
	 * 创建日期:
	 * @param newVdef2 java.lang.String
	 */
	public void setVdef2 (java.lang.String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef3的Getter方法.属性名：备用字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.属性名：备用字段3
	 * 创建日期:
	 * @param newVdef3 java.lang.String
	 */
	public void setVdef3 (java.lang.String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef4的Getter方法.属性名：备用字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.属性名：备用字段4
	 * 创建日期:
	 * @param newVdef4 java.lang.String
	 */
	public void setVdef4 (java.lang.String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef5的Getter方法.属性名：备用字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.属性名：备用字段5
	 * 创建日期:
	 * @param newVdef5 java.lang.String
	 */
	public void setVdef5 (java.lang.String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性id_contact_info的Getter方法.属性名：id_contact_info
	 * 创建日期:
	 * @return nc.vo.scapco.work_notice_contacts.notice_contact_info[]
	 */
	public nc.vo.scapco.work_notice_contacts.notice_contact_info[] getId_contact_info () {
		return id_contact_info;
	}   
	/**
	 * 属性id_contact_info的Setter方法.属性名：id_contact_info
	 * 创建日期:
	 * @param newId_contact_info nc.vo.scapco.work_notice_contacts.notice_contact_info[]
	 */
	public void setId_contact_info (nc.vo.scapco.work_notice_contacts.notice_contact_info[] newId_contact_info ) {
	 	this.id_contact_info = newId_contact_info;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_contact_type";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_notice_contact_type";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_notice_contact_type";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public notice_contact_type() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapco.work_notice_contacts.notice_contact_type" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


