/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapco.work_notice_contacts;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class notice_contact_info extends SuperVO {
	private java.lang.String pk_contact_type;
	private java.lang.String pk_notice_contact_info;
	private java.lang.String pk_org;
	private java.lang.String pk_visualorg;
	private java.lang.String contacts_name;
	private java.lang.String pk_user;
	private java.lang.String sex;
	private java.lang.String post;
	private java.lang.String phone_no;
	private java.lang.String email;
	private java.lang.String qq_num;
	private java.lang.String contacts_type;
	private java.lang.String remark;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_CONTACT_TYPE = "pk_contact_type";
	public static final String PK_NOTICE_CONTACT_INFO = "pk_notice_contact_info";
	public static final String PK_ORG = "pk_org";
	public static final String PK_VISUALORG = "pk_visualorg";
	public static final String CONTACTS_NAME = "contacts_name";
	public static final String PK_USER = "pk_user";
	public static final String SEX = "sex";
	public static final String POST = "post";
	public static final String PHONE_NO = "phone_no";
	public static final String EMAIL = "email";
	public static final String QQ_NUM = "qq_num";
	public static final String CONTACTS_TYPE = "contacts_type";
	public static final String REMARK = "remark";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
			
	/**
	 * 属性pk_contact_type的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_contact_type () {
		return pk_contact_type;
	}   
	/**
	 * 属性pk_contact_type的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_contact_type java.lang.String
	 */
	public void setPk_contact_type (java.lang.String newPk_contact_type ) {
	 	this.pk_contact_type = newPk_contact_type;
	} 	  
	/**
	 * 属性pk_notice_contact_info的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_notice_contact_info () {
		return pk_notice_contact_info;
	}   
	/**
	 * 属性pk_notice_contact_info的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_notice_contact_info java.lang.String
	 */
	public void setPk_notice_contact_info (java.lang.String newPk_notice_contact_info ) {
	 	this.pk_notice_contact_info = newPk_notice_contact_info;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属企业
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属企业
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_visualorg的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_visualorg () {
		return pk_visualorg;
	}   
	/**
	 * 属性pk_visualorg的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_visualorg java.lang.String
	 */
	public void setPk_visualorg (java.lang.String newPk_visualorg ) {
	 	this.pk_visualorg = newPk_visualorg;
	} 	  
	/**
	 * 属性contacts_name的Getter方法.属性名：联系人姓名
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getContacts_name () {
		return contacts_name;
	}   
	/**
	 * 属性contacts_name的Setter方法.属性名：联系人姓名
	 * 创建日期:
	 * @param newContacts_name java.lang.String
	 */
	public void setContacts_name (java.lang.String newContacts_name ) {
	 	this.contacts_name = newContacts_name;
	} 	  
	/**
	 * 属性pk_user的Getter方法.属性名：系统用户
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_user () {
		return pk_user;
	}   
	/**
	 * 属性pk_user的Setter方法.属性名：系统用户
	 * 创建日期:
	 * @param newPk_user java.lang.String
	 */
	public void setPk_user (java.lang.String newPk_user ) {
	 	this.pk_user = newPk_user;
	} 	  
	/**
	 * 属性sex的Getter方法.属性名：性别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSex () {
		return sex;
	}   
	/**
	 * 属性sex的Setter方法.属性名：性别
	 * 创建日期:
	 * @param newSex java.lang.String
	 */
	public void setSex (java.lang.String newSex ) {
	 	this.sex = newSex;
	} 	  
	/**
	 * 属性post的Getter方法.属性名：职务
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPost () {
		return post;
	}   
	/**
	 * 属性post的Setter方法.属性名：职务
	 * 创建日期:
	 * @param newPost java.lang.String
	 */
	public void setPost (java.lang.String newPost ) {
	 	this.post = newPost;
	} 	  
	/**
	 * 属性phone_no的Getter方法.属性名：手机号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPhone_no () {
		return phone_no;
	}   
	/**
	 * 属性phone_no的Setter方法.属性名：手机号
	 * 创建日期:
	 * @param newPhone_no java.lang.String
	 */
	public void setPhone_no (java.lang.String newPhone_no ) {
	 	this.phone_no = newPhone_no;
	} 	  
	/**
	 * 属性email的Getter方法.属性名：邮箱
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getEmail () {
		return email;
	}   
	/**
	 * 属性email的Setter方法.属性名：邮箱
	 * 创建日期:
	 * @param newEmail java.lang.String
	 */
	public void setEmail (java.lang.String newEmail ) {
	 	this.email = newEmail;
	} 	  
	/**
	 * 属性qq_num的Getter方法.属性名：QQ
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQq_num () {
		return qq_num;
	}   
	/**
	 * 属性qq_num的Setter方法.属性名：QQ
	 * 创建日期:
	 * @param newQq_num java.lang.String
	 */
	public void setQq_num (java.lang.String newQq_num ) {
	 	this.qq_num = newQq_num;
	} 	  
	/**
	 * 属性contacts_type的Getter方法.属性名：联系人类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getContacts_type () {
		return contacts_type;
	}   
	/**
	 * 属性contacts_type的Setter方法.属性名：联系人类型
	 * 创建日期:
	 * @param newContacts_type java.lang.String
	 */
	public void setContacts_type (java.lang.String newContacts_type ) {
	 	this.contacts_type = newContacts_type;
	} 	  
	/**
	 * 属性remark的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newRemark java.lang.String
	 */
	public void setRemark (java.lang.String newRemark ) {
	 	this.remark = newRemark;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：备用字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：备用字段1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：备用字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：备用字段2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：备用字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：备用字段3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：备用字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：备用字段4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：备用字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：备用字段5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：备用字段6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：备用字段6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：备用字段7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：备用字段7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：备用字段8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：备用字段8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：备用字段9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：备用字段9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：备用字段10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：备用字段10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_contact_type";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_notice_contact_info";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_notice_contact_info";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_notice_contact_info";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public notice_contact_info() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapco.work_notice_contacts.notice_contact_info" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


