
package nc.scap.pub.sms.service.ah.delegate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MsgWSDelegate", targetNamespace = "http://192.168.1.43:9080/ahgzwsms")
@XmlSeeAlso({
    nc.scap.pub.sms.service.ah.delegate.ObjectFactory.class,
    nc.scap.pub.sms.service.ah.ObjectFactory.class
})
public interface MsgWSDelegate {

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMsgSvr", targetNamespace = "http://192.168.1.43:9080/ahgzwsms", className = "nc.scap.sms.service.ah.SendMsgSvr")
    @ResponseWrapper(localName = "sendMsgSvrResponse", targetNamespace = "http://192.168.1.43:9080/ahgzwsms", className = "nc.scap.sms.service.ah.SendMsgSvrResponse")
    public boolean sendMsgSvr(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

}
