/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapco.work_notice_manager;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class Notice_manager extends SuperVO {
	private java.lang.String pk_notice;
	private java.lang.String notice_no;
	private java.lang.String notice_title;
	private java.lang.String notice_style;
	private java.lang.String business_type;
	private java.lang.String notice_type;
	private nc.vo.pub.lang.UFDate notice_date;
	private java.lang.Integer day_num;
	private nc.vo.pub.lang.UFDate expiration_date;
	private java.lang.String notice_content;
	private java.lang.String is_remind;
	private java.lang.String remind_way;
	private java.lang.String remind_info;
	private java.lang.String data_type;
	private java.lang.String notice_psn;
	private java.lang.String notice_send_org;
	private java.lang.String notice_status;
	private java.lang.String is_auto_urge;
	private java.lang.String urge_start_time;
	private java.lang.String urge_info_trans_way;
	private java.lang.String urge_content_gzw;
	private java.lang.String urge_content_qy;
	private java.lang.String urge_frequency;
	private java.lang.String remark;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.vo.scapco.work_notice_manager.Receive_man[] id_receive_man;
	private nc.vo.scapco.work_notice_manager.Receive_notice[] id_eceive_notice;

	public static final String PK_NOTICE = "pk_notice";
	public static final String NOTICE_NO = "notice_no";
	public static final String NOTICE_TITLE = "notice_title";
	public static final String NOTICE_STYLE = "notice_style";
	public static final String BUSINESS_TYPE = "business_type";
	public static final String NOTICE_TYPE = "notice_type";
	public static final String NOTICE_DATE = "notice_date";
	public static final String DAY_NUM = "day_num";
	public static final String EXPIRATION_DATE = "expiration_date";
	public static final String NOTICE_CONTENT = "notice_content";
	public static final String IS_REMIND = "is_remind";
	public static final String REMIND_WAY = "remind_way";
	public static final String REMIND_INFO = "remind_info";
	public static final String DATA_TYPE = "data_type";
	public static final String NOTICE_PSN = "notice_psn";
	public static final String NOTICE_SEND_ORG = "notice_send_org";
	public static final String NOTICE_STATUS = "notice_status";
	public static final String IS_AUTO_URGE = "is_auto_urge";
	public static final String URGE_START_TIME = "urge_start_time";
	public static final String URGE_INFO_TRANS_WAY = "urge_info_trans_way";
	public static final String URGE_CONTENT_GZW = "urge_content_gzw";
	public static final String URGE_CONTENT_QY = "urge_content_qy";
	public static final String URGE_FREQUENCY = "urge_frequency";
	public static final String REMARK = "remark";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
			
	/**
	 * 属性pk_notice的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_notice () {
		return pk_notice;
	}   
	/**
	 * 属性pk_notice的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_notice java.lang.String
	 */
	public void setPk_notice (java.lang.String newPk_notice ) {
	 	this.pk_notice = newPk_notice;
	} 	  
	/**
	 * 属性notice_no的Getter方法.属性名：通知编号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_no () {
		return notice_no;
	}   
	/**
	 * 属性notice_no的Setter方法.属性名：通知编号
	 * 创建日期:
	 * @param newNotice_no java.lang.String
	 */
	public void setNotice_no (java.lang.String newNotice_no ) {
	 	this.notice_no = newNotice_no;
	} 	  
	/**
	 * 属性notice_title的Getter方法.属性名：通知标题
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_title () {
		return notice_title;
	}   
	/**
	 * 属性notice_title的Setter方法.属性名：通知标题
	 * 创建日期:
	 * @param newNotice_title java.lang.String
	 */
	public void setNotice_title (java.lang.String newNotice_title ) {
	 	this.notice_title = newNotice_title;
	} 	  
	/**
	 * 属性notice_style的Getter方法.属性名：通知类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_style () {
		return notice_style;
	}   
	/**
	 * 属性notice_style的Setter方法.属性名：通知类型
	 * 创建日期:
	 * @param newNotice_style java.lang.String
	 */
	public void setNotice_style (java.lang.String newNotice_style ) {
	 	this.notice_style = newNotice_style;
	} 	  
	/**
	 * 属性business_type的Getter方法.属性名：报告业务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusiness_type () {
		return business_type;
	}   
	/**
	 * 属性business_type的Setter方法.属性名：报告业务类型
	 * 创建日期:
	 * @param newBusiness_type java.lang.String
	 */
	public void setBusiness_type (java.lang.String newBusiness_type ) {
	 	this.business_type = newBusiness_type;
	} 	  
	/**
	 * 属性notice_type的Getter方法.属性名：报告实例类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_type () {
		return notice_type;
	}   
	/**
	 * 属性notice_type的Setter方法.属性名：报告实例类型
	 * 创建日期:
	 * @param newNotice_type java.lang.String
	 */
	public void setNotice_type (java.lang.String newNotice_type ) {
	 	this.notice_type = newNotice_type;
	} 	  
	/**
	 * 属性notice_date的Getter方法.属性名：通知日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getNotice_date () {
		return notice_date;
	}   
	/**
	 * 属性notice_date的Setter方法.属性名：通知日期
	 * 创建日期:
	 * @param newNotice_date nc.vo.pub.lang.UFDate
	 */
	public void setNotice_date (nc.vo.pub.lang.UFDate newNotice_date ) {
	 	this.notice_date = newNotice_date;
	} 	  
	/**
	 * 属性day_num的Getter方法.属性名：提前催报天数
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDay_num () {
		return day_num;
	}   
	/**
	 * 属性day_num的Setter方法.属性名：提前催报天数
	 * 创建日期:
	 * @param newDay_num java.lang.Integer
	 */
	public void setDay_num (java.lang.Integer newDay_num ) {
	 	this.day_num = newDay_num;
	} 	  
	/**
	 * 属性expiration_date的Getter方法.属性名：上报截止日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getExpiration_date () {
		return expiration_date;
	}   
	/**
	 * 属性expiration_date的Setter方法.属性名：上报截止日期
	 * 创建日期:
	 * @param newExpiration_date nc.vo.pub.lang.UFDate
	 */
	public void setExpiration_date (nc.vo.pub.lang.UFDate newExpiration_date ) {
	 	this.expiration_date = newExpiration_date;
	} 	  
	/**
	 * 属性notice_content的Getter方法.属性名：通知内容
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_content () {
		return notice_content;
	}   
	/**
	 * 属性notice_content的Setter方法.属性名：通知内容
	 * 创建日期:
	 * @param newNotice_content java.lang.String
	 */
	public void setNotice_content (java.lang.String newNotice_content ) {
	 	this.notice_content = newNotice_content;
	} 	  
	/**
	 * 属性is_remind的Getter方法.属性名：是否发送提醒
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIs_remind () {
		return is_remind;
	}   
	/**
	 * 属性is_remind的Setter方法.属性名：是否发送提醒
	 * 创建日期:
	 * @param newIs_remind java.lang.String
	 */
	public void setIs_remind (java.lang.String newIs_remind ) {
	 	this.is_remind = newIs_remind;
	} 	  
	/**
	 * 属性remind_way的Getter方法.属性名：提醒方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemind_way () {
		return remind_way;
	}   
	/**
	 * 属性remind_way的Setter方法.属性名：提醒方式
	 * 创建日期:
	 * @param newRemind_way java.lang.String
	 */
	public void setRemind_way (java.lang.String newRemind_way ) {
	 	this.remind_way = newRemind_way;
	} 	  
	/**
	 * 属性remind_info的Getter方法.属性名：提醒内容
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemind_info () {
		return remind_info;
	}   
	/**
	 * 属性remind_info的Setter方法.属性名：提醒内容
	 * 创建日期:
	 * @param newRemind_info java.lang.String
	 */
	public void setRemind_info (java.lang.String newRemind_info ) {
	 	this.remind_info = newRemind_info;
	} 	  
	/**
	 * 属性data_type的Getter方法.属性名：资料类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getData_type () {
		return data_type;
	}   
	/**
	 * 属性data_type的Setter方法.属性名：资料类型
	 * 创建日期:
	 * @param newData_type java.lang.String
	 */
	public void setData_type (java.lang.String newData_type ) {
	 	this.data_type = newData_type;
	} 	  
	/**
	 * 属性notice_psn的Getter方法.属性名：通知发送人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_psn () {
		return notice_psn;
	}   
	/**
	 * 属性notice_psn的Setter方法.属性名：通知发送人
	 * 创建日期:
	 * @param newNotice_psn java.lang.String
	 */
	public void setNotice_psn (java.lang.String newNotice_psn ) {
	 	this.notice_psn = newNotice_psn;
	} 	  
	/**
	 * 属性notice_send_org的Getter方法.属性名：通知发送单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_send_org () {
		return notice_send_org;
	}   
	/**
	 * 属性notice_send_org的Setter方法.属性名：通知发送单位
	 * 创建日期:
	 * @param newNotice_send_org java.lang.String
	 */
	public void setNotice_send_org (java.lang.String newNotice_send_org ) {
	 	this.notice_send_org = newNotice_send_org;
	} 	  
	/**
	 * 属性notice_status的Getter方法.属性名：通知下发状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_status () {
		return notice_status;
	}   
	/**
	 * 属性notice_status的Setter方法.属性名：通知下发状态
	 * 创建日期:
	 * @param newNotice_status java.lang.String
	 */
	public void setNotice_status (java.lang.String newNotice_status ) {
	 	this.notice_status = newNotice_status;
	} 	  
	/**
	 * 属性is_auto_urge的Getter方法.属性名：是否自动催报
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIs_auto_urge () {
		return is_auto_urge;
	}   
	/**
	 * 属性is_auto_urge的Setter方法.属性名：是否自动催报
	 * 创建日期:
	 * @param newIs_auto_urge java.lang.String
	 */
	public void setIs_auto_urge (java.lang.String newIs_auto_urge ) {
	 	this.is_auto_urge = newIs_auto_urge;
	} 	  
	/**
	 * 属性urge_start_time的Getter方法.属性名：催报开始时间
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUrge_start_time () {
		return urge_start_time;
	}   
	/**
	 * 属性urge_start_time的Setter方法.属性名：催报开始时间
	 * 创建日期:
	 * @param newUrge_start_time java.lang.String
	 */
	public void setUrge_start_time (java.lang.String newUrge_start_time ) {
	 	this.urge_start_time = newUrge_start_time;
	} 	  
	/**
	 * 属性urge_info_trans_way的Getter方法.属性名：催报信息发送方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUrge_info_trans_way () {
		return urge_info_trans_way;
	}   
	/**
	 * 属性urge_info_trans_way的Setter方法.属性名：催报信息发送方式
	 * 创建日期:
	 * @param newUrge_info_trans_way java.lang.String
	 */
	public void setUrge_info_trans_way (java.lang.String newUrge_info_trans_way ) {
	 	this.urge_info_trans_way = newUrge_info_trans_way;
	} 	  
	/**
	 * 属性urge_content_gzw的Getter方法.属性名：报送统计内容格式（国资委用户）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUrge_content_gzw () {
		return urge_content_gzw;
	}   
	/**
	 * 属性urge_content_gzw的Setter方法.属性名：报送统计内容格式（国资委用户）
	 * 创建日期:
	 * @param newUrge_content_gzw java.lang.String
	 */
	public void setUrge_content_gzw (java.lang.String newUrge_content_gzw ) {
	 	this.urge_content_gzw = newUrge_content_gzw;
	} 	  
	/**
	 * 属性urge_content_qy的Getter方法.属性名：催报消息内容格式（企业用户）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUrge_content_qy () {
		return urge_content_qy;
	}   
	/**
	 * 属性urge_content_qy的Setter方法.属性名：催报消息内容格式（企业用户）
	 * 创建日期:
	 * @param newUrge_content_qy java.lang.String
	 */
	public void setUrge_content_qy (java.lang.String newUrge_content_qy ) {
	 	this.urge_content_qy = newUrge_content_qy;
	} 	  
	/**
	 * 属性urge_frequency的Getter方法.属性名：催报频率
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUrge_frequency () {
		return urge_frequency;
	}   
	/**
	 * 属性urge_frequency的Setter方法.属性名：催报频率
	 * 创建日期:
	 * @param newUrge_frequency java.lang.String
	 */
	public void setUrge_frequency (java.lang.String newUrge_frequency ) {
	 	this.urge_frequency = newUrge_frequency;
	} 	  
	/**
	 * 属性remark的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newRemark java.lang.String
	 */
	public void setRemark (java.lang.String newRemark ) {
	 	this.remark = newRemark;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：备用字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：备用字段1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：备用字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：备用字段2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：备用字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：备用字段3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：备用字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：备用字段4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：备用字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：备用字段5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：备用字段6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：备用字段6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：备用字段7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：备用字段7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：备用字段8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：备用字段8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：备用字段9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：备用字段9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：备用字段10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：备用字段10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性id_receive_man的Getter方法.属性名：id_receive_man
	 * 创建日期:
	 * @return nc.vo.scapco.work_notice_manager.Receive_man[]
	 */
	public nc.vo.scapco.work_notice_manager.Receive_man[] getId_receive_man () {
		return id_receive_man;
	}   
	/**
	 * 属性id_receive_man的Setter方法.属性名：id_receive_man
	 * 创建日期:
	 * @param newId_receive_man nc.vo.scapco.work_notice_manager.Receive_man[]
	 */
	public void setId_receive_man (nc.vo.scapco.work_notice_manager.Receive_man[] newId_receive_man ) {
	 	this.id_receive_man = newId_receive_man;
	} 	  
	/**
	 * 属性id_eceive_notice的Getter方法.属性名：id_eceive_notice
	 * 创建日期:
	 * @return nc.vo.scapco.work_notice_manager.Receive_notice[]
	 */
	public nc.vo.scapco.work_notice_manager.Receive_notice[] getId_eceive_notice () {
		return id_eceive_notice;
	}   
	/**
	 * 属性id_eceive_notice的Setter方法.属性名：id_eceive_notice
	 * 创建日期:
	 * @param newId_eceive_notice nc.vo.scapco.work_notice_manager.Receive_notice[]
	 */
	public void setId_eceive_notice (nc.vo.scapco.work_notice_manager.Receive_notice[] newId_eceive_notice ) {
	 	this.id_eceive_notice = newId_eceive_notice;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_notice";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_notice_manager";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_notice_manager";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public Notice_manager() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapco.work_notice_manager.Notice_manager" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


