/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapjj.material;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class Attach_BVO extends SuperVO {
	private java.lang.String pk_material_h;
	private java.lang.String pk_material_b;
	private java.lang.Integer rowno;
	private java.lang.String mc;
	private java.lang.String lx;
	private java.lang.String dx;
	private java.lang.String zhxgr;
	private nc.vo.pub.lang.UFDateTime zhxgsj;
	private java.lang.String vnote;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_MATERIAL_H = "pk_material_h";
	public static final String PK_MATERIAL_B = "pk_material_b";
	public static final String ROWNO = "rowno";
	public static final String MC = "mc";
	public static final String LX = "lx";
	public static final String DX = "dx";
	public static final String ZHXGR = "zhxgr";
	public static final String ZHXGSJ = "zhxgsj";
	public static final String VNOTE = "vnote";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
			
	/**
	 * 属性pk_material_h的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_material_h () {
		return pk_material_h;
	}   
	/**
	 * 属性pk_material_h的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_material_h java.lang.String
	 */
	public void setPk_material_h (java.lang.String newPk_material_h ) {
	 	this.pk_material_h = newPk_material_h;
	} 	  
	/**
	 * 属性pk_material_b的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_material_b () {
		return pk_material_b;
	}   
	/**
	 * 属性pk_material_b的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_material_b java.lang.String
	 */
	public void setPk_material_b (java.lang.String newPk_material_b ) {
	 	this.pk_material_b = newPk_material_b;
	} 	  
	/**
	 * 属性rowno的Getter方法.属性名：行号
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getRowno () {
		return rowno;
	}   
	/**
	 * 属性rowno的Setter方法.属性名：行号
	 * 创建日期:
	 * @param newRowno java.lang.Integer
	 */
	public void setRowno (java.lang.Integer newRowno ) {
	 	this.rowno = newRowno;
	} 	  
	/**
	 * 属性mc的Getter方法.属性名：名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMc () {
		return mc;
	}   
	/**
	 * 属性mc的Setter方法.属性名：名称
	 * 创建日期:
	 * @param newMc java.lang.String
	 */
	public void setMc (java.lang.String newMc ) {
	 	this.mc = newMc;
	} 	  
	/**
	 * 属性lx的Getter方法.属性名：类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getLx () {
		return lx;
	}   
	/**
	 * 属性lx的Setter方法.属性名：类型
	 * 创建日期:
	 * @param newLx java.lang.String
	 */
	public void setLx (java.lang.String newLx ) {
	 	this.lx = newLx;
	} 	  
	/**
	 * 属性dx的Getter方法.属性名：大小
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDx () {
		return dx;
	}   
	/**
	 * 属性dx的Setter方法.属性名：大小
	 * 创建日期:
	 * @param newDx java.lang.String
	 */
	public void setDx (java.lang.String newDx ) {
	 	this.dx = newDx;
	} 	  
	/**
	 * 属性zhxgr的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getZhxgr () {
		return zhxgr;
	}   
	/**
	 * 属性zhxgr的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newZhxgr java.lang.String
	 */
	public void setZhxgr (java.lang.String newZhxgr ) {
	 	this.zhxgr = newZhxgr;
	} 	  
	/**
	 * 属性zhxgsj的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getZhxgsj () {
		return zhxgsj;
	}   
	/**
	 * 属性zhxgsj的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newZhxgsj nc.vo.pub.lang.UFDateTime
	 */
	public void setZhxgsj (nc.vo.pub.lang.UFDateTime newZhxgsj ) {
	 	this.zhxgsj = newZhxgsj;
	} 	  
	/**
	 * 属性vnote的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVnote () {
		return vnote;
	}   
	/**
	 * 属性vnote的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newVnote java.lang.String
	 */
	public void setVnote (java.lang.String newVnote ) {
	 	this.vnote = newVnote;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：def1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：def1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：def2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：def2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：def3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：def3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：def4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：def4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：def5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：def5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：def6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：def6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：def7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：def7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：def8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：def8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：def9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：def9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：def10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：def10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_material_h";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_material_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapjj_attach_b";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapjj_attach_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public Attach_BVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapjj.material.Attach_BVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


