/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapjj.material;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class Material_HVO extends SuperVO {
	private java.lang.String pk_material_h;
	private java.lang.String billno;
	private java.lang.String formtitle;
	private java.lang.String year;
	private java.lang.String month;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String zllx;
	private java.lang.String wlorww;
	private java.lang.Integer djcs;
	private java.lang.String vnote;
	private java.lang.String fbzt;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String billmaker;
	private nc.vo.pub.lang.UFDateTime billdate;
	private java.lang.String approver;
	private java.lang.String formstate;
	private nc.vo.pub.lang.UFDateTime approvedate;
	private java.lang.String approvememo;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.vo.scapjj.material.Attach_BVO[] id_material_b;
	private nc.vo.scapjj.material.Otheruser_BVO[] id_otheruser_b;

	public static final String PK_MATERIAL_H = "pk_material_h";
	public static final String BILLNO = "billno";
	public static final String FORMTITLE = "formtitle";
	public static final String YEAR = "year";
	public static final String MONTH = "month";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String ZLLX = "zllx";
	public static final String WLORWW = "wlorww";
	public static final String DJCS = "djcs";
	public static final String VNOTE = "vnote";
	public static final String FBZT = "fbzt";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLDATE = "billdate";
	public static final String APPROVER = "approver";
	public static final String FORMSTATE = "formstate";
	public static final String APPROVEDATE = "approvedate";
	public static final String APPROVEMEMO = "approvememo";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
			
	/**
	 * 属性pk_material_h的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_material_h () {
		return pk_material_h;
	}   
	/**
	 * 属性pk_material_h的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_material_h java.lang.String
	 */
	public void setPk_material_h (java.lang.String newPk_material_h ) {
	 	this.pk_material_h = newPk_material_h;
	} 	  
	/**
	 * 属性billno的Getter方法.属性名：单据号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillno () {
		return billno;
	}   
	/**
	 * 属性billno的Setter方法.属性名：单据号
	 * 创建日期:
	 * @param newBillno java.lang.String
	 */
	public void setBillno (java.lang.String newBillno ) {
	 	this.billno = newBillno;
	} 	  
	/**
	 * 属性formtitle的Getter方法.属性名：单据标题
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormtitle () {
		return formtitle;
	}   
	/**
	 * 属性formtitle的Setter方法.属性名：单据标题
	 * 创建日期:
	 * @param newFormtitle java.lang.String
	 */
	public void setFormtitle (java.lang.String newFormtitle ) {
	 	this.formtitle = newFormtitle;
	} 	  
	/**
	 * 属性year的Getter方法.属性名：年度
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getYear () {
		return year;
	}   
	/**
	 * 属性year的Setter方法.属性名：年度
	 * 创建日期:
	 * @param newYear java.lang.String
	 */
	public void setYear (java.lang.String newYear ) {
	 	this.year = newYear;
	} 	  
	/**
	 * 属性month的Getter方法.属性名：月度
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMonth () {
		return month;
	}   
	/**
	 * 属性month的Setter方法.属性名：月度
	 * 创建日期:
	 * @param newMonth java.lang.String
	 */
	public void setMonth (java.lang.String newMonth ) {
	 	this.month = newMonth;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：主题
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：主题
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：主要内容
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：主要内容
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性zllx的Getter方法.属性名：资料类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getZllx () {
		return zllx;
	}   
	/**
	 * 属性zllx的Setter方法.属性名：资料类型
	 * 创建日期:
	 * @param newZllx java.lang.String
	 */
	public void setZllx (java.lang.String newZllx ) {
	 	this.zllx = newZllx;
	} 	  
	/**
	 * 属性wlorww的Getter方法.属性名：委内/委外
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getWlorww () {
		return wlorww;
	}   
	/**
	 * 属性wlorww的Setter方法.属性名：委内/委外
	 * 创建日期:
	 * @param newWlorww java.lang.String
	 */
	public void setWlorww (java.lang.String newWlorww ) {
	 	this.wlorww = newWlorww;
	} 	  
	/**
	 * 属性djcs的Getter方法.属性名：点击次数
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDjcs () {
		return djcs;
	}   
	/**
	 * 属性djcs的Setter方法.属性名：点击次数
	 * 创建日期:
	 * @param newDjcs java.lang.Integer
	 */
	public void setDjcs (java.lang.Integer newDjcs ) {
	 	this.djcs = newDjcs;
	} 	  
	/**
	 * 属性vnote的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVnote () {
		return vnote;
	}   
	/**
	 * 属性vnote的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newVnote java.lang.String
	 */
	public void setVnote (java.lang.String newVnote ) {
	 	this.vnote = newVnote;
	} 	  
	/**
	 * 属性fbzt的Getter方法.属性名：发布状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFbzt () {
		return fbzt;
	}   
	/**
	 * 属性fbzt的Setter方法.属性名：发布状态
	 * 创建日期:
	 * @param newFbzt java.lang.String
	 */
	public void setFbzt (java.lang.String newFbzt ) {
	 	this.fbzt = newFbzt;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：发布单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：发布单位
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：发布人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：发布人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：发布时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：发布时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性billmaker的Getter方法.属性名：制单人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return billmaker;
	}   
	/**
	 * 属性billmaker的Setter方法.属性名：制单人
	 * 创建日期:
	 * @param newBillmaker java.lang.String
	 */
	public void setBillmaker (java.lang.String newBillmaker ) {
	 	this.billmaker = newBillmaker;
	} 	  
	/**
	 * 属性billdate的Getter方法.属性名：制单时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getBilldate () {
		return billdate;
	}   
	/**
	 * 属性billdate的Setter方法.属性名：制单时间
	 * 创建日期:
	 * @param newBilldate nc.vo.pub.lang.UFDateTime
	 */
	public void setBilldate (nc.vo.pub.lang.UFDateTime newBilldate ) {
	 	this.billdate = newBilldate;
	} 	  
	/**
	 * 属性approver的Getter方法.属性名：审批人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprover () {
		return approver;
	}   
	/**
	 * 属性approver的Setter方法.属性名：审批人
	 * 创建日期:
	 * @param newApprover java.lang.String
	 */
	public void setApprover (java.lang.String newApprover ) {
	 	this.approver = newApprover;
	} 	  
	/**
	 * 属性formstate的Getter方法.属性名：审批状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormstate () {
		return formstate;
	}   
	/**
	 * 属性formstate的Setter方法.属性名：审批状态
	 * 创建日期:
	 * @param newFormstate java.lang.String
	 */
	public void setFormstate (java.lang.String newFormstate ) {
	 	this.formstate = newFormstate;
	} 	  
	/**
	 * 属性approvedate的Getter方法.属性名：审批时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getApprovedate () {
		return approvedate;
	}   
	/**
	 * 属性approvedate的Setter方法.属性名：审批时间
	 * 创建日期:
	 * @param newApprovedate nc.vo.pub.lang.UFDateTime
	 */
	public void setApprovedate (nc.vo.pub.lang.UFDateTime newApprovedate ) {
	 	this.approvedate = newApprovedate;
	} 	  
	/**
	 * 属性approvememo的Getter方法.属性名：审核批语
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprovememo () {
		return approvememo;
	}   
	/**
	 * 属性approvememo的Setter方法.属性名：审核批语
	 * 创建日期:
	 * @param newApprovememo java.lang.String
	 */
	public void setApprovememo (java.lang.String newApprovememo ) {
	 	this.approvememo = newApprovememo;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：def1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：def1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：def2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：def2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：def3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：def3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：def4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：def4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：def5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：def5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：def6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：def6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：def7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：def7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：def8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：def8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：def9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：def9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：def10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：def10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性id_material_b的Getter方法.属性名：id_material_b
	 * 创建日期:
	 * @return nc.vo.scapjj.material.Attach_BVO[]
	 */
	public nc.vo.scapjj.material.Attach_BVO[] getId_material_b () {
		return id_material_b;
	}   
	/**
	 * 属性id_material_b的Setter方法.属性名：id_material_b
	 * 创建日期:
	 * @param newId_material_b nc.vo.scapjj.material.Attach_BVO[]
	 */
	public void setId_material_b (nc.vo.scapjj.material.Attach_BVO[] newId_material_b ) {
	 	this.id_material_b = newId_material_b;
	} 	  
	/**
	 * 属性id_otheruser_b的Getter方法.属性名：id_otheruser_b
	 * 创建日期:
	 * @return nc.vo.scapjj.material.Otheruser_BVO[]
	 */
	public nc.vo.scapjj.material.Otheruser_BVO[] getId_otheruser_b () {
		return id_otheruser_b;
	}   
	/**
	 * 属性id_otheruser_b的Setter方法.属性名：id_otheruser_b
	 * 创建日期:
	 * @param newId_otheruser_b nc.vo.scapjj.material.Otheruser_BVO[]
	 */
	public void setId_otheruser_b (nc.vo.scapjj.material.Otheruser_BVO[] newId_otheruser_b ) {
	 	this.id_otheruser_b = newId_otheruser_b;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_material_h";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapjj_material_h";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapjj_material_h";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public Material_HVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapjj.material.Material_HVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


