
package nc.scap.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendServiceSoap", targetNamespace = "http://access.xx95.net:8886/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendServiceSoap {


    /**
     * <br><br><b>说明：</b><br>短信发送方法，最多一次可发送50个号码。<br><br><br><b>状态报告说明：</b><br>00：成功<br>01：号码（超过上限50个）、参数为空、密码长度不是16位或内容长度超过210<br>02：用户鉴权失败<br>03：登录IP黑名单<br>10：余额不足（仅针对公免账户）<br>99：服务器接受失败<br>当返回值非以上定义，表现为某个字、词组时表示内容有屏蔽字
     * 
     * @param content
     * @param epid
     * @param phone
     * @param userName
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSms", action = "http://access.xx95.net:8886/SendSms")
    @WebResult(name = "SendSmsResult", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "SendSms", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.SendSms")
    @ResponseWrapper(localName = "SendSmsResponse", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.SendSmsResponse")
    public String sendSms(
        @WebParam(name = "epid", targetNamespace = "http://access.xx95.net:8886/")
        String epid,
        @WebParam(name = "User_Name", targetNamespace = "http://access.xx95.net:8886/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://access.xx95.net:8886/")
        String password,
        @WebParam(name = "phone", targetNamespace = "http://access.xx95.net:8886/")
        String phone,
        @WebParam(name = "content", targetNamespace = "http://access.xx95.net:8886/")
        String content);

    /**
     * <br><br><b>说明：</b><br>短信发送方法，最多一次可发送50个号码。<br><br><br><b>状态报告说明：</b><br>00：成功<br>01：号码（超过上限50个）、参数为空、密码长度不是16位或内容长度超过210<br>02：用户鉴权失败<br>03：登录IP黑名单<br>10：余额不足（仅针对公免账户）<br>99：服务器接受失败<br>当返回值非以上定义，表现为某个字、词组时表示内容有屏蔽字
     * 
     * @param content
     * @param epid
     * @param phone
     * @param userName
     * @param extendCode
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSmsEx", action = "http://access.xx95.net:8886/SendSmsEx")
    @WebResult(name = "SendSmsExResult", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "SendSmsEx", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.SendSmsEx")
    @ResponseWrapper(localName = "SendSmsExResponse", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.SendSmsExResponse")
    public String sendSmsEx(
        @WebParam(name = "epid", targetNamespace = "http://access.xx95.net:8886/")
        String epid,
        @WebParam(name = "User_Name", targetNamespace = "http://access.xx95.net:8886/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://access.xx95.net:8886/")
        String password,
        @WebParam(name = "phone", targetNamespace = "http://access.xx95.net:8886/")
        String phone,
        @WebParam(name = "content", targetNamespace = "http://access.xx95.net:8886/")
        String content,
        @WebParam(name = "ExtendCode", targetNamespace = "http://access.xx95.net:8886/")
        String extendCode);

    /**
     * <br><br><b>说明：</b><br>短信发送方法。<br><br><br><b>状态报告说明：</b><br>00：成功<br>01：号码（超过上限50个）、参数为空、密码长度不是16位或内容长度超过210<br>02：用户鉴权失败<br>03：登录IP黑名单<br>10：余额不足（仅针对公免账户）<br>99：服务器接受失败<br>当返回值非以上定义，表现为某个字、词组时表示内容有屏蔽字<br>infos参数格式：<br>号码序列1§内容1※号码序列2§内容2<br><br>注意：号码之间用引文 ,连接，不能超过50个号码。
     * 
     * @param epid
     * @param infos
     * @param userName
     * @param extendCode
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSmsEx1", action = "http://access.xx95.net:8886/SendSmsEx1")
    @WebResult(name = "SendSmsEx1Result", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "SendSmsEx1", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.SendSmsEx1")
    @ResponseWrapper(localName = "SendSmsEx1Response", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.SendSmsEx1Response")
    public String sendSmsEx1(
        @WebParam(name = "epid", targetNamespace = "http://access.xx95.net:8886/")
        String epid,
        @WebParam(name = "User_Name", targetNamespace = "http://access.xx95.net:8886/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://access.xx95.net:8886/")
        String password,
        @WebParam(name = "infos", targetNamespace = "http://access.xx95.net:8886/")
        String infos,
        @WebParam(name = "ExtendCode", targetNamespace = "http://access.xx95.net:8886/")
        String extendCode);

    /**
     * <br><br><b>检查屏蔽字：</b><br>如果有屏蔽字将返回屏蔽字，否则返回为空。
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChkBadWord", action = "http://access.xx95.net:8886/ChkBadWord")
    @WebResult(name = "ChkBadWordResult", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "ChkBadWord", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.ChkBadWord")
    @ResponseWrapper(localName = "ChkBadWordResponse", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.ChkBadWordResponse")
    public String chkBadWord(
        @WebParam(name = "content", targetNamespace = "http://access.xx95.net:8886/")
        String content);

    /**
     * <br><br><b>更改密码：</b><br>需要输入旧密码进行验证。<br><br><b>返回状态：</b><br><br>00：成功<br>01：用户鉴权失败(可能登录信息不正确或超过安全限制，每分钟仅能更改一次，共有5次更改机会，超过五次请联系我们处理。)<br>02：两次输入密码不匹配<br>99：服务器接受失败<br>
     * 
     * @param epid
     * @param confirmPassword
     * @param userName
     * @param oldPass
     * @param newPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangePass", action = "http://access.xx95.net:8886/ChangePass")
    @WebResult(name = "ChangePassResult", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "ChangePass", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.ChangePass")
    @ResponseWrapper(localName = "ChangePassResponse", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.ChangePassResponse")
    public String changePass(
        @WebParam(name = "EPID", targetNamespace = "http://access.xx95.net:8886/")
        String epid,
        @WebParam(name = "User_Name", targetNamespace = "http://access.xx95.net:8886/")
        String userName,
        @WebParam(name = "OldPass", targetNamespace = "http://access.xx95.net:8886/")
        String oldPass,
        @WebParam(name = "NewPass", targetNamespace = "http://access.xx95.net:8886/")
        String newPass,
        @WebParam(name = "Confirm_Password", targetNamespace = "http://access.xx95.net:8886/")
        String confirmPassword);

    /**
     * <br><br><b>获取用户条数（仅针对公免账户）：</b><br>需要输入ID\账户\密码进行验证。<br><b>返回状态：</b><br><br>01：用户鉴权失败<br>02：用户信息不能为空<br>99：服务器接受失败<br>
     * 
     * @param epid
     * @param userName
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "User_Overage", action = "http://access.xx95.net:8886/User_Overage")
    @WebResult(name = "User_OverageResult", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "User_Overage", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.UserOverage")
    @ResponseWrapper(localName = "User_OverageResponse", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.UserOverageResponse")
    public String userOverage(
        @WebParam(name = "EPID", targetNamespace = "http://access.xx95.net:8886/")
        String epid,
        @WebParam(name = "User_Name", targetNamespace = "http://access.xx95.net:8886/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://access.xx95.net:8886/")
        String password);

    /**
     * <br><br><b>接收消息函数：</b><br>需要输入密码进行验证。<br><br><b>返回状态：</b><br><br>00：成功<br>01：用户鉴权失败<br>02：暂无上行数据<br>99：服务器接受失败<br>
     * 
     * @param epid
     * @param cls
     * @param mosId
     * @param userName
     * @param userPass
     * @return
     *     returns nc.scap.sms.ah.RecvMessageResponse.RecvMessageResult
     */
    @WebMethod(operationName = "RecvMessage", action = "http://access.xx95.net:8886/RecvMessage")
    @WebResult(name = "RecvMessageResult", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "RecvMessage", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.RecvMessage")
    @ResponseWrapper(localName = "RecvMessageResponse", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.RecvMessageResponse")
    public nc.scap.sms.RecvMessageResponse.RecvMessageResult recvMessage(
        @WebParam(name = "EPID", targetNamespace = "http://access.xx95.net:8886/")
        String epid,
        @WebParam(name = "User_Name", targetNamespace = "http://access.xx95.net:8886/")
        String userName,
        @WebParam(name = "User_Pass", targetNamespace = "http://access.xx95.net:8886/")
        String userPass,
        @WebParam(name = "MosId", targetNamespace = "http://access.xx95.net:8886/")
        String mosId,
        @WebParam(name = "Cls", targetNamespace = "http://access.xx95.net:8886/")
        String cls);

    /**
     * <br><br><b>接收消息函数：</b><br>需要输入密码进行验证。<br><br><b>返回状态：</b><br><br>00：成功<br>01：用户鉴权失败<br>02：暂无上行数据<br>99：服务器接受失败<br>
     * 
     * @param epid
     * @param cls
     * @param mosId
     * @param userName
     * @param userPass
     * @return
     *     returns nc.scap.sms.ah.RecvMessageExResponse.RecvMessageExResult
     */
    @WebMethod(operationName = "RecvMessageEx", action = "http://access.xx95.net:8886/RecvMessageEx")
    @WebResult(name = "RecvMessageExResult", targetNamespace = "http://access.xx95.net:8886/")
    @RequestWrapper(localName = "RecvMessageEx", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.RecvMessageEx")
    @ResponseWrapper(localName = "RecvMessageExResponse", targetNamespace = "http://access.xx95.net:8886/", className = "nc.scap.sms.ah.RecvMessageExResponse")
    public nc.scap.sms.RecvMessageExResponse.RecvMessageExResult recvMessageEx(
        @WebParam(name = "EPID", targetNamespace = "http://access.xx95.net:8886/")
        String epid,
        @WebParam(name = "User_Name", targetNamespace = "http://access.xx95.net:8886/")
        String userName,
        @WebParam(name = "User_Pass", targetNamespace = "http://access.xx95.net:8886/")
        String userPass,
        @WebParam(name = "MosId", targetNamespace = "http://access.xx95.net:8886/")
        String mosId,
        @WebParam(name = "Cls", targetNamespace = "http://access.xx95.net:8886/")
        String cls);

}
