/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapco.work_report_type;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class receive_org extends SuperVO {
	private java.lang.String pk_work_report_type;
	private java.lang.String pk_receive_org;
	private java.lang.String notice_org;
	private java.lang.String notice_visual_org;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_WORK_REPORT_TYPE = "pk_work_report_type";
	public static final String PK_RECEIVE_ORG = "pk_receive_org";
	public static final String NOTICE_ORG = "notice_org";
	public static final String NOTICE_VISUAL_ORG = "notice_visual_org";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
			
	/**
	 * 属性pk_work_report_type的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_work_report_type () {
		return pk_work_report_type;
	}   
	/**
	 * 属性pk_work_report_type的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_work_report_type java.lang.String
	 */
	public void setPk_work_report_type (java.lang.String newPk_work_report_type ) {
	 	this.pk_work_report_type = newPk_work_report_type;
	} 	  
	/**
	 * 属性pk_receive_org的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_receive_org () {
		return pk_receive_org;
	}   
	/**
	 * 属性pk_receive_org的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_receive_org java.lang.String
	 */
	public void setPk_receive_org (java.lang.String newPk_receive_org ) {
	 	this.pk_receive_org = newPk_receive_org;
	} 	  
	/**
	 * 属性notice_org的Getter方法.属性名：接收企业
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_org () {
		return notice_org;
	}   
	/**
	 * 属性notice_org的Setter方法.属性名：接收企业
	 * 创建日期:
	 * @param newNotice_org java.lang.String
	 */
	public void setNotice_org (java.lang.String newNotice_org ) {
	 	this.notice_org = newNotice_org;
	} 	  
	/**
	 * 属性notice_visual_org的Getter方法.属性名：接收组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNotice_visual_org () {
		return notice_visual_org;
	}   
	/**
	 * 属性notice_visual_org的Setter方法.属性名：接收组织
	 * 创建日期:
	 * @param newNotice_visual_org java.lang.String
	 */
	public void setNotice_visual_org (java.lang.String newNotice_visual_org ) {
	 	this.notice_visual_org = newNotice_visual_org;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：备用字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：备用字段1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：备用字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：备用字段2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：备用字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：备用字段3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：备用字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：备用字段4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：备用字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：备用字段5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_work_report_type";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_receive_org";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_receive_org_type";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_receive_org_type";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public receive_org() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapco.work_report_type.receive_org" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


