
package nc.scap.pub.sms.service.ah.delegate;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MsgWSService", targetNamespace = "http://192.168.1.43:9080/ahgzwsms", wsdlLocation = "http://192.168.138.43:9080/ahgzwsms/MsgWSPort?wsdl")
public class MsgWSService
    extends Service
{

    private final static URL MSGWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(nc.scap.pub.sms.service.ah.delegate.MsgWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = nc.scap.pub.sms.service.ah.delegate.MsgWSService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.138.43:9080/ahgzwsms/MsgWSPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.138.43:9080/ahgzwsms/MsgWSPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MSGWSSERVICE_WSDL_LOCATION = url;
    }

    public MsgWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MsgWSService() {
        super(MSGWSSERVICE_WSDL_LOCATION, new QName("http://192.168.1.43:9080/ahgzwsms", "MsgWSService"));
    }

    /**
     * 
     * @return
     *     returns MsgWSDelegate
     */
    @WebEndpoint(name = "MsgWSPort")
    public MsgWSDelegate getMsgWSPort() {
        return super.getPort(new QName("http://192.168.1.43:9080/ahgzwsms", "MsgWSPort"), MsgWSDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MsgWSDelegate
     */
    @WebEndpoint(name = "MsgWSPort")
    public MsgWSDelegate getMsgWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://192.168.1.43:9080/ahgzwsms", "MsgWSPort"), MsgWSDelegate.class, features);
    }

}
