/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapjj.userpsn;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class V_userpsnVO extends SuperVO {
	private java.lang.String cuserid;
	private java.lang.String user_code;
	private java.lang.String user_name;
	private java.lang.String szdw;
	private java.lang.String sex;
	private java.lang.String zw;
	private java.lang.String zc;
	private java.lang.String tel;
	private java.lang.String mobile;
	private java.lang.String email;
	private java.lang.String pk_org;
	private java.lang.String pk_zw;
	private java.lang.String pk_zc;
	private java.lang.String pk_dept;
	private java.lang.String deptname;
	private java.lang.String enablestate;
	private java.lang.String user_type;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String CUSERID = "cuserid";
	public static final String USER_CODE = "user_code";
	public static final String USER_NAME = "user_name";
	public static final String SZDW = "szdw";
	public static final String SEX = "sex";
	public static final String ZW = "zw";
	public static final String ZC = "zc";
	public static final String TEL = "tel";
	public static final String MOBILE = "mobile";
	public static final String EMAIL = "email";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ZW = "pk_zw";
	public static final String PK_ZC = "pk_zc";
	public static final String PK_DEPT = "pk_dept";
	public static final String DEPTNAME = "deptname";
	public static final String ENABLESTATE = "enablestate";
	public static final String USER_TYPE = "user_type";
			
	/**
	 * 属性cuserid的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCuserid () {
		return cuserid;
	}   
	/**
	 * 属性cuserid的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newCuserid java.lang.String
	 */
	public void setCuserid (java.lang.String newCuserid ) {
	 	this.cuserid = newCuserid;
	} 	  
	/**
	 * 属性user_code的Getter方法.属性名：用户编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUser_code () {
		return user_code;
	}   
	/**
	 * 属性user_code的Setter方法.属性名：用户编码
	 * 创建日期:
	 * @param newUser_code java.lang.String
	 */
	public void setUser_code (java.lang.String newUser_code ) {
	 	this.user_code = newUser_code;
	} 	  
	/**
	 * 属性user_name的Getter方法.属性名：用户名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUser_name () {
		return user_name;
	}   
	/**
	 * 属性user_name的Setter方法.属性名：用户名称
	 * 创建日期:
	 * @param newUser_name java.lang.String
	 */
	public void setUser_name (java.lang.String newUser_name ) {
	 	this.user_name = newUser_name;
	} 	  
	/**
	 * 属性szdw的Getter方法.属性名：所在单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSzdw () {
		return szdw;
	}   
	/**
	 * 属性szdw的Setter方法.属性名：所在单位
	 * 创建日期:
	 * @param newSzdw java.lang.String
	 */
	public void setSzdw (java.lang.String newSzdw ) {
	 	this.szdw = newSzdw;
	} 	  
	/**
	 * 属性sex的Getter方法.属性名：性别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSex () {
		return sex;
	}   
	/**
	 * 属性sex的Setter方法.属性名：性别
	 * 创建日期:
	 * @param newSex java.lang.String
	 */
	public void setSex (java.lang.String newSex ) {
	 	this.sex = newSex;
	} 	  
	/**
	 * 属性zw的Getter方法.属性名：职务
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getZw () {
		return zw;
	}   
	/**
	 * 属性zw的Setter方法.属性名：职务
	 * 创建日期:
	 * @param newZw java.lang.String
	 */
	public void setZw (java.lang.String newZw ) {
	 	this.zw = newZw;
	} 	  
	/**
	 * 属性zc的Getter方法.属性名：职称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getZc () {
		return zc;
	}   
	/**
	 * 属性zc的Setter方法.属性名：职称
	 * 创建日期:
	 * @param newZc java.lang.String
	 */
	public void setZc (java.lang.String newZc ) {
	 	this.zc = newZc;
	} 	  
	/**
	 * 属性tel的Getter方法.属性名：联系电话
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTel () {
		return tel;
	}   
	/**
	 * 属性tel的Setter方法.属性名：联系电话
	 * 创建日期:
	 * @param newTel java.lang.String
	 */
	public void setTel (java.lang.String newTel ) {
	 	this.tel = newTel;
	} 	  
	/**
	 * 属性mobile的Getter方法.属性名：手机
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMobile () {
		return mobile;
	}   
	/**
	 * 属性mobile的Setter方法.属性名：手机
	 * 创建日期:
	 * @param newMobile java.lang.String
	 */
	public void setMobile (java.lang.String newMobile ) {
	 	this.mobile = newMobile;
	} 	  
	/**
	 * 属性email的Getter方法.属性名：邮箱
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getEmail () {
		return email;
	}   
	/**
	 * 属性email的Setter方法.属性名：邮箱
	 * 创建日期:
	 * @param newEmail java.lang.String
	 */
	public void setEmail (java.lang.String newEmail ) {
	 	this.email = newEmail;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所在单位pk
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所在单位pk
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_zw的Getter方法.属性名：职务pk
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_zw () {
		return pk_zw;
	}   
	/**
	 * 属性pk_zw的Setter方法.属性名：职务pk
	 * 创建日期:
	 * @param newPk_zw java.lang.String
	 */
	public void setPk_zw (java.lang.String newPk_zw ) {
	 	this.pk_zw = newPk_zw;
	} 	  
	/**
	 * 属性pk_zc的Getter方法.属性名：职称pk
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_zc () {
		return pk_zc;
	}   
	/**
	 * 属性pk_zc的Setter方法.属性名：职称pk
	 * 创建日期:
	 * @param newPk_zc java.lang.String
	 */
	public void setPk_zc (java.lang.String newPk_zc ) {
	 	this.pk_zc = newPk_zc;
	} 	  
	/**
	 * 属性pk_dept的Getter方法.属性名：部门PK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dept () {
		return pk_dept;
	}   
	/**
	 * 属性pk_dept的Setter方法.属性名：部门PK
	 * 创建日期:
	 * @param newPk_dept java.lang.String
	 */
	public void setPk_dept (java.lang.String newPk_dept ) {
	 	this.pk_dept = newPk_dept;
	} 	  
	/**
	 * 属性deptname的Getter方法.属性名：部门
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDeptname () {
		return deptname;
	}   
	/**
	 * 属性deptname的Setter方法.属性名：部门
	 * 创建日期:
	 * @param newDeptname java.lang.String
	 */
	public void setDeptname (java.lang.String newDeptname ) {
	 	this.deptname = newDeptname;
	} 	  
	/**
	 * 属性enablestate的Getter方法.属性名：启用状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getEnablestate () {
		return enablestate;
	}   
	/**
	 * 属性enablestate的Setter方法.属性名：启用状态
	 * 创建日期:
	 * @param newEnablestate java.lang.String
	 */
	public void setEnablestate (java.lang.String newEnablestate ) {
	 	this.enablestate = newEnablestate;
	} 	  
	/**
	 * 属性user_type的Getter方法.属性名：用户类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUser_type () {
		return user_type;
	}   
	/**
	 * 属性user_type的Setter方法.属性名：用户类型
	 * 创建日期:
	 * @param newUser_type java.lang.String
	 */
	public void setUser_type (java.lang.String newUser_type ) {
	 	this.user_type = newUser_type;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "cuserid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "v_userpsn";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "v_userpsn";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public V_userpsnVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapjj.userpsn.V_userpsnVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


