/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pt.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class LandVO extends SuperVO {
	private java.lang.String pk_land;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String billmaker;
	private nc.vo.pub.lang.UFDateTime billmakedate;
	private java.lang.String billno;
	private java.lang.String approver;
	private nc.vo.pub.lang.UFDateTime approvedate;
	private java.lang.String formstate;
	private java.lang.String formtitle;
	private java.lang.String approvememo;
	private java.lang.String approvestatus;
	private java.lang.String pk_firmtree;
	private java.lang.String vname;
	private java.lang.String vcode;
	private java.lang.String pk_czfirmtree;
	private java.lang.String pk_czorg;
	private java.lang.String czname;
	private java.lang.String vregistry;
	private nc.vo.pub.lang.UFDate cjoindate;
	private nc.vo.pub.lang.UFDouble dregcapital;
	private java.lang.String pk_firmtype;
	private java.lang.String pk_agency;
	private java.lang.String cbtransferflag;
	private java.lang.Integer ibinpost;
	private java.lang.String ccity;
	private java.lang.String vfname;
	private java.lang.String vposition;
	private nc.vo.pub.lang.UFDouble darea;
	private java.lang.String vlevel;
	private java.lang.String inature;
	private java.lang.String iuse;
	private java.lang.String cmortgageflag;
	private java.lang.String ccertificateflag;
	private nc.vo.pub.lang.UFDouble dmarketvalue;
	private nc.vo.pub.lang.UFDouble dwtransprice;
	private nc.vo.pub.lang.UFDate cwctdate;
	private nc.vo.pub.lang.UFDouble dincreaseprice;
	private nc.vo.pub.lang.UFDouble dtransferprice;
	private nc.vo.pub.lang.UFDouble dsellprice;
	private nc.vo.pub.lang.UFDate cincreasedate;
	private java.lang.String vacceptno;
	private java.lang.String vreplace1;
	private nc.vo.pub.lang.UFDouble vbook1;
	private nc.vo.pub.lang.UFDouble vassess1;
	private java.lang.String vreplace2;
	private nc.vo.pub.lang.UFDouble vbook2;
	private nc.vo.pub.lang.UFDouble vassess2;
	private java.lang.String vpricediff;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private nc.vo.pub.lang.UFDouble def11;
	private nc.vo.pub.lang.UFDouble def12;
	private nc.vo.pub.lang.UFDouble def13;
	private nc.vo.pub.lang.UFDouble def14;
	private nc.vo.pub.lang.UFDouble def15;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_LAND = "pk_land";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLMAKEDATE = "billmakedate";
	public static final String BILLNO = "billno";
	public static final String APPROVER = "approver";
	public static final String APPROVEDATE = "approvedate";
	public static final String FORMSTATE = "formstate";
	public static final String FORMTITLE = "formtitle";
	public static final String APPROVEMEMO = "approvememo";
	public static final String APPROVESTATUS = "approvestatus";
	public static final String PK_FIRMTREE = "pk_firmtree";
	public static final String VNAME = "vname";
	public static final String VCODE = "vcode";
	public static final String PK_CZFIRMTREE = "pk_czfirmtree";
	public static final String PK_CZORG = "pk_czorg";
	public static final String CZNAME = "czname";
	public static final String VREGISTRY = "vregistry";
	public static final String CJOINDATE = "cjoindate";
	public static final String DREGCAPITAL = "dregcapital";
	public static final String PK_FIRMTYPE = "pk_firmtype";
	public static final String PK_AGENCY = "pk_agency";
	public static final String CBTRANSFERFLAG = "cbtransferflag";
	public static final String IBINPOST = "ibinpost";
	public static final String CCITY = "ccity";
	public static final String VFNAME = "vfname";
	public static final String VPOSITION = "vposition";
	public static final String DAREA = "darea";
	public static final String VLEVEL = "vlevel";
	public static final String INATURE = "inature";
	public static final String IUSE = "iuse";
	public static final String CMORTGAGEFLAG = "cmortgageflag";
	public static final String CCERTIFICATEFLAG = "ccertificateflag";
	public static final String DMARKETVALUE = "dmarketvalue";
	public static final String DWTRANSPRICE = "dwtransprice";
	public static final String CWCTDATE = "cwctdate";
	public static final String DINCREASEPRICE = "dincreaseprice";
	public static final String DTRANSFERPRICE = "dtransferprice";
	public static final String DSELLPRICE = "dsellprice";
	public static final String CINCREASEDATE = "cincreasedate";
	public static final String VACCEPTNO = "vacceptno";
	public static final String VREPLACE1 = "vreplace1";
	public static final String VBOOK1 = "vbook1";
	public static final String VASSESS1 = "vassess1";
	public static final String VREPLACE2 = "vreplace2";
	public static final String VBOOK2 = "vbook2";
	public static final String VASSESS2 = "vassess2";
	public static final String VPRICEDIFF = "vpricediff";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEF11 = "def11";
	public static final String DEF12 = "def12";
	public static final String DEF13 = "def13";
	public static final String DEF14 = "def14";
	public static final String DEF15 = "def15";
			
	/**
	 * 属性pk_land的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_land () {
		return pk_land;
	}   
	/**
	 * 属性pk_land的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_land java.lang.String
	 */
	public void setPk_land (java.lang.String newPk_land ) {
	 	this.pk_land = newPk_land;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性billmaker的Getter方法.属性名：制单人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return billmaker;
	}   
	/**
	 * 属性billmaker的Setter方法.属性名：制单人
	 * 创建日期:
	 * @param newBillmaker java.lang.String
	 */
	public void setBillmaker (java.lang.String newBillmaker ) {
	 	this.billmaker = newBillmaker;
	} 	  
	/**
	 * 属性billmakedate的Getter方法.属性名：制单日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getBillmakedate () {
		return billmakedate;
	}   
	/**
	 * 属性billmakedate的Setter方法.属性名：制单日期
	 * 创建日期:
	 * @param newBillmakedate nc.vo.pub.lang.UFDateTime
	 */
	public void setBillmakedate (nc.vo.pub.lang.UFDateTime newBillmakedate ) {
	 	this.billmakedate = newBillmakedate;
	} 	  
	/**
	 * 属性billno的Getter方法.属性名：单据号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillno () {
		return billno;
	}   
	/**
	 * 属性billno的Setter方法.属性名：单据号
	 * 创建日期:
	 * @param newBillno java.lang.String
	 */
	public void setBillno (java.lang.String newBillno ) {
	 	this.billno = newBillno;
	} 	  
	/**
	 * 属性approver的Getter方法.属性名：审批人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprover () {
		return approver;
	}   
	/**
	 * 属性approver的Setter方法.属性名：审批人
	 * 创建日期:
	 * @param newApprover java.lang.String
	 */
	public void setApprover (java.lang.String newApprover ) {
	 	this.approver = newApprover;
	} 	  
	/**
	 * 属性approvedate的Getter方法.属性名：审批时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getApprovedate () {
		return approvedate;
	}   
	/**
	 * 属性approvedate的Setter方法.属性名：审批时间
	 * 创建日期:
	 * @param newApprovedate nc.vo.pub.lang.UFDateTime
	 */
	public void setApprovedate (nc.vo.pub.lang.UFDateTime newApprovedate ) {
	 	this.approvedate = newApprovedate;
	} 	  
	/**
	 * 属性formstate的Getter方法.属性名：单据状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormstate () {
		return formstate;
	}   
	/**
	 * 属性formstate的Setter方法.属性名：单据状态
	 * 创建日期:
	 * @param newFormstate java.lang.String
	 */
	public void setFormstate (java.lang.String newFormstate ) {
	 	this.formstate = newFormstate;
	} 	  
	/**
	 * 属性formtitle的Getter方法.属性名：单据标题
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormtitle () {
		return formtitle;
	}   
	/**
	 * 属性formtitle的Setter方法.属性名：单据标题
	 * 创建日期:
	 * @param newFormtitle java.lang.String
	 */
	public void setFormtitle (java.lang.String newFormtitle ) {
	 	this.formtitle = newFormtitle;
	} 	  
	/**
	 * 属性approvememo的Getter方法.属性名：审核说明
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprovememo () {
		return approvememo;
	}   
	/**
	 * 属性approvememo的Setter方法.属性名：审核说明
	 * 创建日期:
	 * @param newApprovememo java.lang.String
	 */
	public void setApprovememo (java.lang.String newApprovememo ) {
	 	this.approvememo = newApprovememo;
	} 	  
	/**
	 * 属性approvestatus的Getter方法.属性名：审批状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprovestatus () {
		return approvestatus;
	}   
	/**
	 * 属性approvestatus的Setter方法.属性名：审批状态
	 * 创建日期:
	 * @param newApprovestatus java.lang.String
	 */
	public void setApprovestatus (java.lang.String newApprovestatus ) {
	 	this.approvestatus = newApprovestatus;
	} 	  
	/**
	 * 属性pk_firmtree的Getter方法.属性名：土地占有企业名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_firmtree () {
		return pk_firmtree;
	}   
	/**
	 * 属性pk_firmtree的Setter方法.属性名：土地占有企业名称
	 * 创建日期:
	 * @param newPk_firmtree java.lang.String
	 */
	public void setPk_firmtree (java.lang.String newPk_firmtree ) {
	 	this.pk_firmtree = newPk_firmtree;
	} 	  
	/**
	 * 属性vname的Getter方法.属性名：土地占有企业
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVname () {
		return vname;
	}   
	/**
	 * 属性vname的Setter方法.属性名：土地占有企业
	 * 创建日期:
	 * @param newVname java.lang.String
	 */
	public void setVname (java.lang.String newVname ) {
	 	this.vname = newVname;
	} 	  
	/**
	 * 属性vcode的Getter方法.属性名：组织机构代码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcode () {
		return vcode;
	}   
	/**
	 * 属性vcode的Setter方法.属性名：组织机构代码
	 * 创建日期:
	 * @param newVcode java.lang.String
	 */
	public void setVcode (java.lang.String newVcode ) {
	 	this.vcode = newVcode;
	} 	  
	/**
	 * 属性pk_czfirmtree的Getter方法.属性名：所出资企业名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_czfirmtree () {
		return pk_czfirmtree;
	}   
	/**
	 * 属性pk_czfirmtree的Setter方法.属性名：所出资企业名称
	 * 创建日期:
	 * @param newPk_czfirmtree java.lang.String
	 */
	public void setPk_czfirmtree (java.lang.String newPk_czfirmtree ) {
	 	this.pk_czfirmtree = newPk_czfirmtree;
	} 	  
	/**
	 * 属性pk_czorg的Getter方法.属性名：所出资企业名
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_czorg () {
		return pk_czorg;
	}   
	/**
	 * 属性pk_czorg的Setter方法.属性名：所出资企业名
	 * 创建日期:
	 * @param newPk_czorg java.lang.String
	 */
	public void setPk_czorg (java.lang.String newPk_czorg ) {
	 	this.pk_czorg = newPk_czorg;
	} 	  
	/**
	 * 属性czname的Getter方法.属性名：所出资企业
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCzname () {
		return czname;
	}   
	/**
	 * 属性czname的Setter方法.属性名：所出资企业
	 * 创建日期:
	 * @param newCzname java.lang.String
	 */
	public void setCzname (java.lang.String newCzname ) {
	 	this.czname = newCzname;
	} 	  
	/**
	 * 属性vregistry的Getter方法.属性名：注册地（住所）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVregistry () {
		return vregistry;
	}   
	/**
	 * 属性vregistry的Setter方法.属性名：注册地（住所）
	 * 创建日期:
	 * @param newVregistry java.lang.String
	 */
	public void setVregistry (java.lang.String newVregistry ) {
	 	this.vregistry = newVregistry;
	} 	  
	/**
	 * 属性cjoindate的Getter方法.属性名：成立时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCjoindate () {
		return cjoindate;
	}   
	/**
	 * 属性cjoindate的Setter方法.属性名：成立时间
	 * 创建日期:
	 * @param newCjoindate nc.vo.pub.lang.UFDate
	 */
	public void setCjoindate (nc.vo.pub.lang.UFDate newCjoindate ) {
	 	this.cjoindate = newCjoindate;
	} 	  
	/**
	 * 属性dregcapital的Getter方法.属性名：注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDregcapital () {
		return dregcapital;
	}   
	/**
	 * 属性dregcapital的Setter方法.属性名：注册资本（万元）
	 * 创建日期:
	 * @param newDregcapital nc.vo.pub.lang.UFDouble
	 */
	public void setDregcapital (nc.vo.pub.lang.UFDouble newDregcapital ) {
	 	this.dregcapital = newDregcapital;
	} 	  
	/**
	 * 属性pk_firmtype的Getter方法.属性名：企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_firmtype () {
		return pk_firmtype;
	}   
	/**
	 * 属性pk_firmtype的Setter方法.属性名：企业类别
	 * 创建日期:
	 * @param newPk_firmtype java.lang.String
	 */
	public void setPk_firmtype (java.lang.String newPk_firmtype ) {
	 	this.pk_firmtype = newPk_firmtype;
	} 	  
	/**
	 * 属性pk_agency的Getter方法.属性名：国资监管机构
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_agency () {
		return pk_agency;
	}   
	/**
	 * 属性pk_agency的Setter方法.属性名：国资监管机构
	 * 创建日期:
	 * @param newPk_agency java.lang.String
	 */
	public void setPk_agency (java.lang.String newPk_agency ) {
	 	this.pk_agency = newPk_agency;
	} 	  
	/**
	 * 属性cbtransferflag的Getter方法.属性名：是否含有国有划拨土地
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCbtransferflag () {
		return cbtransferflag;
	}   
	/**
	 * 属性cbtransferflag的Setter方法.属性名：是否含有国有划拨土地
	 * 创建日期:
	 * @param newCbtransferflag java.lang.String
	 */
	public void setCbtransferflag (java.lang.String newCbtransferflag ) {
	 	this.cbtransferflag = newCbtransferflag;
	} 	  
	/**
	 * 属性ibinpost的Getter方法.属性名：职工人数
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIbinpost () {
		return ibinpost;
	}   
	/**
	 * 属性ibinpost的Setter方法.属性名：职工人数
	 * 创建日期:
	 * @param newIbinpost java.lang.Integer
	 */
	public void setIbinpost (java.lang.Integer newIbinpost ) {
	 	this.ibinpost = newIbinpost;
	} 	  
	/**
	 * 属性ccity的Getter方法.属性名：所在城市
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCcity () {
		return ccity;
	}   
	/**
	 * 属性ccity的Setter方法.属性名：所在城市
	 * 创建日期:
	 * @param newCcity java.lang.String
	 */
	public void setCcity (java.lang.String newCcity ) {
	 	this.ccity = newCcity;
	} 	  
	/**
	 * 属性vfname的Getter方法.属性名：宗地名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVfname () {
		return vfname;
	}   
	/**
	 * 属性vfname的Setter方法.属性名：宗地名称
	 * 创建日期:
	 * @param newVfname java.lang.String
	 */
	public void setVfname (java.lang.String newVfname ) {
	 	this.vfname = newVfname;
	} 	  
	/**
	 * 属性vposition的Getter方法.属性名：宗地位置
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVposition () {
		return vposition;
	}   
	/**
	 * 属性vposition的Setter方法.属性名：宗地位置
	 * 创建日期:
	 * @param newVposition java.lang.String
	 */
	public void setVposition (java.lang.String newVposition ) {
	 	this.vposition = newVposition;
	} 	  
	/**
	 * 属性darea的Getter方法.属性名：面积
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDarea () {
		return darea;
	}   
	/**
	 * 属性darea的Setter方法.属性名：面积
	 * 创建日期:
	 * @param newDarea nc.vo.pub.lang.UFDouble
	 */
	public void setDarea (nc.vo.pub.lang.UFDouble newDarea ) {
	 	this.darea = newDarea;
	} 	  
	/**
	 * 属性vlevel的Getter方法.属性名：土地级别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVlevel () {
		return vlevel;
	}   
	/**
	 * 属性vlevel的Setter方法.属性名：土地级别
	 * 创建日期:
	 * @param newVlevel java.lang.String
	 */
	public void setVlevel (java.lang.String newVlevel ) {
	 	this.vlevel = newVlevel;
	} 	  
	/**
	 * 属性inature的Getter方法.属性名：性质
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getInature () {
		return inature;
	}   
	/**
	 * 属性inature的Setter方法.属性名：性质
	 * 创建日期:
	 * @param newInature java.lang.String
	 */
	public void setInature (java.lang.String newInature ) {
	 	this.inature = newInature;
	} 	  
	/**
	 * 属性iuse的Getter方法.属性名：用途
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIuse () {
		return iuse;
	}   
	/**
	 * 属性iuse的Setter方法.属性名：用途
	 * 创建日期:
	 * @param newIuse java.lang.String
	 */
	public void setIuse (java.lang.String newIuse ) {
	 	this.iuse = newIuse;
	} 	  
	/**
	 * 属性cmortgageflag的Getter方法.属性名：是否抵押
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCmortgageflag () {
		return cmortgageflag;
	}   
	/**
	 * 属性cmortgageflag的Setter方法.属性名：是否抵押
	 * 创建日期:
	 * @param newCmortgageflag java.lang.String
	 */
	public void setCmortgageflag (java.lang.String newCmortgageflag ) {
	 	this.cmortgageflag = newCmortgageflag;
	} 	  
	/**
	 * 属性ccertificateflag的Getter方法.属性名：是否办证
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCcertificateflag () {
		return ccertificateflag;
	}   
	/**
	 * 属性ccertificateflag的Setter方法.属性名：是否办证
	 * 创建日期:
	 * @param newCcertificateflag java.lang.String
	 */
	public void setCcertificateflag (java.lang.String newCcertificateflag ) {
	 	this.ccertificateflag = newCcertificateflag;
	} 	  
	/**
	 * 属性dmarketvalue的Getter方法.属性名：评估价格
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDmarketvalue () {
		return dmarketvalue;
	}   
	/**
	 * 属性dmarketvalue的Setter方法.属性名：评估价格
	 * 创建日期:
	 * @param newDmarketvalue nc.vo.pub.lang.UFDouble
	 */
	public void setDmarketvalue (nc.vo.pub.lang.UFDouble newDmarketvalue ) {
	 	this.dmarketvalue = newDmarketvalue;
	} 	  
	/**
	 * 属性dwtransprice的Getter方法.属性名：交易价格
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDwtransprice () {
		return dwtransprice;
	}   
	/**
	 * 属性dwtransprice的Setter方法.属性名：交易价格
	 * 创建日期:
	 * @param newDwtransprice nc.vo.pub.lang.UFDouble
	 */
	public void setDwtransprice (nc.vo.pub.lang.UFDouble newDwtransprice ) {
	 	this.dwtransprice = newDwtransprice;
	} 	  
	/**
	 * 属性cwctdate的Getter方法.属性名：交易时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCwctdate () {
		return cwctdate;
	}   
	/**
	 * 属性cwctdate的Setter方法.属性名：交易时间
	 * 创建日期:
	 * @param newCwctdate nc.vo.pub.lang.UFDate
	 */
	public void setCwctdate (nc.vo.pub.lang.UFDate newCwctdate ) {
	 	this.cwctdate = newCwctdate;
	} 	  
	/**
	 * 属性dincreaseprice的Getter方法.属性名：转增金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDincreaseprice () {
		return dincreaseprice;
	}   
	/**
	 * 属性dincreaseprice的Setter方法.属性名：转增金额
	 * 创建日期:
	 * @param newDincreaseprice nc.vo.pub.lang.UFDouble
	 */
	public void setDincreaseprice (nc.vo.pub.lang.UFDouble newDincreaseprice ) {
	 	this.dincreaseprice = newDincreaseprice;
	} 	  
	/**
	 * 属性dtransferprice的Getter方法.属性名：划拨土地性质评估价格
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDtransferprice () {
		return dtransferprice;
	}   
	/**
	 * 属性dtransferprice的Setter方法.属性名：划拨土地性质评估价格
	 * 创建日期:
	 * @param newDtransferprice nc.vo.pub.lang.UFDouble
	 */
	public void setDtransferprice (nc.vo.pub.lang.UFDouble newDtransferprice ) {
	 	this.dtransferprice = newDtransferprice;
	} 	  
	/**
	 * 属性dsellprice的Getter方法.属性名：出让土地性质评估价格
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDsellprice () {
		return dsellprice;
	}   
	/**
	 * 属性dsellprice的Setter方法.属性名：出让土地性质评估价格
	 * 创建日期:
	 * @param newDsellprice nc.vo.pub.lang.UFDouble
	 */
	public void setDsellprice (nc.vo.pub.lang.UFDouble newDsellprice ) {
	 	this.dsellprice = newDsellprice;
	} 	  
	/**
	 * 属性cincreasedate的Getter方法.属性名：转增时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCincreasedate () {
		return cincreasedate;
	}   
	/**
	 * 属性cincreasedate的Setter方法.属性名：转增时间
	 * 创建日期:
	 * @param newCincreasedate nc.vo.pub.lang.UFDate
	 */
	public void setCincreasedate (nc.vo.pub.lang.UFDate newCincreasedate ) {
	 	this.cincreasedate = newCincreasedate;
	} 	  
	/**
	 * 属性vacceptno的Getter方法.属性名：批准文号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVacceptno () {
		return vacceptno;
	}   
	/**
	 * 属性vacceptno的Setter方法.属性名：批准文号
	 * 创建日期:
	 * @param newVacceptno java.lang.String
	 */
	public void setVacceptno (java.lang.String newVacceptno ) {
	 	this.vacceptno = newVacceptno;
	} 	  
	/**
	 * 属性vreplace1的Getter方法.属性名：置换方1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVreplace1 () {
		return vreplace1;
	}   
	/**
	 * 属性vreplace1的Setter方法.属性名：置换方1
	 * 创建日期:
	 * @param newVreplace1 java.lang.String
	 */
	public void setVreplace1 (java.lang.String newVreplace1 ) {
	 	this.vreplace1 = newVreplace1;
	} 	  
	/**
	 * 属性vbook1的Getter方法.属性名：标的1账面值
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVbook1 () {
		return vbook1;
	}   
	/**
	 * 属性vbook1的Setter方法.属性名：标的1账面值
	 * 创建日期:
	 * @param newVbook1 nc.vo.pub.lang.UFDouble
	 */
	public void setVbook1 (nc.vo.pub.lang.UFDouble newVbook1 ) {
	 	this.vbook1 = newVbook1;
	} 	  
	/**
	 * 属性vassess1的Getter方法.属性名：标的1评估值
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVassess1 () {
		return vassess1;
	}   
	/**
	 * 属性vassess1的Setter方法.属性名：标的1评估值
	 * 创建日期:
	 * @param newVassess1 nc.vo.pub.lang.UFDouble
	 */
	public void setVassess1 (nc.vo.pub.lang.UFDouble newVassess1 ) {
	 	this.vassess1 = newVassess1;
	} 	  
	/**
	 * 属性vreplace2的Getter方法.属性名：置换方2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVreplace2 () {
		return vreplace2;
	}   
	/**
	 * 属性vreplace2的Setter方法.属性名：置换方2
	 * 创建日期:
	 * @param newVreplace2 java.lang.String
	 */
	public void setVreplace2 (java.lang.String newVreplace2 ) {
	 	this.vreplace2 = newVreplace2;
	} 	  
	/**
	 * 属性vbook2的Getter方法.属性名：标的2账面值
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVbook2 () {
		return vbook2;
	}   
	/**
	 * 属性vbook2的Setter方法.属性名：标的2账面值
	 * 创建日期:
	 * @param newVbook2 nc.vo.pub.lang.UFDouble
	 */
	public void setVbook2 (nc.vo.pub.lang.UFDouble newVbook2 ) {
	 	this.vbook2 = newVbook2;
	} 	  
	/**
	 * 属性vassess2的Getter方法.属性名：标的2评估值
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVassess2 () {
		return vassess2;
	}   
	/**
	 * 属性vassess2的Setter方法.属性名：标的2评估值
	 * 创建日期:
	 * @param newVassess2 nc.vo.pub.lang.UFDouble
	 */
	public void setVassess2 (nc.vo.pub.lang.UFDouble newVassess2 ) {
	 	this.vassess2 = newVassess2;
	} 	  
	/**
	 * 属性vpricediff的Getter方法.属性名：现金补差价情况
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVpricediff () {
		return vpricediff;
	}   
	/**
	 * 属性vpricediff的Setter方法.属性名：现金补差价情况
	 * 创建日期:
	 * @param newVpricediff java.lang.String
	 */
	public void setVpricediff (java.lang.String newVpricediff ) {
	 	this.vpricediff = newVpricediff;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：自定义项1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：自定义项1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：自定义项2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：自定义项2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：自定义项3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：自定义项3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：自定义项4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：自定义项4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：自定义项5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：自定义项5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：自定义项6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：自定义项6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：自定义项7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：自定义项7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：自定义项8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：自定义项8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：自定义项9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：自定义项9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：自定义项10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：自定义项10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性def11的Getter方法.属性名：自定义项11
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDef11 () {
		return def11;
	}   
	/**
	 * 属性def11的Setter方法.属性名：自定义项11
	 * 创建日期:
	 * @param newDef11 nc.vo.pub.lang.UFDouble
	 */
	public void setDef11 (nc.vo.pub.lang.UFDouble newDef11 ) {
	 	this.def11 = newDef11;
	} 	  
	/**
	 * 属性def12的Getter方法.属性名：自定义项12
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDef12 () {
		return def12;
	}   
	/**
	 * 属性def12的Setter方法.属性名：自定义项12
	 * 创建日期:
	 * @param newDef12 nc.vo.pub.lang.UFDouble
	 */
	public void setDef12 (nc.vo.pub.lang.UFDouble newDef12 ) {
	 	this.def12 = newDef12;
	} 	  
	/**
	 * 属性def13的Getter方法.属性名：自定义项13
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDef13 () {
		return def13;
	}   
	/**
	 * 属性def13的Setter方法.属性名：自定义项13
	 * 创建日期:
	 * @param newDef13 nc.vo.pub.lang.UFDouble
	 */
	public void setDef13 (nc.vo.pub.lang.UFDouble newDef13 ) {
	 	this.def13 = newDef13;
	} 	  
	/**
	 * 属性def14的Getter方法.属性名：自定义项14
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDef14 () {
		return def14;
	}   
	/**
	 * 属性def14的Setter方法.属性名：自定义项14
	 * 创建日期:
	 * @param newDef14 nc.vo.pub.lang.UFDouble
	 */
	public void setDef14 (nc.vo.pub.lang.UFDouble newDef14 ) {
	 	this.def14 = newDef14;
	} 	  
	/**
	 * 属性def15的Getter方法.属性名：自定义项15
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDef15 () {
		return def15;
	}   
	/**
	 * 属性def15的Setter方法.属性名：自定义项15
	 * 创建日期:
	 * @param newDef15 nc.vo.pub.lang.UFDouble
	 */
	public void setDef15 (nc.vo.pub.lang.UFDouble newDef15 ) {
	 	this.def15 = newDef15;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_land";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scappt_land";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scappt_land";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public LandVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pt.vos.LandVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


