/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pt.vos;
	
import java.io.Serializable;

import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapptTransferHVO extends SuperVO implements Serializable{
	private java.lang.String pk_transfer_h;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String billmaker;
	private nc.vo.pub.lang.UFDateTime billmakedate;
	private java.lang.String billno;
	private java.lang.String approver;
	private nc.vo.pub.lang.UFDateTime approvedate;
	private java.lang.String formstate;
	private java.lang.String formtitle;
	private java.lang.String vrequestno;
	private java.lang.String cprocesstype;
	private java.lang.String cchangetype;
	private java.lang.String ctradetype;
	private java.lang.String cgreattype;
	private java.lang.String vlevel;
	private java.lang.String pk_sgroup;
	private java.lang.String capplicant;
	private nc.vo.pub.lang.UFDate capplicantdate;
	private java.lang.String pk_borg;
	private java.lang.String pk_reportno;
	private java.lang.String vbunit;
	private java.lang.String pk_bcurrency;
	private nc.vo.pub.lang.UFDouble dbpercent;
	private java.lang.String vbaddress;
	private nc.vo.pub.lang.UFDate cbsetupdate;
	private nc.vo.pub.lang.UFDouble dbcapital;
	private java.lang.String vbfactype;
	private java.lang.Integer ibinpost;
	private java.lang.Integer ibretired;
	private nc.vo.pub.lang.UFBoolean cbtransferflag;
	private nc.vo.pub.lang.UFDate cbreportdate;
	private nc.vo.pub.lang.UFDouble dbassets;
	private nc.vo.pub.lang.UFDouble dbdebt;
	private nc.vo.pub.lang.UFDouble dbnetassets;
	private nc.vo.pub.lang.UFDouble dbincome;
	private nc.vo.pub.lang.UFDouble dbnetprofit;
	private java.lang.String vbinternal;
	private nc.vo.pub.lang.UFBoolean cbgiveup;
	private java.lang.String vbintent;
	private java.lang.String vbother;
	private nc.vo.pub.lang.UFDouble dbcarrying;
	private java.lang.String vbdetail;
	private java.lang.String vrname;
	private java.lang.String pk_rorg;
	private nc.vo.pub.lang.UFDouble drcapital;
	private java.lang.String vrfactype;
	private java.lang.String pk_rgroup;
	private java.lang.String pk_passess;
	private java.lang.String vpcode;
	private java.lang.String vporgname;
	private java.lang.String vpnumber;
	private nc.vo.pub.lang.UFDate vpdate;
	private nc.vo.pub.lang.UFDate vpbasedate;
	private java.lang.String vpbasename;
	private java.lang.String vplawyer;
	private nc.vo.pub.lang.UFDouble dpcarrying;
	private java.lang.String vwname;
	private java.lang.String vwunit;
	private java.lang.String pk_wcurrency;
	private java.lang.String vacceptno;
	private java.lang.String vwperiod;
	private nc.vo.pub.lang.UFDouble dwprice;
	private nc.vo.pub.lang.UFBoolean cwtransflag;
	private java.lang.String vwtranstype;
	private nc.vo.pub.lang.UFDouble dwtransprice;
	private java.lang.String vwassignname;
	private java.lang.String vwassigtype;
	private nc.vo.pub.lang.UFDate cwctdate;
	private java.lang.String vwpayment;
	private nc.vo.pub.lang.UFDouble dwdownpayment;
	private nc.vo.pub.lang.UFDouble dwdownpercent;
	private nc.vo.pub.lang.UFDate cwbalancedate;
	private nc.vo.pub.lang.UFDate cwforensicdate;
	private java.lang.String vsname;
	private java.lang.String pk_sorg;
	private java.lang.String vsunit;
	private java.lang.String pk_scurrency;
	private java.lang.String vagency;
	private nc.vo.pub.lang.UFDouble dscapital;
	private java.lang.String vsfactype;
	private java.lang.String pk_slgroup;
	private java.lang.String vjunit;
	private java.lang.String pk_jcurrency;
	private nc.vo.pub.lang.UFDouble djprice;
	private nc.vo.pub.lang.UFDate djdate;
	private java.lang.String vqunit;
	private java.lang.String pk_qcurrency;
	private java.lang.String vqstock;
	private java.lang.String cqpricedate;
	private java.lang.String attrname;
	private java.lang.String dqrealprice;
	private java.lang.String vqname;
	private java.lang.String vqlawyer;
	private java.lang.String vqaccount;
	private java.lang.Integer vqprinciple;
	private java.lang.String vqbaseassess;
	private nc.vo.pub.lang.UFDouble dqperprice;
	private java.lang.Integer iqmatype;
	private nc.vo.pub.lang.UFDouble dqprice;
	private java.lang.String pk_gorg;
	private java.lang.Integer dgpercent;
	private java.lang.String vgunit;
	private java.lang.String pk_gcurrency;
	private java.lang.String vgaddress;
	private nc.vo.pub.lang.UFDate cgsetupdate;
	private nc.vo.pub.lang.UFDouble dgcapital;
	private java.lang.String vgfactype;
	private nc.vo.pub.lang.UFDate cgreportdate;
	private nc.vo.pub.lang.UFDouble dgassets;
	private nc.vo.pub.lang.UFDouble dgdebt;
	private nc.vo.pub.lang.UFDouble dgnetassets;
	private nc.vo.pub.lang.UFDouble dgincome;
	private nc.vo.pub.lang.UFDouble dgnetprofit;
	private java.lang.String vcname;
	private java.lang.String vccode;
	private java.lang.String vcunit;
	private java.lang.String pk_ccurrency;
	private nc.vo.pub.lang.UFDouble dccapital;
	private java.lang.String vcfactype;
	private java.lang.String pk_cgroup;
	private java.lang.String vcinside;
	private java.lang.String vccorpname;
	private nc.vo.pub.lang.UFDate ccpolicydate;
	private nc.vo.pub.lang.UFDate ccapprovedate;
	private java.lang.String vcrecordno;
	private java.lang.String vcassessname;
	private java.lang.String vcassesstype;
	private java.lang.String vcfactyoe;
	private java.lang.String vcother;
	private java.lang.String  vcasstype;
	private java.lang.String cassetstype;
	private java.lang.String industry;
	private java.lang.String tramethod;
	private java.lang.String traarea;
	private java.lang.String traname;
	private nc.vo.pub.lang.UFBoolean isleadin;
	private java.lang.String ismerge;
	private java.lang.String vcsasstype;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private nc.vo.pub.lang.UFDouble listvalue;
	private java.lang.String isgzw;
	private java.lang.String leadintramodel;
	private java.lang.String pk_bfirmbase_h;
	private java.lang.String pk_rfirmbase_h;
	private java.lang.String pk_sfirmbase_h;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.scap.pt.vos.ScapptTransferTargetVO[] id_scappt_transfer_target;
	private nc.scap.pt.vos.ScapptTransferTransferorVO[] id_scappt_transfer_transferor;
	private nc.scap.pt.vos.ScapptTransferAssessVO[] id_scappt_transfer_assess;
	private nc.scap.pt.vos.ScapptTransferTransfereeVO[] id_scappt_transfer_transferee;
	private nc.scap.pt.vos.ScapptAttachVO[] id_scappt_attach;
	
	private nc.vo.pub.lang.UFDouble jzcpgz;
	
	private java.lang.String pgjgmc;
	private java.lang.String pgbgbm;
	private nc.vo.pub.lang.UFDate pgjzr;
	private java.lang.String pgjz;
	private java.lang.String pgbabm;
	private java.lang.String pgbadw;
	private nc.vo.pub.lang.UFDate pgbarq;
	


	public java.lang.String getPgjgmc() {
		return pgjgmc;
	}
	public void setPgjgmc(java.lang.String pgjgmc) {
		this.pgjgmc = pgjgmc;
	}
	public java.lang.String getPgbgbm() {
		return pgbgbm;
	}
	public void setPgbgbm(java.lang.String pgbgbm) {
		this.pgbgbm = pgbgbm;
	}
	public nc.vo.pub.lang.UFDate getPgjzr() {
		return pgjzr;
	}
	public void setPgjzr(nc.vo.pub.lang.UFDate pgjzr) {
		this.pgjzr = pgjzr;
	}
	public java.lang.String getPgjz() {
		return pgjz;
	}
	public void setPgjz(java.lang.String pgjz) {
		this.pgjz = pgjz;
	}
	public java.lang.String getPgbabm() {
		return pgbabm;
	}
	public void setPgbabm(java.lang.String pgbabm) {
		this.pgbabm = pgbabm;
	}
	public java.lang.String getPgbadw() {
		return pgbadw;
	}
	public void setPgbadw(java.lang.String pgbadw) {
		this.pgbadw = pgbadw;
	}
	public nc.vo.pub.lang.UFDate getPgbarq() {
		return pgbarq;
	}
	public void setPgbarq(nc.vo.pub.lang.UFDate pgbarq) {
		this.pgbarq = pgbarq;
	}
	public nc.vo.pub.lang.UFDouble getJzcpgz() {
		return jzcpgz;
	}
	public void setJzcpgz(nc.vo.pub.lang.UFDouble jzcpgz) {
		this.jzcpgz = jzcpgz;
	}

	private java.lang.String bdzcjgdm;
	public java.lang.String getBdzcjgdm() {
		return bdzcjgdm;
	}
	public void setBdzcjgdm(java.lang.String bdzcjgdm) {
		this.bdzcjgdm = bdzcjgdm;
	}
	public java.lang.String getZrfzcjgdm() {
		return zrfzcjgdm;
	}
	public void setZrfzcjgdm(java.lang.String zrfzcjgdm) {
		this.zrfzcjgdm = zrfzcjgdm;
	}
	public java.lang.String getSrfzcjgdm() {
		return srfzcjgdm;
	}
	public void setSrfzcjgdm(java.lang.String srfzcjgdm) {
		this.srfzcjgdm = srfzcjgdm;
	}
	public java.lang.String getBdgzjgjg() {
		return bdgzjgjg;
	}
	public void setBdgzjgjg(java.lang.String bdgzjgjg) {
		this.bdgzjgjg = bdgzjgjg;
	}
	public java.lang.String getZrfgzjgjg() {
		return zrfgzjgjg;
	}
	public void setZrfgzjgjg(java.lang.String zrfgzjgjg) {
		this.zrfgzjgjg = zrfgzjgjg;
	}
	public java.lang.String getSrfgzjgjg() {
		return srfgzjgjg;
	}
	public void setSrfgzjgjg(java.lang.String srfgzjgjg) {
		this.srfgzjgjg = srfgzjgjg;
	}
	public java.lang.String getZcpgdw() {
		return zcpgdw;
	}
	public void setZcpgdw(java.lang.String zcpgdw) {
		this.zcpgdw = zcpgdw;
	}
	public java.lang.String getZcpgbz() {
		return zcpgbz;
	}
	public void setZcpgbz(java.lang.String zcpgbz) {
		this.zcpgbz = zcpgbz;
	}
	public java.lang.String getZzxs() {
		return zzxs;
	}
	public void setZzxs(java.lang.String zzxs) {
		this.zzxs = zzxs;
	}
	public java.lang.String getBi_1() {
		return bi_1;
	}
	public void setBi_1(java.lang.String bi_1) {
		this.bi_1 = bi_1;
	}
	public java.lang.String getBi_2() {
		return bi_2;
	}
	public void setBi_2(java.lang.String bi_2) {
		this.bi_2 = bi_2;
	}

	private java.lang.String zrfzcjgdm;
	private java.lang.String srfzcjgdm;
	private java.lang.String bdgzjgjg;
	private java.lang.String zrfgzjgjg;
	private java.lang.String srfgzjgjg;
	private java.lang.String zcpgdw;
	private java.lang.String zcpgbz;
	private java.lang.String zzxs;
	private java.lang.String bi_1;
	private java.lang.String bi_2;

	public static String JZCPGZ = "jzcpgz";
	public static String BDFZCJGDM = "bdzcjgdm";
	public static String ZRFZCJGDM = "zrfzcjgdm";
	public static String SRFZCJGDM = "srfzcjgdm";
	public static String BDFGZJGJG = "bdgzjgjg";
	public static String ZRFGZJGJG = "zrfgzjgjg";
	public static String SRFGZJGJG = "srfgzjgjg";
	public static String ZCPGDW = "zcpgdw";
	public static String ZCPGBZ = "zcpgbz";
	public static String ZZXS = "zzxs";
	public static String BI_1 = "bi_1";
	public static String BI_2 = "bi_2";
	public static final String PK_TRANSFER_H = "pk_transfer_h";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLMAKEDATE = "billmakedate";
	public static final String BILLNO = "billno";
	public static final String APPROVER = "approver";
	public static final String APPROVEDATE = "approvedate";
	public static final String FORMSTATE = "formstate";
	public static final String FORMTITLE = "formtitle";
	public static final String VREQUESTNO = "vrequestno";
	public static final String CPROCESSTYPE = "cprocesstype";
	public static final String CCHANGETYPE = "cchangetype";
	public static final String CTRADETYPE = "ctradetype";
	public static final String CGREATTYPE = "cgreattype";
	public static final String VLEVEL = "vlevel";
	public static final String PK_SGROUP = "pk_sgroup";
	public static final String CAPPLICANT = "capplicant";
	public static final String CAPPLICANTDATE = "capplicantdate";
	public static final String PK_BORG = "pk_borg";
	public static final String PK_REPORTNO = "pk_reportno";
	public static final String VBUNIT = "vbunit";
	public static final String PK_BCURRENCY = "pk_bcurrency";
	public static final String DBPERCENT = "dbpercent";
	public static final String VBADDRESS = "vbaddress";
	public static final String CBSETUPDATE = "cbsetupdate";
	public static final String DBCAPITAL = "dbcapital";
	public static final String VBFACTYPE = "vbfactype";
	public static final String IBINPOST = "ibinpost";
	public static final String IBRETIRED = "ibretired";
	public static final String CBTRANSFERFLAG = "cbtransferflag";
	public static final String CBREPORTDATE = "cbreportdate";
	public static final String DBASSETS = "dbassets";
	public static final String DBDEBT = "dbdebt";
	public static final String DBNETASSETS = "dbnetassets";
	public static final String DBINCOME = "dbincome";
	public static final String DBNETPROFIT = "dbnetprofit";
	public static final String VBINTERNAL = "vbinternal";
	public static final String CBGIVEUP = "cbgiveup";
	public static final String VBINTENT = "vbintent";
	public static final String VBOTHER = "vbother";
	public static final String DBCARRYING = "dbcarrying";
	public static final String VBDETAIL = "vbdetail";
	public static final String VRNAME = "vrname";
	public static final String PK_RORG = "pk_rorg";
	public static final String DRCAPITAL = "drcapital";
	public static final String VRFACTYPE = "vrfactype";
	public static final String PK_RGROUP = "pk_rgroup";
	public static final String PK_PASSESS = "pk_passess";
	public static final String VPCODE = "vpcode";
	public static final String VPORGNAME = "vporgname";
	public static final String VPNUMBER = "vpnumber";
	public static final String VPDATE = "vpdate";
	public static final String VPBASEDATE = "vpbasedate";
	public static final String VPBASENAME = "vpbasename";
	public static final String VPLAWYER = "vplawyer";
	public static final String DPCARRYING = "dpcarrying";
	public static final String VWNAME = "vwname";
	public static final String VWUNIT = "vwunit";
	public static final String PK_WCURRENCY = "pk_wcurrency";
	public static final String VACCEPTNO = "vacceptno";
	public static final String VWPERIOD = "vwperiod";
	public static final String DWPRICE = "dwprice";
	public static final String CWTRANSFLAG = "cwtransflag";
	public static final String VWTRANSTYPE = "vwtranstype";
	public static final String DWTRANSPRICE = "dwtransprice";
	public static final String VWASSIGNNAME = "vwassignname";
	public static final String VWASSIGTYPE = "vwassigtype";
	public static final String CWCTDATE = "cwctdate";
	public static final String VWPAYMENT = "vwpayment";
	public static final String DWDOWNPAYMENT = "dwdownpayment";
	public static final String DWDOWNPERCENT = "dwdownpercent";
	public static final String CWBALANCEDATE = "cwbalancedate";
	public static final String CWFORENSICDATE = "cwforensicdate";
	public static final String VSNAME = "vsname";
	public static final String PK_SORG = "pk_sorg";
	public static final String VSUNIT = "vsunit";
	public static final String PK_SCURRENCY = "pk_scurrency";
	public static final String VAGENCY = "vagency";
	public static final String DSCAPITAL = "dscapital";
	public static final String VSFACTYPE = "vsfactype";
	public static final String PK_SLGROUP = "pk_slgroup";
	public static final String VJUNIT = "vjunit";
	public static final String PK_JCURRENCY = "pk_jcurrency";
	public static final String DJPRICE = "djprice";
	public static final String DJDATE = "djdate";
	public static final String VQUNIT = "vqunit";
	public static final String PK_QCURRENCY = "pk_qcurrency";
	public static final String VQSTOCK = "vqstock";
	public static final String CQPRICEDATE = "cqpricedate";
	public static final String ATTRNAME = "attrname";
	public static final String DQREALPRICE = "dqrealprice";
	public static final String VQNAME = "vqname";
	public static final String VQLAWYER = "vqlawyer";
	public static final String VQACCOUNT = "vqaccount";
	public static final String VQPRINCIPLE = "vqprinciple";
	public static final String VQBASEASSESS = "vqbaseassess";
	public static final String DQPERPRICE = "dqperprice";
	public static final String IQMATYPE = "iqmatype";
	public static final String DQPRICE = "dqprice";
	public static final String PK_GORG = "pk_gorg";
	public static final String DGPERCENT = "dgpercent";
	public static final String VGUNIT = "vgunit";
	public static final String PK_GCURRENCY = "pk_gcurrency";
	public static final String VGADDRESS = "vgaddress";
	public static final String CGSETUPDATE = "cgsetupdate";
	public static final String DGCAPITAL = "dgcapital";
	public static final String VGFACTYPE = "vgfactype";
	public static final String CGREPORTDATE = "cgreportdate";
	public static final String DGASSETS = "dgassets";
	public static final String DGDEBT = "dgdebt";
	public static final String DGNETASSETS = "dgnetassets";
	public static final String DGINCOME = "dgincome";
	public static final String DGNETPROFIT = "dgnetprofit";
	public static final String VCNAME = "vcname";
	public static final String VCCODE = "vccode";
	public static final String VCUNIT = "vcunit";
	public static final String PK_CCURRENCY = "pk_ccurrency";
	public static final String DCCAPITAL = "dccapital";
	public static final String VCFACTYPE = "vcfactype";
	public static final String PK_CGROUP = "pk_cgroup";
	public static final String VCINSIDE = "vcinside";
	public static final String VCCORPNAME = "vccorpname";
	public static final String CCPOLICYDATE = "ccpolicydate";
	public static final String CCAPPROVEDATE = "ccapprovedate";
	public static final String VCRECORDNO = "vcrecordno";
	public static final String VCASSESSNAME = "vcassessname";
	public static final String VCASSESSTYPE = "vcassesstype";
	public static final String VCFACTYOE = "vcfactyoe";
	public static final String VCOTHER = "vcother";
	public static final String VCASSTYPE = "vcasstype";
	public static final String CASSETSTYPE = "cassetstype";
	public static final String INDUSTRY = "industry";
	public static final String TRAMETHOD = "tramethod";
	public static final String TRAAREA = "traarea";
	public static final String TRANAME = "traname";
	public static final String ISLEADIN = "isleadin";
	public static final String ISMERGE = "ismerge";
	public static final String VCSASSTYPE = "vcsasstype";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String LISTVALUE = "listvalue";
	public static final String ISGZW = "isgzw";
	public static final String LEADINTRAMODEL = "leadintramodel";
	public static final String PK_BFIRMBASE_H = "pk_bfirmbase_h";
	public static final String PK_RFIRMBASE_H = "pk_rfirmbase_h";
	public static final String PK_SFIRMBASE_H = "pk_sfirmbase_h";
			
	/**
	 * 属性pk_transfer_h的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_transfer_h () {
		return pk_transfer_h;
	}   
	/**
	 * 属性pk_transfer_h的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_transfer_h java.lang.String
	 */
	public void setPk_transfer_h (java.lang.String newPk_transfer_h ) {
	 	this.pk_transfer_h = newPk_transfer_h;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织主键
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团主键
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性billmaker的Getter方法.属性名：制单人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return billmaker;
	}   
	/**
	 * 属性billmaker的Setter方法.属性名：制单人
	 * 创建日期:
	 * @param newBillmaker java.lang.String
	 */
	public void setBillmaker (java.lang.String newBillmaker ) {
	 	this.billmaker = newBillmaker;
	} 	  
	/**
	 * 属性billmakedate的Getter方法.属性名：制单日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getBillmakedate () {
		return billmakedate;
	}   
	/**
	 * 属性billmakedate的Setter方法.属性名：制单日期
	 * 创建日期:
	 * @param newBillmakedate nc.vo.pub.lang.UFDateTime
	 */
	public void setBillmakedate (nc.vo.pub.lang.UFDateTime newBillmakedate ) {
	 	this.billmakedate = newBillmakedate;
	} 	  
	/**
	 * 属性billno的Getter方法.属性名：单据号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillno () {
		return billno;
	}   
	/**
	 * 属性billno的Setter方法.属性名：单据号
	 * 创建日期:
	 * @param newBillno java.lang.String
	 */
	public void setBillno (java.lang.String newBillno ) {
	 	this.billno = newBillno;
	} 	  
	/**
	 * 属性approver的Getter方法.属性名：审批人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprover () {
		return approver;
	}   
	/**
	 * 属性approver的Setter方法.属性名：审批人
	 * 创建日期:
	 * @param newApprover java.lang.String
	 */
	public void setApprover (java.lang.String newApprover ) {
	 	this.approver = newApprover;
	} 	  
	/**
	 * 属性approvedate的Getter方法.属性名：审批时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getApprovedate () {
		return approvedate;
	}   
	/**
	 * 属性approvedate的Setter方法.属性名：审批时间
	 * 创建日期:
	 * @param newApprovedate nc.vo.pub.lang.UFDateTime
	 */
	public void setApprovedate (nc.vo.pub.lang.UFDateTime newApprovedate ) {
	 	this.approvedate = newApprovedate;
	} 	  
	/**
	 * 属性formstate的Getter方法.属性名：单据状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormstate () {
		return formstate;
	}   
	/**
	 * 属性formstate的Setter方法.属性名：单据状态
	 * 创建日期:
	 * @param newFormstate java.lang.String
	 */
	public void setFormstate (java.lang.String newFormstate ) {
	 	this.formstate = newFormstate;
	} 	  
	/**
	 * 属性formtitle的Getter方法.属性名：单据标题
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormtitle () {
		return formtitle;
	}   
	/**
	 * 属性formtitle的Setter方法.属性名：单据标题
	 * 创建日期:
	 * @param newFormtitle java.lang.String
	 */
	public void setFormtitle (java.lang.String newFormtitle ) {
	 	this.formtitle = newFormtitle;
	} 	  
	/**
	 * 属性vrequestno的Getter方法.属性名：申请单号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVrequestno () {
		return vrequestno;
	}   
	/**
	 * 属性vrequestno的Setter方法.属性名：申请单号
	 * 创建日期:
	 * @param newVrequestno java.lang.String
	 */
	public void setVrequestno (java.lang.String newVrequestno ) {
	 	this.vrequestno = newVrequestno;
	} 	  
	/**
	 * 属性cprocesstype的Getter方法.属性名：审批流程类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCprocesstype () {
		return cprocesstype;
	}   
	/**
	 * 属性cprocesstype的Setter方法.属性名：审批流程类型
	 * 创建日期:
	 * @param newCprocesstype java.lang.String
	 */
	public void setCprocesstype (java.lang.String newCprocesstype ) {
	 	this.cprocesstype = newCprocesstype;
	} 	  
	/**
	 * 属性cchangetype的Getter方法.属性名：产权变动类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCchangetype () {
		return cchangetype;
	}   
	/**
	 * 属性cchangetype的Setter方法.属性名：产权变动类型
	 * 创建日期:
	 * @param newCchangetype java.lang.String
	 */
	public void setCchangetype (java.lang.String newCchangetype ) {
	 	this.cchangetype = newCchangetype;
	} 	  
	/**
	 * 属性ctradetype的Getter方法.属性名：产权交易方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCtradetype () {
		return ctradetype;
	}   
	/**
	 * 属性ctradetype的Setter方法.属性名：产权交易方式
	 * 创建日期:
	 * @param newCtradetype java.lang.String
	 */
	public void setCtradetype (java.lang.String newCtradetype ) {
	 	this.ctradetype = newCtradetype;
	} 	  
	/**
	 * 属性cgreattype的Getter方法.属性名：重大资产处置方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCgreattype () {
		return cgreattype;
	}   
	/**
	 * 属性cgreattype的Setter方法.属性名：重大资产处置方式
	 * 创建日期:
	 * @param newCgreattype java.lang.String
	 */
	public void setCgreattype (java.lang.String newCgreattype ) {
	 	this.cgreattype = newCgreattype;
	} 	  
	/**
	 * 属性vlevel的Getter方法.属性名：企业级次
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVlevel () {
		return vlevel;
	}   
	/**
	 * 属性vlevel的Setter方法.属性名：企业级次
	 * 创建日期:
	 * @param newVlevel java.lang.String
	 */
	public void setVlevel (java.lang.String newVlevel ) {
	 	this.vlevel = newVlevel;
	} 	  
	/**
	 * 属性pk_sgroup的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sgroup () {
		return pk_sgroup;
	}   
	/**
	 * 属性pk_sgroup的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_sgroup java.lang.String
	 */
	public void setPk_sgroup (java.lang.String newPk_sgroup ) {
	 	this.pk_sgroup = newPk_sgroup;
	} 	  
	/**
	 * 属性capplicant的Getter方法.属性名：申请人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCapplicant () {
		return capplicant;
	}   
	/**
	 * 属性capplicant的Setter方法.属性名：申请人
	 * 创建日期:
	 * @param newCapplicant java.lang.String
	 */
	public void setCapplicant (java.lang.String newCapplicant ) {
	 	this.capplicant = newCapplicant;
	} 	  
	/**
	 * 属性capplicantdate的Getter方法.属性名：申请日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCapplicantdate () {
		return capplicantdate;
	}   
	/**
	 * 属性capplicantdate的Setter方法.属性名：申请日期
	 * 创建日期:
	 * @param newCapplicantdate nc.vo.pub.lang.UFDate
	 */
	public void setCapplicantdate (nc.vo.pub.lang.UFDate newCapplicantdate ) {
	 	this.capplicantdate = newCapplicantdate;
	} 	  
	/**
	 * 属性pk_borg的Getter方法.属性名：标的企业
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_borg () {
		return pk_borg;
	}   
	/**
	 * 属性pk_borg的Setter方法.属性名：标的企业
	 * 创建日期:
	 * @param newPk_borg java.lang.String
	 */
	public void setPk_borg (java.lang.String newPk_borg ) {
	 	this.pk_borg = newPk_borg;
	} 	  
	/**
	 * 属性pk_reportno的Getter方法.属性名：申请单号1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_reportno () {
		return pk_reportno;
	}   
	/**
	 * 属性pk_reportno的Setter方法.属性名：申请单号1
	 * 创建日期:
	 * @param newPk_reportno java.lang.String
	 */
	public void setPk_reportno (java.lang.String newPk_reportno ) {
	 	this.pk_reportno = newPk_reportno;
	} 	  
	/**
	 * 属性vbunit的Getter方法.属性名：单位1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbunit () {
		return vbunit;
	}   
	/**
	 * 属性vbunit的Setter方法.属性名：单位1
	 * 创建日期:
	 * @param newVbunit java.lang.String
	 */
	public void setVbunit (java.lang.String newVbunit ) {
	 	this.vbunit = newVbunit;
	} 	  
	/**
	 * 属性pk_bcurrency的Getter方法.属性名：币种1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bcurrency () {
		return pk_bcurrency;
	}   
	/**
	 * 属性pk_bcurrency的Setter方法.属性名：币种1
	 * 创建日期:
	 * @param newPk_bcurrency java.lang.String
	 */
	public void setPk_bcurrency (java.lang.String newPk_bcurrency ) {
	 	this.pk_bcurrency = newPk_bcurrency;
	} 	  
	/**
	 * 属性dbpercent的Getter方法.属性名：拟转让股比(%)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbpercent () {
		return dbpercent;
	}   
	/**
	 * 属性dbpercent的Setter方法.属性名：拟转让股比(%)
	 * 创建日期:
	 * @param newDbpercent nc.vo.pub.lang.UFDouble
	 */
	public void setDbpercent (nc.vo.pub.lang.UFDouble newDbpercent ) {
	 	this.dbpercent = newDbpercent;
	} 	  
	/**
	 * 属性vbaddress的Getter方法.属性名：注册地（住所）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbaddress () {
		return vbaddress;
	}   
	/**
	 * 属性vbaddress的Setter方法.属性名：注册地（住所）
	 * 创建日期:
	 * @param newVbaddress java.lang.String
	 */
	public void setVbaddress (java.lang.String newVbaddress ) {
	 	this.vbaddress = newVbaddress;
	} 	  
	/**
	 * 属性cbsetupdate的Getter方法.属性名：成立时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCbsetupdate () {
		return cbsetupdate;
	}   
	/**
	 * 属性cbsetupdate的Setter方法.属性名：成立时间
	 * 创建日期:
	 * @param newCbsetupdate nc.vo.pub.lang.UFDate
	 */
	public void setCbsetupdate (nc.vo.pub.lang.UFDate newCbsetupdate ) {
	 	this.cbsetupdate = newCbsetupdate;
	} 	  
	/**
	 * 属性dbcapital的Getter方法.属性名：注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbcapital () {
		return dbcapital;
	}   
	/**
	 * 属性dbcapital的Setter方法.属性名：注册资本（万元）
	 * 创建日期:
	 * @param newDbcapital nc.vo.pub.lang.UFDouble
	 */
	public void setDbcapital (nc.vo.pub.lang.UFDouble newDbcapital ) {
	 	this.dbcapital = newDbcapital;
	} 	  
	/**
	 * 属性vbfactype的Getter方法.属性名：企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbfactype () {
		return vbfactype;
	}   
	/**
	 * 属性vbfactype的Setter方法.属性名：企业类别
	 * 创建日期:
	 * @param newVbfactype java.lang.String
	 */
	public void setVbfactype (java.lang.String newVbfactype ) {
	 	this.vbfactype = newVbfactype;
	} 	  
	/**
	 * 属性ibinpost的Getter方法.属性名：在岗职工人数
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIbinpost () {
		return ibinpost;
	}   
	/**
	 * 属性ibinpost的Setter方法.属性名：在岗职工人数
	 * 创建日期:
	 * @param newIbinpost java.lang.Integer
	 */
	public void setIbinpost (java.lang.Integer newIbinpost ) {
	 	this.ibinpost = newIbinpost;
	} 	  
	/**
	 * 属性ibretired的Getter方法.属性名：离退休人数
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIbretired () {
		return ibretired;
	}   
	/**
	 * 属性ibretired的Setter方法.属性名：离退休人数
	 * 创建日期:
	 * @param newIbretired java.lang.Integer
	 */
	public void setIbretired (java.lang.Integer newIbretired ) {
	 	this.ibretired = newIbretired;
	} 	  
	/**
	 * 属性cbtransferflag的Getter方法.属性名：是否有国有划拨土地
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCbtransferflag () {
		return cbtransferflag;
	}   
	/**
	 * 属性cbtransferflag的Setter方法.属性名：是否有国有划拨土地
	 * 创建日期:
	 * @param newCbtransferflag nc.vo.pub.lang.UFBoolean
	 */
	public void setCbtransferflag (nc.vo.pub.lang.UFBoolean newCbtransferflag ) {
	 	this.cbtransferflag = newCbtransferflag;
	} 	  
	/**
	 * 属性cbreportdate的Getter方法.属性名：报表日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCbreportdate () {
		return cbreportdate;
	}   
	/**
	 * 属性cbreportdate的Setter方法.属性名：报表日期
	 * 创建日期:
	 * @param newCbreportdate nc.vo.pub.lang.UFDate
	 */
	public void setCbreportdate (nc.vo.pub.lang.UFDate newCbreportdate ) {
	 	this.cbreportdate = newCbreportdate;
	} 	  
	/**
	 * 属性dbassets的Getter方法.属性名：资产（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbassets () {
		return dbassets;
	}   
	/**
	 * 属性dbassets的Setter方法.属性名：资产（万元）
	 * 创建日期:
	 * @param newDbassets nc.vo.pub.lang.UFDouble
	 */
	public void setDbassets (nc.vo.pub.lang.UFDouble newDbassets ) {
	 	this.dbassets = newDbassets;
	} 	  
	/**
	 * 属性dbdebt的Getter方法.属性名：负债（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbdebt () {
		return dbdebt;
	}   
	/**
	 * 属性dbdebt的Setter方法.属性名：负债（万元）
	 * 创建日期:
	 * @param newDbdebt nc.vo.pub.lang.UFDouble
	 */
	public void setDbdebt (nc.vo.pub.lang.UFDouble newDbdebt ) {
	 	this.dbdebt = newDbdebt;
	} 	  
	/**
	 * 属性dbnetassets的Getter方法.属性名：净资产（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbnetassets () {
		return dbnetassets;
	}   
	/**
	 * 属性dbnetassets的Setter方法.属性名：净资产（万元）
	 * 创建日期:
	 * @param newDbnetassets nc.vo.pub.lang.UFDouble
	 */
	public void setDbnetassets (nc.vo.pub.lang.UFDouble newDbnetassets ) {
	 	this.dbnetassets = newDbnetassets;
	} 	  
	/**
	 * 属性dbincome的Getter方法.属性名：营业收入（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbincome () {
		return dbincome;
	}   
	/**
	 * 属性dbincome的Setter方法.属性名：营业收入（万元）
	 * 创建日期:
	 * @param newDbincome nc.vo.pub.lang.UFDouble
	 */
	public void setDbincome (nc.vo.pub.lang.UFDouble newDbincome ) {
	 	this.dbincome = newDbincome;
	} 	  
	/**
	 * 属性dbnetprofit的Getter方法.属性名：净利润（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbnetprofit () {
		return dbnetprofit;
	}   
	/**
	 * 属性dbnetprofit的Setter方法.属性名：净利润（万元）
	 * 创建日期:
	 * @param newDbnetprofit nc.vo.pub.lang.UFDouble
	 */
	public void setDbnetprofit (nc.vo.pub.lang.UFDouble newDbnetprofit ) {
	 	this.dbnetprofit = newDbnetprofit;
	} 	  
	/**
	 * 属性vbinternal的Getter方法.属性名：内部审议情况
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbinternal () {
		return vbinternal;
	}   
	/**
	 * 属性vbinternal的Setter方法.属性名：内部审议情况
	 * 创建日期:
	 * @param newVbinternal java.lang.String
	 */
	public void setVbinternal (java.lang.String newVbinternal ) {
	 	this.vbinternal = newVbinternal;
	} 	  
	/**
	 * 属性cbgiveup的Getter方法.属性名：标的企业原股东是否放弃行使优先购买权
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCbgiveup () {
		return cbgiveup;
	}   
	/**
	 * 属性cbgiveup的Setter方法.属性名：标的企业原股东是否放弃行使优先购买权
	 * 创建日期:
	 * @param newCbgiveup nc.vo.pub.lang.UFBoolean
	 */
	public void setCbgiveup (nc.vo.pub.lang.UFBoolean newCbgiveup ) {
	 	this.cbgiveup = newCbgiveup;
	} 	  
	/**
	 * 属性vbintent的Getter方法.属性名：管理层拟参与受让意向
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbintent () {
		return vbintent;
	}   
	/**
	 * 属性vbintent的Setter方法.属性名：管理层拟参与受让意向
	 * 创建日期:
	 * @param newVbintent java.lang.String
	 */
	public void setVbintent (java.lang.String newVbintent ) {
	 	this.vbintent = newVbintent;
	} 	  
	/**
	 * 属性vbother的Getter方法.属性名：其他披露内容
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbother () {
		return vbother;
	}   
	/**
	 * 属性vbother的Setter方法.属性名：其他披露内容
	 * 创建日期:
	 * @param newVbother java.lang.String
	 */
	public void setVbother (java.lang.String newVbother ) {
	 	this.vbother = newVbother;
	} 	  
	/**
	 * 属性dbcarrying的Getter方法.属性名：账面价值(万元)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbcarrying () {
		return dbcarrying;
	}   
	/**
	 * 属性dbcarrying的Setter方法.属性名：账面价值(万元)
	 * 创建日期:
	 * @param newDbcarrying nc.vo.pub.lang.UFDouble
	 */
	public void setDbcarrying (nc.vo.pub.lang.UFDouble newDbcarrying ) {
	 	this.dbcarrying = newDbcarrying;
	} 	  
	/**
	 * 属性vbdetail的Getter方法.属性名：资产明细
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbdetail () {
		return vbdetail;
	}   
	/**
	 * 属性vbdetail的Setter方法.属性名：资产明细
	 * 创建日期:
	 * @param newVbdetail java.lang.String
	 */
	public void setVbdetail (java.lang.String newVbdetail ) {
	 	this.vbdetail = newVbdetail;
	} 	  
	/**
	 * 属性vrname的Getter方法.属性名：转让方名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVrname () {
		return vrname;
	}   
	/**
	 * 属性vrname的Setter方法.属性名：转让方名称
	 * 创建日期:
	 * @param newVrname java.lang.String
	 */
	public void setVrname (java.lang.String newVrname ) {
	 	this.vrname = newVrname;
	} 	  
	/**
	 * 属性pk_rorg的Getter方法.属性名：组织机构代码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rorg () {
		return pk_rorg;
	}   
	/**
	 * 属性pk_rorg的Setter方法.属性名：组织机构代码
	 * 创建日期:
	 * @param newPk_rorg java.lang.String
	 */
	public void setPk_rorg (java.lang.String newPk_rorg ) {
	 	this.pk_rorg = newPk_rorg;
	} 	  
	/**
	 * 属性drcapital的Getter方法.属性名：转让方注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDrcapital () {
		return drcapital;
	}   
	/**
	 * 属性drcapital的Setter方法.属性名：转让方注册资本（万元）
	 * 创建日期:
	 * @param newDrcapital nc.vo.pub.lang.UFDouble
	 */
	public void setDrcapital (nc.vo.pub.lang.UFDouble newDrcapital ) {
	 	this.drcapital = newDrcapital;
	} 	  
	/**
	 * 属性vrfactype的Getter方法.属性名：转让方企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVrfactype () {
		return vrfactype;
	}   
	/**
	 * 属性vrfactype的Setter方法.属性名：转让方企业类别
	 * 创建日期:
	 * @param newVrfactype java.lang.String
	 */
	public void setVrfactype (java.lang.String newVrfactype ) {
	 	this.vrfactype = newVrfactype;
	} 	  
	/**
	 * 属性pk_rgroup的Getter方法.属性名：转让方所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rgroup () {
		return pk_rgroup;
	}   
	/**
	 * 属性pk_rgroup的Setter方法.属性名：转让方所属集团
	 * 创建日期:
	 * @param newPk_rgroup java.lang.String
	 */
	public void setPk_rgroup (java.lang.String newPk_rgroup ) {
	 	this.pk_rgroup = newPk_rgroup;
	} 	  
	/**
	 * 属性pk_passess的Getter方法.属性名：评估机构
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_passess () {
		return pk_passess;
	}   
	/**
	 * 属性pk_passess的Setter方法.属性名：评估机构
	 * 创建日期:
	 * @param newPk_passess java.lang.String
	 */
	public void setPk_passess (java.lang.String newPk_passess ) {
	 	this.pk_passess = newPk_passess;
	} 	  
	/**
	 * 属性vpcode的Getter方法.属性名：评估报告编号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVpcode () {
		return vpcode;
	}   
	/**
	 * 属性vpcode的Setter方法.属性名：评估报告编号
	 * 创建日期:
	 * @param newVpcode java.lang.String
	 */
	public void setVpcode (java.lang.String newVpcode ) {
	 	this.vpcode = newVpcode;
	} 	  
	/**
	 * 属性vporgname的Getter方法.属性名：核准（备案）机构
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVporgname () {
		return vporgname;
	}   
	/**
	 * 属性vporgname的Setter方法.属性名：核准（备案）机构
	 * 创建日期:
	 * @param newVporgname java.lang.String
	 */
	public void setVporgname (java.lang.String newVporgname ) {
	 	this.vporgname = newVporgname;
	} 	  
	/**
	 * 属性vpnumber的Getter方法.属性名：核准（备案）文号（编号）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVpnumber () {
		return vpnumber;
	}   
	/**
	 * 属性vpnumber的Setter方法.属性名：核准（备案）文号（编号）
	 * 创建日期:
	 * @param newVpnumber java.lang.String
	 */
	public void setVpnumber (java.lang.String newVpnumber ) {
	 	this.vpnumber = newVpnumber;
	} 	  
	/**
	 * 属性vpdate的Getter方法.属性名：核准（备案）日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getVpdate () {
		return vpdate;
	}   
	/**
	 * 属性vpdate的Setter方法.属性名：核准（备案）日期
	 * 创建日期:
	 * @param newVpdate nc.vo.pub.lang.UFDate
	 */
	public void setVpdate (nc.vo.pub.lang.UFDate newVpdate ) {
	 	this.vpdate = newVpdate;
	} 	  
	/**
	 * 属性vpbasedate的Getter方法.属性名：评估基准日
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getVpbasedate () {
		return vpbasedate;
	}   
	/**
	 * 属性vpbasedate的Setter方法.属性名：评估基准日
	 * 创建日期:
	 * @param newVpbasedate nc.vo.pub.lang.UFDate
	 */
	public void setVpbasedate (nc.vo.pub.lang.UFDate newVpbasedate ) {
	 	this.vpbasedate = newVpbasedate;
	} 	  
	/**
	 * 属性vpbasename的Getter方法.属性名：评估基准日审计机构
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVpbasename () {
		return vpbasename;
	}   
	/**
	 * 属性vpbasename的Setter方法.属性名：评估基准日审计机构
	 * 创建日期:
	 * @param newVpbasename java.lang.String
	 */
	public void setVpbasename (java.lang.String newVpbasename ) {
	 	this.vpbasename = newVpbasename;
	} 	  
	/**
	 * 属性vplawyer的Getter方法.属性名：律师事务所
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVplawyer () {
		return vplawyer;
	}   
	/**
	 * 属性vplawyer的Setter方法.属性名：律师事务所
	 * 创建日期:
	 * @param newVplawyer java.lang.String
	 */
	public void setVplawyer (java.lang.String newVplawyer ) {
	 	this.vplawyer = newVplawyer;
	} 	  
	/**
	 * 属性dpcarrying的Getter方法.属性名：评估价值（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDpcarrying () {
		return dpcarrying;
	}   
	/**
	 * 属性dpcarrying的Setter方法.属性名：评估价值（万元）
	 * 创建日期:
	 * @param newDpcarrying nc.vo.pub.lang.UFDouble
	 */
	public void setDpcarrying (nc.vo.pub.lang.UFDouble newDpcarrying ) {
	 	this.dpcarrying = newDpcarrying;
	} 	  
	/**
	 * 属性vwname的Getter方法.属性名：产权交易机构名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwname () {
		return vwname;
	}   
	/**
	 * 属性vwname的Setter方法.属性名：产权交易机构名称
	 * 创建日期:
	 * @param newVwname java.lang.String
	 */
	public void setVwname (java.lang.String newVwname ) {
	 	this.vwname = newVwname;
	} 	  
	/**
	 * 属性vwunit的Getter方法.属性名：单位2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwunit () {
		return vwunit;
	}   
	/**
	 * 属性vwunit的Setter方法.属性名：单位2
	 * 创建日期:
	 * @param newVwunit java.lang.String
	 */
	public void setVwunit (java.lang.String newVwunit ) {
	 	this.vwunit = newVwunit;
	} 	  
	/**
	 * 属性pk_wcurrency的Getter方法.属性名：币种2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_wcurrency () {
		return pk_wcurrency;
	}   
	/**
	 * 属性pk_wcurrency的Setter方法.属性名：币种2
	 * 创建日期:
	 * @param newPk_wcurrency java.lang.String
	 */
	public void setPk_wcurrency (java.lang.String newPk_wcurrency ) {
	 	this.pk_wcurrency = newPk_wcurrency;
	} 	  
	/**
	 * 属性vacceptno的Getter方法.属性名：批准文号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVacceptno () {
		return vacceptno;
	}   
	/**
	 * 属性vacceptno的Setter方法.属性名：批准文号
	 * 创建日期:
	 * @param newVacceptno java.lang.String
	 */
	public void setVacceptno (java.lang.String newVacceptno ) {
	 	this.vacceptno = newVacceptno;
	} 	  
	/**
	 * 属性vwperiod的Getter方法.属性名：信息公告期间
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwperiod () {
		return vwperiod;
	}   
	/**
	 * 属性vwperiod的Setter方法.属性名：信息公告期间
	 * 创建日期:
	 * @param newVwperiod java.lang.String
	 */
	public void setVwperiod (java.lang.String newVwperiod ) {
	 	this.vwperiod = newVwperiod;
	} 	  
	/**
	 * 属性dwprice的Getter方法.属性名：挂牌价格(万元)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDwprice () {
		return dwprice;
	}   
	/**
	 * 属性dwprice的Setter方法.属性名：挂牌价格(万元)
	 * 创建日期:
	 * @param newDwprice nc.vo.pub.lang.UFDouble
	 */
	public void setDwprice (nc.vo.pub.lang.UFDouble newDwprice ) {
	 	this.dwprice = newDwprice;
	} 	  
	/**
	 * 属性cwtransflag的Getter方法.属性名：是否成交
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCwtransflag () {
		return cwtransflag;
	}   
	/**
	 * 属性cwtransflag的Setter方法.属性名：是否成交
	 * 创建日期:
	 * @param newCwtransflag nc.vo.pub.lang.UFBoolean
	 */
	public void setCwtransflag (nc.vo.pub.lang.UFBoolean newCwtransflag ) {
	 	this.cwtransflag = newCwtransflag;
	} 	  
	/**
	 * 属性vwtranstype的Getter方法.属性名：交易方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwtranstype () {
		return vwtranstype;
	}   
	/**
	 * 属性vwtranstype的Setter方法.属性名：交易方式
	 * 创建日期:
	 * @param newVwtranstype java.lang.String
	 */
	public void setVwtranstype (java.lang.String newVwtranstype ) {
	 	this.vwtranstype = newVwtranstype;
	} 	  
	/**
	 * 属性dwtransprice的Getter方法.属性名：成交金额(万元)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDwtransprice () {
		return dwtransprice;
	}   
	/**
	 * 属性dwtransprice的Setter方法.属性名：成交金额(万元)
	 * 创建日期:
	 * @param newDwtransprice nc.vo.pub.lang.UFDouble
	 */
	public void setDwtransprice (nc.vo.pub.lang.UFDouble newDwtransprice ) {
	 	this.dwtransprice = newDwtransprice;
	} 	  
	/**
	 * 属性vwassignname的Getter方法.属性名：产权交易受让方名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwassignname () {
		return vwassignname;
	}   
	/**
	 * 属性vwassignname的Setter方法.属性名：产权交易受让方名称
	 * 创建日期:
	 * @param newVwassignname java.lang.String
	 */
	public void setVwassignname (java.lang.String newVwassignname ) {
	 	this.vwassignname = newVwassignname;
	} 	  
	/**
	 * 属性vwassigtype的Getter方法.属性名：受让方经济类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwassigtype () {
		return vwassigtype;
	}   
	/**
	 * 属性vwassigtype的Setter方法.属性名：受让方经济类型
	 * 创建日期:
	 * @param newVwassigtype java.lang.String
	 */
	public void setVwassigtype (java.lang.String newVwassigtype ) {
	 	this.vwassigtype = newVwassigtype;
	} 	  
	/**
	 * 属性cwctdate的Getter方法.属性名：合同签订日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCwctdate () {
		return cwctdate;
	}   
	/**
	 * 属性cwctdate的Setter方法.属性名：合同签订日期
	 * 创建日期:
	 * @param newCwctdate nc.vo.pub.lang.UFDate
	 */
	public void setCwctdate (nc.vo.pub.lang.UFDate newCwctdate ) {
	 	this.cwctdate = newCwctdate;
	} 	  
	/**
	 * 属性vwpayment的Getter方法.属性名：付款方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwpayment () {
		return vwpayment;
	}   
	/**
	 * 属性vwpayment的Setter方法.属性名：付款方式
	 * 创建日期:
	 * @param newVwpayment java.lang.String
	 */
	public void setVwpayment (java.lang.String newVwpayment ) {
	 	this.vwpayment = newVwpayment;
	} 	  
	/**
	 * 属性dwdownpayment的Getter方法.属性名：首付金额(万元)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDwdownpayment () {
		return dwdownpayment;
	}   
	/**
	 * 属性dwdownpayment的Setter方法.属性名：首付金额(万元)
	 * 创建日期:
	 * @param newDwdownpayment nc.vo.pub.lang.UFDouble
	 */
	public void setDwdownpayment (nc.vo.pub.lang.UFDouble newDwdownpayment ) {
	 	this.dwdownpayment = newDwdownpayment;
	} 	  
	/**
	 * 属性dwdownpercent的Getter方法.属性名：首付比例(%)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDwdownpercent () {
		return dwdownpercent;
	}   
	/**
	 * 属性dwdownpercent的Setter方法.属性名：首付比例(%)
	 * 创建日期:
	 * @param newDwdownpercent nc.vo.pub.lang.UFDouble
	 */
	public void setDwdownpercent (nc.vo.pub.lang.UFDouble newDwdownpercent ) {
	 	this.dwdownpercent = newDwdownpercent;
	} 	  
	/**
	 * 属性cwbalancedate的Getter方法.属性名：尾款付款期限
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCwbalancedate () {
		return cwbalancedate;
	}   
	/**
	 * 属性cwbalancedate的Setter方法.属性名：尾款付款期限
	 * 创建日期:
	 * @param newCwbalancedate nc.vo.pub.lang.UFDate
	 */
	public void setCwbalancedate (nc.vo.pub.lang.UFDate newCwbalancedate ) {
	 	this.cwbalancedate = newCwbalancedate;
	} 	  
	/**
	 * 属性cwforensicdate的Getter方法.属性名：出具交易鉴证日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCwforensicdate () {
		return cwforensicdate;
	}   
	/**
	 * 属性cwforensicdate的Setter方法.属性名：出具交易鉴证日期
	 * 创建日期:
	 * @param newCwforensicdate nc.vo.pub.lang.UFDate
	 */
	public void setCwforensicdate (nc.vo.pub.lang.UFDate newCwforensicdate ) {
	 	this.cwforensicdate = newCwforensicdate;
	} 	  
	/**
	 * 属性vsname的Getter方法.属性名：受让方名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVsname () {
		return vsname;
	}   
	/**
	 * 属性vsname的Setter方法.属性名：受让方名称
	 * 创建日期:
	 * @param newVsname java.lang.String
	 */
	public void setVsname (java.lang.String newVsname ) {
	 	this.vsname = newVsname;
	} 	  
	/**
	 * 属性pk_sorg的Getter方法.属性名：受让方组织机构代码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sorg () {
		return pk_sorg;
	}   
	/**
	 * 属性pk_sorg的Setter方法.属性名：受让方组织机构代码
	 * 创建日期:
	 * @param newPk_sorg java.lang.String
	 */
	public void setPk_sorg (java.lang.String newPk_sorg ) {
	 	this.pk_sorg = newPk_sorg;
	} 	  
	/**
	 * 属性vsunit的Getter方法.属性名：单位3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVsunit () {
		return vsunit;
	}   
	/**
	 * 属性vsunit的Setter方法.属性名：单位3
	 * 创建日期:
	 * @param newVsunit java.lang.String
	 */
	public void setVsunit (java.lang.String newVsunit ) {
	 	this.vsunit = newVsunit;
	} 	  
	/**
	 * 属性pk_scurrency的Getter方法.属性名：币种3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_scurrency () {
		return pk_scurrency;
	}   
	/**
	 * 属性pk_scurrency的Setter方法.属性名：币种3
	 * 创建日期:
	 * @param newPk_scurrency java.lang.String
	 */
	public void setPk_scurrency (java.lang.String newPk_scurrency ) {
	 	this.pk_scurrency = newPk_scurrency;
	} 	  
	/**
	 * 属性vagency的Getter方法.属性名：国资监管机构
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVagency () {
		return vagency;
	}   
	/**
	 * 属性vagency的Setter方法.属性名：国资监管机构
	 * 创建日期:
	 * @param newVagency java.lang.String
	 */
	public void setVagency (java.lang.String newVagency ) {
	 	this.vagency = newVagency;
	} 	  
	/**
	 * 属性dscapital的Getter方法.属性名：受让方注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDscapital () {
		return dscapital;
	}   
	/**
	 * 属性dscapital的Setter方法.属性名：受让方注册资本（万元）
	 * 创建日期:
	 * @param newDscapital nc.vo.pub.lang.UFDouble
	 */
	public void setDscapital (nc.vo.pub.lang.UFDouble newDscapital ) {
	 	this.dscapital = newDscapital;
	} 	  
	/**
	 * 属性vsfactype的Getter方法.属性名：受让方企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVsfactype () {
		return vsfactype;
	}   
	/**
	 * 属性vsfactype的Setter方法.属性名：受让方企业类别
	 * 创建日期:
	 * @param newVsfactype java.lang.String
	 */
	public void setVsfactype (java.lang.String newVsfactype ) {
	 	this.vsfactype = newVsfactype;
	} 	  
	/**
	 * 属性pk_slgroup的Getter方法.属性名：受让方所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_slgroup () {
		return pk_slgroup;
	}   
	/**
	 * 属性pk_slgroup的Setter方法.属性名：受让方所属集团
	 * 创建日期:
	 * @param newPk_slgroup java.lang.String
	 */
	public void setPk_slgroup (java.lang.String newPk_slgroup ) {
	 	this.pk_slgroup = newPk_slgroup;
	} 	  
	/**
	 * 属性vjunit的Getter方法.属性名：单位4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVjunit () {
		return vjunit;
	}   
	/**
	 * 属性vjunit的Setter方法.属性名：单位4
	 * 创建日期:
	 * @param newVjunit java.lang.String
	 */
	public void setVjunit (java.lang.String newVjunit ) {
	 	this.vjunit = newVjunit;
	} 	  
	/**
	 * 属性pk_jcurrency的Getter方法.属性名：币种4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_jcurrency () {
		return pk_jcurrency;
	}   
	/**
	 * 属性pk_jcurrency的Setter方法.属性名：币种4
	 * 创建日期:
	 * @param newPk_jcurrency java.lang.String
	 */
	public void setPk_jcurrency (java.lang.String newPk_jcurrency ) {
	 	this.pk_jcurrency = newPk_jcurrency;
	} 	  
	/**
	 * 属性djprice的Getter方法.属性名：增（减）资价格
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDjprice () {
		return djprice;
	}   
	/**
	 * 属性djprice的Setter方法.属性名：增（减）资价格
	 * 创建日期:
	 * @param newDjprice nc.vo.pub.lang.UFDouble
	 */
	public void setDjprice (nc.vo.pub.lang.UFDouble newDjprice ) {
	 	this.djprice = newDjprice;
	} 	  
	/**
	 * 属性djdate的Getter方法.属性名：增（减）资完成日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDjdate () {
		return djdate;
	}   
	/**
	 * 属性djdate的Setter方法.属性名：增（减）资完成日期
	 * 创建日期:
	 * @param newDjdate nc.vo.pub.lang.UFDate
	 */
	public void setDjdate (nc.vo.pub.lang.UFDate newDjdate ) {
	 	this.djdate = newDjdate;
	} 	  
	/**
	 * 属性vqunit的Getter方法.属性名：单位5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVqunit () {
		return vqunit;
	}   
	/**
	 * 属性vqunit的Setter方法.属性名：单位5
	 * 创建日期:
	 * @param newVqunit java.lang.String
	 */
	public void setVqunit (java.lang.String newVqunit ) {
	 	this.vqunit = newVqunit;
	} 	  
	/**
	 * 属性pk_qcurrency的Getter方法.属性名：币种5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_qcurrency () {
		return pk_qcurrency;
	}   
	/**
	 * 属性pk_qcurrency的Setter方法.属性名：币种5
	 * 创建日期:
	 * @param newPk_qcurrency java.lang.String
	 */
	public void setPk_qcurrency (java.lang.String newPk_qcurrency ) {
	 	this.pk_qcurrency = newPk_qcurrency;
	} 	  
	/**
	 * 属性vqstock的Getter方法.属性名：股票代码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVqstock () {
		return vqstock;
	}   
	/**
	 * 属性vqstock的Setter方法.属性名：股票代码
	 * 创建日期:
	 * @param newVqstock java.lang.String
	 */
	public void setVqstock (java.lang.String newVqstock ) {
	 	this.vqstock = newVqstock;
	} 	  
	/**
	 * 属性cqpricedate的Getter方法.属性名：定价基准日
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCqpricedate () {
		return cqpricedate;
	}   
	/**
	 * 属性cqpricedate的Setter方法.属性名：定价基准日
	 * 创建日期:
	 * @param newCqpricedate java.lang.String
	 */
	public void setCqpricedate (java.lang.String newCqpricedate ) {
	 	this.cqpricedate = newCqpricedate;
	} 	  
	/**
	 * 属性attrname的Getter方法.属性名：定价基准日前20个交易日股票均价（元/股）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAttrname () {
		return attrname;
	}   
	/**
	 * 属性attrname的Setter方法.属性名：定价基准日前20个交易日股票均价（元/股）
	 * 创建日期:
	 * @param newAttrname java.lang.String
	 */
	public void setAttrname (java.lang.String newAttrname ) {
	 	this.attrname = newAttrname;
	} 	  
	/**
	 * 属性dqrealprice的Getter方法.属性名：确定的每股交易价格（元/股）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDqrealprice () {
		return dqrealprice;
	}   
	/**
	 * 属性dqrealprice的Setter方法.属性名：确定的每股交易价格（元/股）
	 * 创建日期:
	 * @param newDqrealprice java.lang.String
	 */
	public void setDqrealprice (java.lang.String newDqrealprice ) {
	 	this.dqrealprice = newDqrealprice;
	} 	  
	/**
	 * 属性vqname的Getter方法.属性名：财务顾问名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVqname () {
		return vqname;
	}   
	/**
	 * 属性vqname的Setter方法.属性名：财务顾问名称
	 * 创建日期:
	 * @param newVqname java.lang.String
	 */
	public void setVqname (java.lang.String newVqname ) {
	 	this.vqname = newVqname;
	} 	  
	/**
	 * 属性vqlawyer的Getter方法.属性名：律师事务所名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVqlawyer () {
		return vqlawyer;
	}   
	/**
	 * 属性vqlawyer的Setter方法.属性名：律师事务所名称
	 * 创建日期:
	 * @param newVqlawyer java.lang.String
	 */
	public void setVqlawyer (java.lang.String newVqlawyer ) {
	 	this.vqlawyer = newVqlawyer;
	} 	  
	/**
	 * 属性vqaccount的Getter方法.属性名：会计师事务所名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVqaccount () {
		return vqaccount;
	}   
	/**
	 * 属性vqaccount的Setter方法.属性名：会计师事务所名称
	 * 创建日期:
	 * @param newVqaccount java.lang.String
	 */
	public void setVqaccount (java.lang.String newVqaccount ) {
	 	this.vqaccount = newVqaccount;
	} 	  
	/**
	 * 属性vqprinciple的Getter方法.属性名：定价原则
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getVqprinciple () {
		return vqprinciple;
	}   
	/**
	 * 属性vqprinciple的Setter方法.属性名：定价原则
	 * 创建日期:
	 * @param newVqprinciple java.lang.Integer
	 */
	public void setVqprinciple (java.lang.Integer newVqprinciple ) {
	 	this.vqprinciple = newVqprinciple;
	} 	  
	/**
	 * 属性vqbaseassess的Getter方法.属性名：企业并购评估基准日审计机构
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVqbaseassess () {
		return vqbaseassess;
	}   
	/**
	 * 属性vqbaseassess的Setter方法.属性名：企业并购评估基准日审计机构
	 * 创建日期:
	 * @param newVqbaseassess java.lang.String
	 */
	public void setVqbaseassess (java.lang.String newVqbaseassess ) {
	 	this.vqbaseassess = newVqbaseassess;
	} 	  
	/**
	 * 属性dqperprice的Getter方法.属性名：确定的每份出资交易价格（元/1元出资）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDqperprice () {
		return dqperprice;
	}   
	/**
	 * 属性dqperprice的Setter方法.属性名：确定的每份出资交易价格（元/1元出资）
	 * 创建日期:
	 * @param newDqperprice nc.vo.pub.lang.UFDouble
	 */
	public void setDqperprice (nc.vo.pub.lang.UFDouble newDqperprice ) {
	 	this.dqperprice = newDqperprice;
	} 	  
	/**
	 * 属性iqmatype的Getter方法.属性名：并购方式
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIqmatype () {
		return iqmatype;
	}   
	/**
	 * 属性iqmatype的Setter方法.属性名：并购方式
	 * 创建日期:
	 * @param newIqmatype java.lang.Integer
	 */
	public void setIqmatype (java.lang.Integer newIqmatype ) {
	 	this.iqmatype = newIqmatype;
	} 	  
	/**
	 * 属性dqprice的Getter方法.属性名：交易对价总额（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDqprice () {
		return dqprice;
	}   
	/**
	 * 属性dqprice的Setter方法.属性名：交易对价总额（万元）
	 * 创建日期:
	 * @param newDqprice nc.vo.pub.lang.UFDouble
	 */
	public void setDqprice (nc.vo.pub.lang.UFDouble newDqprice ) {
	 	this.dqprice = newDqprice;
	} 	  
	/**
	 * 属性pk_gorg的Getter方法.属性名：标的企业名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_gorg () {
		return pk_gorg;
	}   
	/**
	 * 属性pk_gorg的Setter方法.属性名：标的企业名称
	 * 创建日期:
	 * @param newPk_gorg java.lang.String
	 */
	public void setPk_gorg (java.lang.String newPk_gorg ) {
	 	this.pk_gorg = newPk_gorg;
	} 	  
	/**
	 * 属性dgpercent的Getter方法.属性名：并购企业信息组织机构代码
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDgpercent () {
		return dgpercent;
	}   
	/**
	 * 属性dgpercent的Setter方法.属性名：并购企业信息组织机构代码
	 * 创建日期:
	 * @param newDgpercent java.lang.Integer
	 */
	public void setDgpercent (java.lang.Integer newDgpercent ) {
	 	this.dgpercent = newDgpercent;
	} 	  
	/**
	 * 属性vgunit的Getter方法.属性名：单位6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVgunit () {
		return vgunit;
	}   
	/**
	 * 属性vgunit的Setter方法.属性名：单位6
	 * 创建日期:
	 * @param newVgunit java.lang.String
	 */
	public void setVgunit (java.lang.String newVgunit ) {
	 	this.vgunit = newVgunit;
	} 	  
	/**
	 * 属性pk_gcurrency的Getter方法.属性名：币种6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_gcurrency () {
		return pk_gcurrency;
	}   
	/**
	 * 属性pk_gcurrency的Setter方法.属性名：币种6
	 * 创建日期:
	 * @param newPk_gcurrency java.lang.String
	 */
	public void setPk_gcurrency (java.lang.String newPk_gcurrency ) {
	 	this.pk_gcurrency = newPk_gcurrency;
	} 	  
	/**
	 * 属性vgaddress的Getter方法.属性名：并购企业信息注册地（住所）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVgaddress () {
		return vgaddress;
	}   
	/**
	 * 属性vgaddress的Setter方法.属性名：并购企业信息注册地（住所）
	 * 创建日期:
	 * @param newVgaddress java.lang.String
	 */
	public void setVgaddress (java.lang.String newVgaddress ) {
	 	this.vgaddress = newVgaddress;
	} 	  
	/**
	 * 属性cgsetupdate的Getter方法.属性名：并购企业信息成立时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCgsetupdate () {
		return cgsetupdate;
	}   
	/**
	 * 属性cgsetupdate的Setter方法.属性名：并购企业信息成立时间
	 * 创建日期:
	 * @param newCgsetupdate nc.vo.pub.lang.UFDate
	 */
	public void setCgsetupdate (nc.vo.pub.lang.UFDate newCgsetupdate ) {
	 	this.cgsetupdate = newCgsetupdate;
	} 	  
	/**
	 * 属性dgcapital的Getter方法.属性名：并购企业信息注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDgcapital () {
		return dgcapital;
	}   
	/**
	 * 属性dgcapital的Setter方法.属性名：并购企业信息注册资本（万元）
	 * 创建日期:
	 * @param newDgcapital nc.vo.pub.lang.UFDouble
	 */
	public void setDgcapital (nc.vo.pub.lang.UFDouble newDgcapital ) {
	 	this.dgcapital = newDgcapital;
	} 	  
	/**
	 * 属性vgfactype的Getter方法.属性名：并购企业信息企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVgfactype () {
		return vgfactype;
	}   
	/**
	 * 属性vgfactype的Setter方法.属性名：并购企业信息企业类别
	 * 创建日期:
	 * @param newVgfactype java.lang.String
	 */
	public void setVgfactype (java.lang.String newVgfactype ) {
	 	this.vgfactype = newVgfactype;
	} 	  
	/**
	 * 属性cgreportdate的Getter方法.属性名：并购企业信息报表日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCgreportdate () {
		return cgreportdate;
	}   
	/**
	 * 属性cgreportdate的Setter方法.属性名：并购企业信息报表日期
	 * 创建日期:
	 * @param newCgreportdate nc.vo.pub.lang.UFDate
	 */
	public void setCgreportdate (nc.vo.pub.lang.UFDate newCgreportdate ) {
	 	this.cgreportdate = newCgreportdate;
	} 	  
	/**
	 * 属性dgassets的Getter方法.属性名：并购企业信息资产（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDgassets () {
		return dgassets;
	}   
	/**
	 * 属性dgassets的Setter方法.属性名：并购企业信息资产（万元）
	 * 创建日期:
	 * @param newDgassets nc.vo.pub.lang.UFDouble
	 */
	public void setDgassets (nc.vo.pub.lang.UFDouble newDgassets ) {
	 	this.dgassets = newDgassets;
	} 	  
	/**
	 * 属性dgdebt的Getter方法.属性名：并购企业信息负债（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDgdebt () {
		return dgdebt;
	}   
	/**
	 * 属性dgdebt的Setter方法.属性名：并购企业信息负债（万元）
	 * 创建日期:
	 * @param newDgdebt nc.vo.pub.lang.UFDouble
	 */
	public void setDgdebt (nc.vo.pub.lang.UFDouble newDgdebt ) {
	 	this.dgdebt = newDgdebt;
	} 	  
	/**
	 * 属性dgnetassets的Getter方法.属性名：并购企业信息净资产（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDgnetassets () {
		return dgnetassets;
	}   
	/**
	 * 属性dgnetassets的Setter方法.属性名：并购企业信息净资产（万元）
	 * 创建日期:
	 * @param newDgnetassets nc.vo.pub.lang.UFDouble
	 */
	public void setDgnetassets (nc.vo.pub.lang.UFDouble newDgnetassets ) {
	 	this.dgnetassets = newDgnetassets;
	} 	  
	/**
	 * 属性dgincome的Getter方法.属性名：并购企业信息营业收入（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDgincome () {
		return dgincome;
	}   
	/**
	 * 属性dgincome的Setter方法.属性名：并购企业信息营业收入（万元）
	 * 创建日期:
	 * @param newDgincome nc.vo.pub.lang.UFDouble
	 */
	public void setDgincome (nc.vo.pub.lang.UFDouble newDgincome ) {
	 	this.dgincome = newDgincome;
	} 	  
	/**
	 * 属性dgnetprofit的Getter方法.属性名：并购企业信息净利润（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDgnetprofit () {
		return dgnetprofit;
	}   
	/**
	 * 属性dgnetprofit的Setter方法.属性名：并购企业信息净利润（万元）
	 * 创建日期:
	 * @param newDgnetprofit nc.vo.pub.lang.UFDouble
	 */
	public void setDgnetprofit (nc.vo.pub.lang.UFDouble newDgnetprofit ) {
	 	this.dgnetprofit = newDgnetprofit;
	} 	  
	/**
	 * 属性vcname的Getter方法.属性名：资产持有单位名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcname () {
		return vcname;
	}   
	/**
	 * 属性vcname的Setter方法.属性名：资产持有单位名称
	 * 创建日期:
	 * @param newVcname java.lang.String
	 */
	public void setVcname (java.lang.String newVcname ) {
	 	this.vcname = newVcname;
	} 	  
	/**
	 * 属性vccode的Getter方法.属性名：资产持有单位组织机构代码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVccode () {
		return vccode;
	}   
	/**
	 * 属性vccode的Setter方法.属性名：资产持有单位组织机构代码
	 * 创建日期:
	 * @param newVccode java.lang.String
	 */
	public void setVccode (java.lang.String newVccode ) {
	 	this.vccode = newVccode;
	} 	  
	/**
	 * 属性vcunit的Getter方法.属性名：单位7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcunit () {
		return vcunit;
	}   
	/**
	 * 属性vcunit的Setter方法.属性名：单位7
	 * 创建日期:
	 * @param newVcunit java.lang.String
	 */
	public void setVcunit (java.lang.String newVcunit ) {
	 	this.vcunit = newVcunit;
	} 	  
	/**
	 * 属性pk_ccurrency的Getter方法.属性名：币种7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_ccurrency () {
		return pk_ccurrency;
	}   
	/**
	 * 属性pk_ccurrency的Setter方法.属性名：币种7
	 * 创建日期:
	 * @param newPk_ccurrency java.lang.String
	 */
	public void setPk_ccurrency (java.lang.String newPk_ccurrency ) {
	 	this.pk_ccurrency = newPk_ccurrency;
	} 	  
	/**
	 * 属性dccapital的Getter方法.属性名：处置注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDccapital () {
		return dccapital;
	}   
	/**
	 * 属性dccapital的Setter方法.属性名：处置注册资本（万元）
	 * 创建日期:
	 * @param newDccapital nc.vo.pub.lang.UFDouble
	 */
	public void setDccapital (nc.vo.pub.lang.UFDouble newDccapital ) {
	 	this.dccapital = newDccapital;
	} 	  
	/**
	 * 属性vcfactype的Getter方法.属性名：处置企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcfactype () {
		return vcfactype;
	}   
	/**
	 * 属性vcfactype的Setter方法.属性名：处置企业类别
	 * 创建日期:
	 * @param newVcfactype java.lang.String
	 */
	public void setVcfactype (java.lang.String newVcfactype ) {
	 	this.vcfactype = newVcfactype;
	} 	  
	/**
	 * 属性pk_cgroup的Getter方法.属性名：处置所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_cgroup () {
		return pk_cgroup;
	}   
	/**
	 * 属性pk_cgroup的Setter方法.属性名：处置所属集团
	 * 创建日期:
	 * @param newPk_cgroup java.lang.String
	 */
	public void setPk_cgroup (java.lang.String newPk_cgroup ) {
	 	this.pk_cgroup = newPk_cgroup;
	} 	  
	/**
	 * 属性vcinside的Getter方法.属性名：处置标的企业内部决策文件
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcinside () {
		return vcinside;
	}   
	/**
	 * 属性vcinside的Setter方法.属性名：处置标的企业内部决策文件
	 * 创建日期:
	 * @param newVcinside java.lang.String
	 */
	public void setVcinside (java.lang.String newVcinside ) {
	 	this.vcinside = newVcinside;
	} 	  
	/**
	 * 属性vccorpname的Getter方法.属性名：处置行为批准单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVccorpname () {
		return vccorpname;
	}   
	/**
	 * 属性vccorpname的Setter方法.属性名：处置行为批准单位
	 * 创建日期:
	 * @param newVccorpname java.lang.String
	 */
	public void setVccorpname (java.lang.String newVccorpname ) {
	 	this.vccorpname = newVccorpname;
	} 	  
	/**
	 * 属性ccpolicydate的Getter方法.属性名：决策时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCcpolicydate () {
		return ccpolicydate;
	}   
	/**
	 * 属性ccpolicydate的Setter方法.属性名：决策时间
	 * 创建日期:
	 * @param newCcpolicydate nc.vo.pub.lang.UFDate
	 */
	public void setCcpolicydate (nc.vo.pub.lang.UFDate newCcpolicydate ) {
	 	this.ccpolicydate = newCcpolicydate;
	} 	  
	/**
	 * 属性ccapprovedate的Getter方法.属性名：批准日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCcapprovedate () {
		return ccapprovedate;
	}   
	/**
	 * 属性ccapprovedate的Setter方法.属性名：批准日期
	 * 创建日期:
	 * @param newCcapprovedate nc.vo.pub.lang.UFDate
	 */
	public void setCcapprovedate (nc.vo.pub.lang.UFDate newCcapprovedate ) {
	 	this.ccapprovedate = newCcapprovedate;
	} 	  
	/**
	 * 属性vcrecordno的Getter方法.属性名：备案编号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcrecordno () {
		return vcrecordno;
	}   
	/**
	 * 属性vcrecordno的Setter方法.属性名：备案编号
	 * 创建日期:
	 * @param newVcrecordno java.lang.String
	 */
	public void setVcrecordno (java.lang.String newVcrecordno ) {
	 	this.vcrecordno = newVcrecordno;
	} 	  
	/**
	 * 属性vcassessname的Getter方法.属性名：处置标的资产名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcassessname () {
		return vcassessname;
	}   
	/**
	 * 属性vcassessname的Setter方法.属性名：处置标的资产名称
	 * 创建日期:
	 * @param newVcassessname java.lang.String
	 */
	public void setVcassessname (java.lang.String newVcassessname ) {
	 	this.vcassessname = newVcassessname;
	} 	  
	/**
	 * 属性vcassesstype的Getter方法.属性名：资产处置方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcassesstype () {
		return vcassesstype;
	}   
	/**
	 * 属性vcassesstype的Setter方法.属性名：资产处置方式
	 * 创建日期:
	 * @param newVcassesstype java.lang.String
	 */
	public void setVcassesstype (java.lang.String newVcassesstype ) {
	 	this.vcassesstype = newVcassesstype;
	} 	  
	/**
	 * 属性vcfactyoe的Getter方法.属性名：处置标的企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcfactyoe () {
		return vcfactyoe;
	}   
	/**
	 * 属性vcfactyoe的Setter方法.属性名：处置标的企业类别
	 * 创建日期:
	 * @param newVcfactyoe java.lang.String
	 */
	public void setVcfactyoe (java.lang.String newVcfactyoe ) {
	 	this.vcfactyoe = newVcfactyoe;
	} 	  
	/**
	 * 属性vcother的Getter方法.属性名：其他需要说明的情况
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcother () {
		return vcother;
	}   
	/**
	 * 属性vcother的Setter方法.属性名：其他需要说明的情况
	 * 创建日期:
	 * @param newVcother java.lang.String
	 */
	public void setVcother (java.lang.String newVcother ) {
	 	this.vcother = newVcother;
	} 	  
	/**
	 * 属性id_scappt_transfer_target的Getter方法.属性名：id_scappt_transfer_target
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptTransferTargetVO[]
	 */
	public nc.scap.pt.vos.ScapptTransferTargetVO[] getId_scappt_transfer_target () {
		return id_scappt_transfer_target;
	}   
	/**
	 * 属性id_scappt_transfer_target的Setter方法.属性名：id_scappt_transfer_target
	 * 创建日期:
	 * @param newId_scappt_transfer_target nc.scap.pt.vos.ScapptTransferTargetVO[]
	 */
	public void setId_scappt_transfer_target (nc.scap.pt.vos.ScapptTransferTargetVO[] newId_scappt_transfer_target ) {
	 	this.id_scappt_transfer_target = newId_scappt_transfer_target;
	} 	  
	/**
	 * 属性id_scappt_transfer_transferor的Getter方法.属性名：id_scappt_transfer_transferor
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptTransferTransferorVO[]
	 */
	public nc.scap.pt.vos.ScapptTransferTransferorVO[] getId_scappt_transfer_transferor () {
		return id_scappt_transfer_transferor;
	}   
	/**
	 * 属性id_scappt_transfer_transferor的Setter方法.属性名：id_scappt_transfer_transferor
	 * 创建日期:
	 * @param newId_scappt_transfer_transferor nc.scap.pt.vos.ScapptTransferTransferorVO[]
	 */
	public void setId_scappt_transfer_transferor (nc.scap.pt.vos.ScapptTransferTransferorVO[] newId_scappt_transfer_transferor ) {
	 	this.id_scappt_transfer_transferor = newId_scappt_transfer_transferor;
	} 	  
	/**
	 * 属性id_scappt_transfer_assess的Getter方法.属性名：id_scappt_transfer_assess
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptTransferAssessVO[]
	 */
	public nc.scap.pt.vos.ScapptTransferAssessVO[] getId_scappt_transfer_assess () {
		return id_scappt_transfer_assess;
	}   
	/**
	 * 属性id_scappt_transfer_assess的Setter方法.属性名：id_scappt_transfer_assess
	 * 创建日期:
	 * @param newId_scappt_transfer_assess nc.scap.pt.vos.ScapptTransferAssessVO[]
	 */
	public void setId_scappt_transfer_assess (nc.scap.pt.vos.ScapptTransferAssessVO[] newId_scappt_transfer_assess ) {
	 	this.id_scappt_transfer_assess = newId_scappt_transfer_assess;
	} 	  
	/**
	 * 属性id_scappt_transfer_transferee的Getter方法.属性名：id_scappt_transfer_transferee
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptTransferTransfereeVO[]
	 */
	public nc.scap.pt.vos.ScapptTransferTransfereeVO[] getId_scappt_transfer_transferee () {
		return id_scappt_transfer_transferee;
	}   
	/**
	 * 属性id_scappt_transfer_transferee的Setter方法.属性名：id_scappt_transfer_transferee
	 * 创建日期:
	 * @param newId_scappt_transfer_transferee nc.scap.pt.vos.ScapptTransferTransfereeVO[]
	 */
	public void setId_scappt_transfer_transferee (nc.scap.pt.vos.ScapptTransferTransfereeVO[] newId_scappt_transfer_transferee ) {
	 	this.id_scappt_transfer_transferee = newId_scappt_transfer_transferee;
	} 	  
	/**
	 * 属性id_scappt_attach的Getter方法.属性名：id_scappt_attach
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptAttachVO[]
	 */
	public nc.scap.pt.vos.ScapptAttachVO[] getId_scappt_attach () {
		return id_scappt_attach;
	}   
	/**
	 * 属性id_scappt_attach的Setter方法.属性名：id_scappt_attach
	 * 创建日期:
	 * @param newId_scappt_attach nc.scap.pt.vos.ScapptAttachVO[]
	 */
	public void setId_scappt_attach (nc.scap.pt.vos.ScapptAttachVO[] newId_scappt_attach ) {
	 	this.id_scappt_attach = newId_scappt_attach;
	} 	  
	/**
	 * 属性vcasstype的Getter方法.属性名：转让方经济类型
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public java.lang.String  getVcasstype () {
		return vcasstype;
	}   
	/**
	 * 属性vcasstype的Setter方法.属性名：转让方经济类型
	 * 创建日期:
	 * @param newVcasstype nc.vo.pub.lang.UFDouble
	 */
	public void setVcasstype (java.lang.String  newVcasstype ) {
	 	this.vcasstype = newVcasstype;
	} 	  
	/**
	 * 属性cassetstype的Getter方法.属性名：国资监管类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCassetstype () {
		return cassetstype;
	}   
	/**
	 * 属性cassetstype的Setter方法.属性名：国资监管类型
	 * 创建日期:
	 * @param newCassetstype java.lang.String
	 */
	public void setCassetstype (java.lang.String newCassetstype ) {
	 	this.cassetstype = newCassetstype;
	} 	  
	/**
	 * 属性industry的Getter方法.属性名：行业
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIndustry () {
		return industry;
	}   
	/**
	 * 属性industry的Setter方法.属性名：行业
	 * 创建日期:
	 * @param newIndustry java.lang.String
	 */
	public void setIndustry (java.lang.String newIndustry ) {
	 	this.industry = newIndustry;
	} 	  
	/**
	 * 属性tramethod的Getter方法.属性名：成交方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTramethod () {
		return tramethod;
	}   
	/**
	 * 属性tramethod的Setter方法.属性名：成交方式
	 * 创建日期:
	 * @param newTramethod java.lang.String
	 */
	public void setTramethod (java.lang.String newTramethod ) {
	 	this.tramethod = newTramethod;
	} 	  
	/**
	 * 属性traarea的Getter方法.属性名：交易区域
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTraarea () {
		return traarea;
	}   
	/**
	 * 属性traarea的Setter方法.属性名：交易区域
	 * 创建日期:
	 * @param newTraarea java.lang.String
	 */
	public void setTraarea (java.lang.String newTraarea ) {
	 	this.traarea = newTraarea;
	} 	  
	/**
	 * 属性traname的Getter方法.属性名：转让标的名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTraname () {
		return traname;
	}   
	/**
	 * 属性traname的Setter方法.属性名：转让标的名称
	 * 创建日期:
	 * @param newTraname java.lang.String
	 */
	public void setTraname (java.lang.String newTraname ) {
	 	this.traname = newTraname;
	} 	  
	/**
	 * 属性isleadin的Getter方法.属性名：是否导入
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsleadin () {
		return isleadin;
	}   
	/**
	 * 属性isleadin的Setter方法.属性名：是否导入
	 * 创建日期:
	 * @param newIsleadin nc.vo.pub.lang.UFBoolean
	 */
	public void setIsleadin (nc.vo.pub.lang.UFBoolean newIsleadin ) {
	 	this.isleadin = newIsleadin;
	} 	  
	/**
	 * 属性ismerge的Getter方法.属性名：是否合并
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIsmerge () {
		return ismerge;
	}   
	/**
	 * 属性ismerge的Setter方法.属性名：是否合并
	 * 创建日期:
	 * @param newIsmerge java.lang.String
	 */
	public void setIsmerge (java.lang.String newIsmerge ) {
	 	this.ismerge = newIsmerge;
	} 	  
	/**
	 * 属性vcsasstype的Getter方法.属性名：受让方经济类型1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcsasstype () {
		return vcsasstype;
	}   
	/**
	 * 属性vcsasstype的Setter方法.属性名：受让方经济类型1
	 * 创建日期:
	 * @param newVcsasstype java.lang.String
	 */
	public void setVcsasstype (java.lang.String newVcsasstype ) {
	 	this.vcsasstype = newVcsasstype;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：自定义字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：自定义字段1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：自定义字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：自定义字段2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：自定义字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：自定义字段3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：自定义字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：自定义字段4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：自定义字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：自定义字段5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：自定义字段6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：自定义字段6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：自定义字段7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：自定义字段7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：自定义字段8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：自定义字段8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：自定义字段9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：自定义字段9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：自定义字段10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：自定义字段10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性listvalue的Getter方法.属性名：申请挂牌价格
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getListvalue () {
		return listvalue;
	}   
	/**
	 * 属性listvalue的Setter方法.属性名：申请挂牌价格
	 * 创建日期:
	 * @param newListvalue nc.vo.pub.lang.UFDouble
	 */
	public void setListvalue (nc.vo.pub.lang.UFDouble newListvalue ) {
	 	this.listvalue = newListvalue;
	} 	  
	/**
	 * 属性isgzw的Getter方法.属性名：是否国资委审核
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIsgzw () {
		return isgzw;
	}   
	/**
	 * 属性isgzw的Setter方法.属性名：是否国资委审核
	 * 创建日期:
	 * @param newIsgzw java.lang.String
	 */
	public void setIsgzw (java.lang.String newIsgzw ) {
	 	this.isgzw = newIsgzw;
	} 	  
	/**
	 * 属性leadintramodel的Getter方法.属性名：导入交易方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getLeadintramodel () {
		return leadintramodel;
	}   
	/**
	 * 属性leadintramodel的Setter方法.属性名：导入交易方式
	 * 创建日期:
	 * @param newLeadintramodel java.lang.String
	 */
	public void setLeadintramodel (java.lang.String newLeadintramodel ) {
	 	this.leadintramodel = newLeadintramodel;
	} 	  
	/**
	 * 属性pk_bfirmbase_h的Getter方法.属性名：产权登记主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bfirmbase_h () {
		return pk_bfirmbase_h;
	}   
	/**
	 * 属性pk_bfirmbase_h的Setter方法.属性名：产权登记主键
	 * 创建日期:
	 * @param newPk_bfirmbase_h java.lang.String
	 */
	public void setPk_bfirmbase_h (java.lang.String newPk_bfirmbase_h ) {
	 	this.pk_bfirmbase_h = newPk_bfirmbase_h;
	} 	  
	/**
	 * 属性pk_rfirmbase_h的Getter方法.属性名：所属集团产权登记主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rfirmbase_h () {
		return pk_rfirmbase_h;
	}   
	/**
	 * 属性pk_rfirmbase_h的Setter方法.属性名：所属集团产权登记主键
	 * 创建日期:
	 * @param newPk_rfirmbase_h java.lang.String
	 */
	public void setPk_rfirmbase_h (java.lang.String newPk_rfirmbase_h ) {
	 	this.pk_rfirmbase_h = newPk_rfirmbase_h;
	} 	  
	/**
	 * 属性pk_sfirmbase_h的Getter方法.属性名：产权登记主键1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sfirmbase_h () {
		return pk_sfirmbase_h;
	}   
	/**
	 * 属性pk_sfirmbase_h的Setter方法.属性名：产权登记主键1
	 * 创建日期:
	 * @param newPk_sfirmbase_h java.lang.String
	 */
	public void setPk_sfirmbase_h (java.lang.String newPk_sfirmbase_h ) {
	 	this.pk_sfirmbase_h = newPk_sfirmbase_h;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_transfer_h";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scappt_transfer_h";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scappt_transfer_h";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapptTransferHVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pt.vos.ScapptTransferHVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


