/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pt.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapptInfoCountBVO extends SuperVO {
	private java.lang.String pk_infocount;
	private java.lang.String pk_infocount_b;
	private java.lang.String project;
	private java.lang.String rowcount;
	private java.lang.String jezs;
	private java.lang.String cjje;
	private java.lang.String sj_zcze;
	private java.lang.String sj_jzc;
	private java.lang.String pg_zcze;
	private java.lang.String pg_jzc;
	private java.lang.String zrbdgpz;
	private java.lang.String jyzjz;
	private java.lang.String jyzjl;
	private java.lang.String vlevle;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_INFOCOUNT = "pk_infocount";
	public static final String PK_INFOCOUNT_B = "pk_infocount_b";
	public static final String PROJECT = "project";
	public static final String ROWCOUNT = "rowcount";
	public static final String JEZS = "jezs";
	public static final String CJJE = "cjje";
	public static final String SJ_ZCZE = "sj_zcze";
	public static final String SJ_JZC = "sj_jzc";
	public static final String PG_ZCZE = "pg_zcze";
	public static final String PG_JZC = "pg_jzc";
	public static final String ZRBDGPZ = "zrbdgpz";
	public static final String JYZJZ = "jyzjz";
	public static final String JYZJL = "jyzjl";
	public static final String VLEVLE = "vlevle";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
			
	/**
	 * 属性pk_infocount的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_infocount () {
		return pk_infocount;
	}   
	/**
	 * 属性pk_infocount的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_infocount java.lang.String
	 */
	public void setPk_infocount (java.lang.String newPk_infocount ) {
	 	this.pk_infocount = newPk_infocount;
	} 	  
	/**
	 * 属性pk_infocount_b的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_infocount_b () {
		return pk_infocount_b;
	}   
	/**
	 * 属性pk_infocount_b的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_infocount_b java.lang.String
	 */
	public void setPk_infocount_b (java.lang.String newPk_infocount_b ) {
	 	this.pk_infocount_b = newPk_infocount_b;
	} 	  
	/**
	 * 属性project的Getter方法.属性名：项目
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getProject () {
		return project;
	}   
	/**
	 * 属性project的Setter方法.属性名：项目
	 * 创建日期:
	 * @param newProject java.lang.String
	 */
	public void setProject (java.lang.String newProject ) {
	 	this.project = newProject;
	} 	  
	/**
	 * 属性rowcount的Getter方法.属性名：行次
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRowcount () {
		return rowcount;
	}   
	/**
	 * 属性rowcount的Setter方法.属性名：行次
	 * 创建日期:
	 * @param newRowcount java.lang.String
	 */
	public void setRowcount (java.lang.String newRowcount ) {
	 	this.rowcount = newRowcount;
	} 	  
	/**
	 * 属性jezs的Getter方法.属性名：交易宗数
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getJezs () {
		return jezs;
	}   
	/**
	 * 属性jezs的Setter方法.属性名：交易宗数
	 * 创建日期:
	 * @param newJezs java.lang.String
	 */
	public void setJezs (java.lang.String newJezs ) {
	 	this.jezs = newJezs;
	} 	  
	/**
	 * 属性cjje的Getter方法.属性名：成交金额
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCjje () {
		return cjje;
	}   
	/**
	 * 属性cjje的Setter方法.属性名：成交金额
	 * 创建日期:
	 * @param newCjje java.lang.String
	 */
	public void setCjje (java.lang.String newCjje ) {
	 	this.cjje = newCjje;
	} 	  
	/**
	 * 属性sj_zcze的Getter方法.属性名：审计(资产总额)
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSj_zcze () {
		return sj_zcze;
	}   
	/**
	 * 属性sj_zcze的Setter方法.属性名：审计(资产总额)
	 * 创建日期:
	 * @param newSj_zcze java.lang.String
	 */
	public void setSj_zcze (java.lang.String newSj_zcze ) {
	 	this.sj_zcze = newSj_zcze;
	} 	  
	/**
	 * 属性sj_jzc的Getter方法.属性名：审计(净资产)
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSj_jzc () {
		return sj_jzc;
	}   
	/**
	 * 属性sj_jzc的Setter方法.属性名：审计(净资产)
	 * 创建日期:
	 * @param newSj_jzc java.lang.String
	 */
	public void setSj_jzc (java.lang.String newSj_jzc ) {
	 	this.sj_jzc = newSj_jzc;
	} 	  
	/**
	 * 属性pg_zcze的Getter方法.属性名：评估(资产总额)
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPg_zcze () {
		return pg_zcze;
	}   
	/**
	 * 属性pg_zcze的Setter方法.属性名：评估(资产总额)
	 * 创建日期:
	 * @param newPg_zcze java.lang.String
	 */
	public void setPg_zcze (java.lang.String newPg_zcze ) {
	 	this.pg_zcze = newPg_zcze;
	} 	  
	/**
	 * 属性pg_jzc的Getter方法.属性名：评估(净资产)
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPg_jzc () {
		return pg_jzc;
	}   
	/**
	 * 属性pg_jzc的Setter方法.属性名：评估(净资产)
	 * 创建日期:
	 * @param newPg_jzc java.lang.String
	 */
	public void setPg_jzc (java.lang.String newPg_jzc ) {
	 	this.pg_jzc = newPg_jzc;
	} 	  
	/**
	 * 属性zrbdgpz的Getter方法.属性名：转让标的评估值
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getZrbdgpz () {
		return zrbdgpz;
	}   
	/**
	 * 属性zrbdgpz的Setter方法.属性名：转让标的评估值
	 * 创建日期:
	 * @param newZrbdgpz java.lang.String
	 */
	public void setZrbdgpz (java.lang.String newZrbdgpz ) {
	 	this.zrbdgpz = newZrbdgpz;
	} 	  
	/**
	 * 属性jyzjz的Getter方法.属性名：交易增(减)值
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getJyzjz () {
		return jyzjz;
	}   
	/**
	 * 属性jyzjz的Setter方法.属性名：交易增(减)值
	 * 创建日期:
	 * @param newJyzjz java.lang.String
	 */
	public void setJyzjz (java.lang.String newJyzjz ) {
	 	this.jyzjz = newJyzjz;
	} 	  
	/**
	 * 属性jyzjl的Getter方法.属性名：交易增(减)率
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getJyzjl () {
		return jyzjl;
	}   
	/**
	 * 属性jyzjl的Setter方法.属性名：交易增(减)率
	 * 创建日期:
	 * @param newJyzjl java.lang.String
	 */
	public void setJyzjl (java.lang.String newJyzjl ) {
	 	this.jyzjl = newJyzjl;
	} 	  
	/**
	 * 属性vlevle的Getter方法.属性名：级次
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVlevle () {
		return vlevle;
	}   
	/**
	 * 属性vlevle的Setter方法.属性名：级次
	 * 创建日期:
	 * @param newVlevle java.lang.String
	 */
	public void setVlevle (java.lang.String newVlevle ) {
	 	this.vlevle = newVlevle;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：自定义1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：自定义1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：自定义2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：自定义2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：自定义3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：自定义3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：自定义4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：自定义4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：自定义5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：自定义5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_infocount";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_infocount_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scappt_infocount_b";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scappt_infocount_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapptInfoCountBVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pt.vos.ScapptInfoCountBVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


