/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pt.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapptInfoCountHVO extends SuperVO {
	private java.lang.String pk_infocount;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private nc.vo.pub.lang.UFDate begindate;
	private nc.vo.pub.lang.UFDate enddate;
	private java.lang.String transjg;
	private java.lang.String jgtype;
	private java.lang.String vunit;
	private java.lang.String biller;
	private nc.vo.pub.lang.UFDateTime billdate;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.scap.pt.vos.ScapptInfoCountBVO[] id_scappt_infocount_b;

	public static final String PK_INFOCOUNT = "pk_infocount";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String BEGINDATE = "begindate";
	public static final String ENDDATE = "enddate";
	public static final String TRANSJG = "transjg";
	public static final String JGTYPE = "jgtype";
	public static final String VUNIT = "vunit";
	public static final String BILLER = "biller";
	public static final String BILLDATE = "billdate";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
			
	/**
	 * 属性pk_org的Getter方法.属性名：组织主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织主键
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团主键
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 
	
	/**
	 * 属性pk_infocount的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_infocount () {
		return pk_infocount;
	}   
	/**
	 * 属性pk_infocount的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_infocount java.lang.String
	 */
	public void setPk_infocount (java.lang.String newPk_infocount ) {
	 	this.pk_infocount = newPk_infocount;
	} 	  
	/**
	 * 属性begindate的Getter方法.属性名：开始日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getBegindate () {
		return begindate;
	}   
	/**
	 * 属性begindate的Setter方法.属性名：开始日期
	 * 创建日期:
	 * @param newBegindate nc.vo.pub.lang.UFDate
	 */
	public void setBegindate (nc.vo.pub.lang.UFDate newBegindate ) {
	 	this.begindate = newBegindate;
	} 	  
	/**
	 * 属性enddate的Getter方法.属性名：结束日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getEnddate () {
		return enddate;
	}   
	/**
	 * 属性enddate的Setter方法.属性名：结束日期
	 * 创建日期:
	 * @param newEnddate nc.vo.pub.lang.UFDate
	 */
	public void setEnddate (nc.vo.pub.lang.UFDate newEnddate ) {
	 	this.enddate = newEnddate;
	} 	  
	/**
	 * 属性transjg的Getter方法.属性名：交易机构
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTransjg () {
		return transjg;
	}   
	/**
	 * 属性transjg的Setter方法.属性名：交易机构
	 * 创建日期:
	 * @param newTransjg java.lang.String
	 */
	public void setTransjg (java.lang.String newTransjg ) {
	 	this.transjg = newTransjg;
	} 	  
	/**
	 * 属性jgtype的Getter方法.属性名：监管分类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getJgtype () {
		return jgtype;
	}   
	/**
	 * 属性jgtype的Setter方法.属性名：监管分类
	 * 创建日期:
	 * @param newJgtype java.lang.String
	 */
	public void setJgtype (java.lang.String newJgtype ) {
	 	this.jgtype = newJgtype;
	} 	  
	/**
	 * 属性vunit的Getter方法.属性名：金额单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVunit () {
		return vunit;
	}   
	/**
	 * 属性vunit的Setter方法.属性名：金额单位
	 * 创建日期:
	 * @param newVunit java.lang.String
	 */
	public void setVunit (java.lang.String newVunit ) {
	 	this.vunit = newVunit;
	} 	  
	/**
	 * 属性biller的Getter方法.属性名：制单人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBiller () {
		return biller;
	}   
	/**
	 * 属性biller的Setter方法.属性名：制单人
	 * 创建日期:
	 * @param newBiller java.lang.String
	 */
	public void setBiller (java.lang.String newBiller ) {
	 	this.biller = newBiller;
	} 	  
	/**
	 * 属性billdate的Getter方法.属性名：制单日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getBilldate () {
		return billdate;
	}   
	/**
	 * 属性billdate的Setter方法.属性名：制单日期
	 * 创建日期:
	 * @param newBilldate nc.vo.pub.lang.UFDateTime
	 */
	public void setBilldate (nc.vo.pub.lang.UFDateTime newBilldate ) {
	 	this.billdate = newBilldate;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：自定义1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：自定义1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：自定义2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：自定义2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：自定义3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：自定义3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：自定义4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：自定义4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：自定义5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：自定义5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性id_scappt_infocount_b的Getter方法.属性名：id_scappt_infocount_b
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptInfoCountBVO[]
	 */
	public nc.scap.pt.vos.ScapptInfoCountBVO[] getId_scappt_infocount_b () {
		return id_scappt_infocount_b;
	}   
	/**
	 * 属性id_scappt_infocount_b的Setter方法.属性名：id_scappt_infocount_b
	 * 创建日期:
	 * @param newId_scappt_infocount_b nc.scap.pt.vos.ScapptInfoCountBVO[]
	 */
	public void setId_scappt_infocount_b (nc.scap.pt.vos.ScapptInfoCountBVO[] newId_scappt_infocount_b ) {
	 	this.id_scappt_infocount_b = newId_scappt_infocount_b;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_infocount";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scappt_infocount";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scappt_infocount";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapptInfoCountHVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pt.vos.ScapptInfoCountHVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


