/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pt.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapptExportTransHVO extends SuperVO {
	private java.lang.String pk_main;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String billmaker;
	private nc.vo.pub.lang.UFDate billmakedate;
	private java.lang.String billno;
	private java.lang.String cchangetype;
	private java.lang.String ctradetype;
	private java.lang.String vlevel;
	private java.lang.String pk_sgroup;
	private java.lang.String pk_sgroup_s;
	public java.lang.String getPk_sgroup_s() {
		return pk_sgroup_s;
	}
	public void setPk_sgroup_s(java.lang.String pk_sgroup_s) {
		this.pk_sgroup_s = pk_sgroup_s;
	}

	private java.lang.String pk_zgroup;
	private java.lang.String pk_zgroup_s;
	public java.lang.String getPk_zgroup_s() {
		return pk_zgroup_s;
	}
	public void setPk_zgroup_s(java.lang.String pk_zgroup_s) {
		this.pk_zgroup_s = pk_zgroup_s;
	}

	private java.lang.String pk_borg;
	private java.lang.String pk_borg_s;
	public java.lang.String getPk_borg_s() {
		return pk_borg_s;
	}
	public void setPk_borg_s(java.lang.String pk_borg_s) {
		this.pk_borg_s = pk_borg_s;
	}

	private java.lang.String dbpercent;
	private java.lang.String vbaddress;
	private nc.vo.pub.lang.UFDate cbsetupdate;
	private nc.vo.pub.lang.UFDouble dbcapital;
	private java.lang.String vbfactype;
	private java.lang.Integer ibinpost;
	private nc.vo.pub.lang.UFDouble ibinpost_d;
	public nc.vo.pub.lang.UFDouble getIbinpost_d() {
		return ibinpost_d;
	}
	public void setIbinpost_d(nc.vo.pub.lang.UFDouble ibinpost_d) {
		this.ibinpost_d = ibinpost_d;
	}

	private java.lang.Integer ibretired;
	private nc.vo.pub.lang.UFDouble ibretired_d;
	public nc.vo.pub.lang.UFDouble getIbretired_d() {
		return ibretired_d;
	}
	public void setIbretired_d(nc.vo.pub.lang.UFDouble ibretired_d) {
		this.ibretired_d = ibretired_d;
	}

	private nc.vo.pub.lang.UFBoolean cbtransferflag;
	private nc.vo.pub.lang.UFBoolean if_sus;
	private java.lang.String if_sus_s;
	public java.lang.String getIf_sus_s() {
		return if_sus_s;
	}
	public void setIf_sus_s(java.lang.String if_sus_s) {
		this.if_sus_s = if_sus_s;
	}

	private nc.vo.pub.lang.UFDouble vbdetail;
	private java.lang.String vrname;
	private java.lang.String pk_rorg;
	private nc.vo.pub.lang.UFDouble drcapital;
	private java.lang.String vrfactype;
	private java.lang.String pk_rgroup;
	private java.lang.String vacceptno;
	private java.lang.String vwperiod;
	private java.lang.String atrdata;
	private nc.vo.pub.lang.UFDouble dwprice;
	private nc.vo.pub.lang.UFBoolean cwtransflag;
	private java.lang.String vwtranstype;
	private java.lang.String vwtranstype_s;
	public java.lang.String getVwtranstype_s() {
		return vwtranstype_s;
	}
	public void setVwtranstype_s(java.lang.String vwtranstype_s) {
		this.vwtranstype_s = vwtranstype_s;
	}

	private nc.vo.pub.lang.UFDouble dwtransprice;
	private java.lang.String vwassignname;
	private nc.vo.pub.lang.UFDate cwctdate;
	private java.lang.String cwctdate_s;
	private java.lang.String vwpayment;
	private java.lang.String vsname;
	private java.lang.String pk_sorg;
	private java.lang.String dscapital;
	private java.lang.String address;
	private java.lang.String pk_slgroup;
	private java.lang.String pk_gorg;
	private java.lang.String vcassesstype;
	private java.lang.String tramethod;
	private java.lang.String memo;
	private java.lang.String traname;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private nc.vo.pub.lang.UFDouble listvalue;
	private java.lang.String pk_bfirmbase_h;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_MAIN = "pk_main";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLMAKEDATE = "billmakedate";
	public static final String BILLNO = "billno";
	public static final String CCHANGETYPE = "cchangetype";
	public static final String CTRADETYPE = "ctradetype";
	public static final String VLEVEL = "vlevel";
	public static final String PK_SGROUP = "pk_sgroup";
	public static final String PK_SGROUP_S = "pk_sgroup_s";
	public static final String PK_ZGROUP = "pk_zgroup";
	public static final String PK_ZGROUP_S = "pk_zgroup_s";
	public static final String PK_BORG = "pk_borg";
	public static final String PK_BORG_S = "pk_borg_s";
	public static final String DBPERCENT = "dbpercent";
	public static final String VBADDRESS = "vbaddress";
	public static final String CBSETUPDATE = "cbsetupdate";
	public static final String DBCAPITAL = "dbcapital";
	public static final String VBFACTYPE = "vbfactype";
	public static final String IBINPOST = "ibinpost";
	public static final String IBRETIRED = "ibretired";
	public static final String IBINPOST_D = "ibinpost_d";
	public static final String IBRETIRED_D = "ibretired_d";
	public static final String CBTRANSFERFLAG = "cbtransferflag";
	public static final String IF_SUS = "if_sus";
	public static final String IF_SUS_S = "if_sus_s";
	public static final String VBDETAIL = "vbdetail";
	public static final String VRNAME = "vrname";
	public static final String PK_RORG = "pk_rorg";
	public static final String DRCAPITAL = "drcapital";
	public static final String VRFACTYPE = "vrfactype";
	public static final String PK_RGROUP = "pk_rgroup";
	public static final String VACCEPTNO = "vacceptno";
	public static final String VWPERIOD = "vwperiod";
	public static final String ATRDATA = "atrdata";
	public static final String DWPRICE = "dwprice";
	public static final String CWTRANSFLAG = "cwtransflag";
	public static final String VWTRANSTYPE = "vwtranstype";
	public static final String VWTRANSTYPE_S = "vwtranstype_s";
	public static final String DWTRANSPRICE = "dwtransprice";
	public static final String VWASSIGNNAME = "vwassignname";
	public static final String CWCTDATE = "cwctdate";
	public static final String CWCTDATE_S = "cwctdate_s";
	public static final String VWPAYMENT = "vwpayment";
	public static final String VSNAME = "vsname";
	public static final String PK_SORG = "pk_sorg";
	public static final String DSCAPITAL = "dscapital";
	public static final String ADDRESS = "address";
	public static final String PK_SLGROUP = "pk_slgroup";
	public static final String PK_GORG = "pk_gorg";
	public static final String VCASSESSTYPE = "vcassesstype";
	public static final String TRAMETHOD = "tramethod";
	public static final String MEMO = "memo";
	public static final String TRANAME = "traname";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String LISTVALUE = "listvalue";
	public static final String PK_BFIRMBASE_H = "pk_bfirmbase_h";
			
	/**
	 * 属性pk_main的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_main () {
		return pk_main;
	}   
	/**
	 * 属性pk_main的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_main java.lang.String
	 */
	public void setPk_main (java.lang.String newPk_main ) {
	 	this.pk_main = newPk_main;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织主键
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团主键
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性billmaker的Getter方法.属性名：制单人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return billmaker;
	}   
	/**
	 * 属性billmaker的Setter方法.属性名：制单人
	 * 创建日期:
	 * @param newBillmaker java.lang.String
	 */
	public void setBillmaker (java.lang.String newBillmaker ) {
	 	this.billmaker = newBillmaker;
	} 	  
	/**
	 * 属性billmakedate的Getter方法.属性名：制单日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getBillmakedate () {
		return billmakedate;
	}   
	/**
	 * 属性billmakedate的Setter方法.属性名：制单日期
	 * 创建日期:
	 * @param newBillmakedate nc.vo.pub.lang.UFDate
	 */
	public void setBillmakedate (nc.vo.pub.lang.UFDate newBillmakedate ) {
	 	this.billmakedate = newBillmakedate;
	} 	  
	/**
	 * 属性billno的Getter方法.属性名：单据号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillno () {
		return billno;
	}   
	/**
	 * 属性billno的Setter方法.属性名：单据号
	 * 创建日期:
	 * @param newBillno java.lang.String
	 */
	public void setBillno (java.lang.String newBillno ) {
	 	this.billno = newBillno;
	} 	  
	/**
	 * 属性cchangetype的Getter方法.属性名：产权变动类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCchangetype () {
		return cchangetype;
	}   
	/**
	 * 属性cchangetype的Setter方法.属性名：产权变动类型
	 * 创建日期:
	 * @param newCchangetype java.lang.String
	 */
	public void setCchangetype (java.lang.String newCchangetype ) {
	 	this.cchangetype = newCchangetype;
	} 	  
	/**
	 * 属性ctradetype的Getter方法.属性名：产权交易方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCtradetype () {
		return ctradetype;
	}   
	/**
	 * 属性ctradetype的Setter方法.属性名：产权交易方式
	 * 创建日期:
	 * @param newCtradetype java.lang.String
	 */
	public void setCtradetype (java.lang.String newCtradetype ) {
	 	this.ctradetype = newCtradetype;
	} 	  
	/**
	 * 属性vlevel的Getter方法.属性名：企业级次
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVlevel () {
		return vlevel;
	}   
	/**
	 * 属性vlevel的Setter方法.属性名：企业级次
	 * 创建日期:
	 * @param newVlevel java.lang.String
	 */
	public void setVlevel (java.lang.String newVlevel ) {
	 	this.vlevel = newVlevel;
	} 	  
	/**
	 * 属性pk_sgroup的Getter方法.属性名：委托单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sgroup () {
		return pk_sgroup;
	}   
	/**
	 * 属性pk_sgroup的Setter方法.属性名：委托单位
	 * 创建日期:
	 * @param newPk_sgroup java.lang.String
	 */
	public void setPk_sgroup (java.lang.String newPk_sgroup ) {
	 	this.pk_sgroup = newPk_sgroup;
	} 	  
	/**
	 * 属性pk_zgroup的Getter方法.属性名：省属企业集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_zgroup () {
		return pk_zgroup;
	}   
	/**
	 * 属性pk_zgroup的Setter方法.属性名：省属企业集团
	 * 创建日期:
	 * @param newPk_zgroup java.lang.String
	 */
	public void setPk_zgroup (java.lang.String newPk_zgroup ) {
	 	this.pk_zgroup = newPk_zgroup;
	} 	  
	/**
	 * 属性pk_borg的Getter方法.属性名：标的企业
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_borg () {
		return pk_borg;
	}   
	/**
	 * 属性pk_borg的Setter方法.属性名：标的企业
	 * 创建日期:
	 * @param newPk_borg java.lang.String
	 */
	public void setPk_borg (java.lang.String newPk_borg ) {
	 	this.pk_borg = newPk_borg;
	} 	  
	/**
	 * 属性dbpercent的Getter方法.属性名：业务性质
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDbpercent () {
		return dbpercent;
	}   
	/**
	 * 属性dbpercent的Setter方法.属性名：业务性质
	 * 创建日期:
	 * @param newDbpercent java.lang.String
	 */
	public void setDbpercent (java.lang.String newDbpercent ) {
	 	this.dbpercent = newDbpercent;
	} 	  
	/**
	 * 属性vbaddress的Getter方法.属性名：注册地（住所）
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbaddress () {
		return vbaddress;
	}   
	/**
	 * 属性vbaddress的Setter方法.属性名：注册地（住所）
	 * 创建日期:
	 * @param newVbaddress java.lang.String
	 */
	public void setVbaddress (java.lang.String newVbaddress ) {
	 	this.vbaddress = newVbaddress;
	} 	  
	/**
	 * 属性cbsetupdate的Getter方法.属性名：成立时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCbsetupdate () {
		return cbsetupdate;
	}   
	/**
	 * 属性cbsetupdate的Setter方法.属性名：成立时间
	 * 创建日期:
	 * @param newCbsetupdate nc.vo.pub.lang.UFDate
	 */
	public void setCbsetupdate (nc.vo.pub.lang.UFDate newCbsetupdate ) {
	 	this.cbsetupdate = newCbsetupdate;
	} 	  
	/**
	 * 属性dbcapital的Getter方法.属性名：注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDbcapital () {
		return dbcapital;
	}   
	/**
	 * 属性dbcapital的Setter方法.属性名：注册资本（万元）
	 * 创建日期:
	 * @param newDbcapital nc.vo.pub.lang.UFDouble
	 */
	public void setDbcapital (nc.vo.pub.lang.UFDouble newDbcapital ) {
	 	this.dbcapital = newDbcapital;
	} 	  
	/**
	 * 属性vbfactype的Getter方法.属性名：企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbfactype () {
		return vbfactype;
	}   
	/**
	 * 属性vbfactype的Setter方法.属性名：企业类别
	 * 创建日期:
	 * @param newVbfactype java.lang.String
	 */
	public void setVbfactype (java.lang.String newVbfactype ) {
	 	this.vbfactype = newVbfactype;
	} 	  
	/**
	 * 属性ibinpost的Getter方法.属性名：公告次数
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIbinpost () {
		return ibinpost;
	}   
	/**
	 * 属性ibinpost的Setter方法.属性名：公告次数
	 * 创建日期:
	 * @param newIbinpost java.lang.Integer
	 */
	public void setIbinpost (java.lang.Integer newIbinpost ) {
	 	this.ibinpost = newIbinpost;
	} 	  
	/**
	 * 属性ibretired的Getter方法.属性名：竞买人数
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIbretired () {
		return ibretired;
	}   
	/**
	 * 属性ibretired的Setter方法.属性名：竞买人数
	 * 创建日期:
	 * @param newIbretired java.lang.Integer
	 */
	public void setIbretired (java.lang.Integer newIbretired ) {
	 	this.ibretired = newIbretired;
	} 	  
	/**
	 * 属性cbtransferflag的Getter方法.属性名：是否有国有划拨土地
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCbtransferflag () {
		return cbtransferflag;
	}   
	/**
	 * 属性cbtransferflag的Setter方法.属性名：是否有国有划拨土地
	 * 创建日期:
	 * @param newCbtransferflag nc.vo.pub.lang.UFBoolean
	 */
	public void setCbtransferflag (nc.vo.pub.lang.UFBoolean newCbtransferflag ) {
	 	this.cbtransferflag = newCbtransferflag;
	} 	  
	/**
	 * 属性if_sus的Getter方法.属性名：是否交易成功
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIf_sus () {
		return if_sus;
	}   
	/**
	 * 属性if_sus的Setter方法.属性名：是否交易成功
	 * 创建日期:
	 * @param newIf_sus nc.vo.pub.lang.UFBoolean
	 */
	public void setIf_sus (nc.vo.pub.lang.UFBoolean newIf_sus ) {
	 	this.if_sus = newIf_sus;
	} 	  
	/**
	 * 属性vbdetail的Getter方法.属性名：评估价/原租价（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVbdetail () {
		return vbdetail;
	}   
	/**
	 * 属性vbdetail的Setter方法.属性名：评估价/原租价（万元）
	 * 创建日期:
	 * @param newVbdetail nc.vo.pub.lang.UFDouble
	 */
	public void setVbdetail (nc.vo.pub.lang.UFDouble newVbdetail ) {
	 	this.vbdetail = newVbdetail;
	} 	  
	/**
	 * 属性vrname的Getter方法.属性名：转让方名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVrname () {
		return vrname;
	}   
	/**
	 * 属性vrname的Setter方法.属性名：转让方名称
	 * 创建日期:
	 * @param newVrname java.lang.String
	 */
	public void setVrname (java.lang.String newVrname ) {
	 	this.vrname = newVrname;
	} 	  
	/**
	 * 属性pk_rorg的Getter方法.属性名：组织机构代码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rorg () {
		return pk_rorg;
	}   
	/**
	 * 属性pk_rorg的Setter方法.属性名：组织机构代码
	 * 创建日期:
	 * @param newPk_rorg java.lang.String
	 */
	public void setPk_rorg (java.lang.String newPk_rorg ) {
	 	this.pk_rorg = newPk_rorg;
	} 	  
	/**
	 * 属性drcapital的Getter方法.属性名：转让方注册资本（万元）
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDrcapital () {
		return drcapital;
	}   
	/**
	 * 属性drcapital的Setter方法.属性名：转让方注册资本（万元）
	 * 创建日期:
	 * @param newDrcapital nc.vo.pub.lang.UFDouble
	 */
	public void setDrcapital (nc.vo.pub.lang.UFDouble newDrcapital ) {
	 	this.drcapital = newDrcapital;
	} 	  
	/**
	 * 属性vrfactype的Getter方法.属性名：转让方企业类别
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVrfactype () {
		return vrfactype;
	}   
	/**
	 * 属性vrfactype的Setter方法.属性名：转让方企业类别
	 * 创建日期:
	 * @param newVrfactype java.lang.String
	 */
	public void setVrfactype (java.lang.String newVrfactype ) {
	 	this.vrfactype = newVrfactype;
	} 	  
	/**
	 * 属性pk_rgroup的Getter方法.属性名：转让方所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rgroup () {
		return pk_rgroup;
	}   
	/**
	 * 属性pk_rgroup的Setter方法.属性名：转让方所属集团
	 * 创建日期:
	 * @param newPk_rgroup java.lang.String
	 */
	public void setPk_rgroup (java.lang.String newPk_rgroup ) {
	 	this.pk_rgroup = newPk_rgroup;
	} 	  
	/**
	 * 属性vacceptno的Getter方法.属性名：批准文号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVacceptno () {
		return vacceptno;
	}   
	/**
	 * 属性vacceptno的Setter方法.属性名：批准文号
	 * 创建日期:
	 * @param newVacceptno java.lang.String
	 */
	public void setVacceptno (java.lang.String newVacceptno ) {
	 	this.vacceptno = newVacceptno;
	} 	  
	/**
	 * 属性vwperiod的Getter方法.属性名：地址
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwperiod () {
		return vwperiod;
	}   
	/**
	 * 属性vwperiod的Setter方法.属性名：地址
	 * 创建日期:
	 * @param newVwperiod java.lang.String
	 */
	public void setVwperiod (java.lang.String newVwperiod ) {
	 	this.vwperiod = newVwperiod;
	} 	  
	/**
	 * 属性atrdata的Getter方法.属性名：面积/数量
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAtrdata () {
		return atrdata;
	}   
	/**
	 * 属性atrdata的Setter方法.属性名：面积/数量
	 * 创建日期:
	 * @param newAtrdata java.lang.String
	 */
	public void setAtrdata (java.lang.String newAtrdata ) {
	 	this.atrdata = newAtrdata;
	} 	  
	/**
	 * 属性dwprice的Getter方法.属性名：挂牌价格(万元)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDwprice () {
		return dwprice;
	}   
	/**
	 * 属性dwprice的Setter方法.属性名：挂牌价格(万元)
	 * 创建日期:
	 * @param newDwprice nc.vo.pub.lang.UFDouble
	 */
	public void setDwprice (nc.vo.pub.lang.UFDouble newDwprice ) {
	 	this.dwprice = newDwprice;
	} 	  
	/**
	 * 属性cwtransflag的Getter方法.属性名：是否成交
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCwtransflag () {
		return cwtransflag;
	}   
	/**
	 * 属性cwtransflag的Setter方法.属性名：是否成交
	 * 创建日期:
	 * @param newCwtransflag nc.vo.pub.lang.UFBoolean
	 */
	public void setCwtransflag (nc.vo.pub.lang.UFBoolean newCwtransflag ) {
	 	this.cwtransflag = newCwtransflag;
	} 	  
	/**
	 * 属性vwtranstype的Getter方法.属性名：交易方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwtranstype () {
		return vwtranstype;
	}   
	/**
	 * 属性vwtranstype的Setter方法.属性名：交易方式
	 * 创建日期:
	 * @param newVwtranstype java.lang.String
	 */
	public void setVwtranstype (java.lang.String newVwtranstype ) {
	 	this.vwtranstype = newVwtranstype;
	} 	  
	/**
	 * 属性dwtransprice的Getter方法.属性名：成交价(万元)
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDwtransprice () {
		return dwtransprice;
	}   
	/**
	 * 属性dwtransprice的Setter方法.属性名：成交价(万元)
	 * 创建日期:
	 * @param newDwtransprice nc.vo.pub.lang.UFDouble
	 */
	public void setDwtransprice (nc.vo.pub.lang.UFDouble newDwtransprice ) {
	 	this.dwtransprice = newDwtransprice;
	} 	  
	/**
	 * 属性vwassignname的Getter方法.属性名：产权交易受让方名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwassignname () {
		return vwassignname;
	}   
	/**
	 * 属性vwassignname的Setter方法.属性名：产权交易受让方名称
	 * 创建日期:
	 * @param newVwassignname java.lang.String
	 */
	public void setVwassignname (java.lang.String newVwassignname ) {
	 	this.vwassignname = newVwassignname;
	} 	  
	/**
	 * 属性cwctdate的Getter方法.属性名：交易时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCwctdate () {
		return cwctdate;
	}   
	/**
	 * 属性cwctdate的Setter方法.属性名：交易时间
	 * 创建日期:
	 * @param newCwctdate nc.vo.pub.lang.UFDate
	 */
	public void setCwctdate (nc.vo.pub.lang.UFDate newCwctdate ) {
	 	this.cwctdate = newCwctdate;
	} 	  
	public java.lang.String getCwctdate_s() {
		return cwctdate_s;
	}
	public void setCwctdate_s(java.lang.String cwctdate_s) {
		this.cwctdate_s = cwctdate_s;
	}
	/**
	 * 属性vwpayment的Getter方法.属性名：付款方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVwpayment () {
		return vwpayment;
	}   
	/**
	 * 属性vwpayment的Setter方法.属性名：付款方式
	 * 创建日期:
	 * @param newVwpayment java.lang.String
	 */
	public void setVwpayment (java.lang.String newVwpayment ) {
	 	this.vwpayment = newVwpayment;
	} 	  
	/**
	 * 属性vsname的Getter方法.属性名：受让方名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVsname () {
		return vsname;
	}   
	/**
	 * 属性vsname的Setter方法.属性名：受让方名称
	 * 创建日期:
	 * @param newVsname java.lang.String
	 */
	public void setVsname (java.lang.String newVsname ) {
	 	this.vsname = newVsname;
	} 	  
	/**
	 * 属性pk_sorg的Getter方法.属性名：受让方组织机构代码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sorg () {
		return pk_sorg;
	}   
	/**
	 * 属性pk_sorg的Setter方法.属性名：受让方组织机构代码
	 * 创建日期:
	 * @param newPk_sorg java.lang.String
	 */
	public void setPk_sorg (java.lang.String newPk_sorg ) {
	 	this.pk_sorg = newPk_sorg;
	} 	  
	/**
	 * 属性dscapital的Getter方法.属性名：联系电话
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDscapital () {
		return dscapital;
	}   
	/**
	 * 属性dscapital的Setter方法.属性名：联系电话
	 * 创建日期:
	 * @param newDscapital java.lang.String
	 */
	public void setDscapital (java.lang.String newDscapital ) {
	 	this.dscapital = newDscapital;
	} 	  
	/**
	 * 属性address的Getter方法.属性名：住址
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAddress () {
		return address;
	}   
	/**
	 * 属性address的Setter方法.属性名：住址
	 * 创建日期:
	 * @param newAddress java.lang.String
	 */
	public void setAddress (java.lang.String newAddress ) {
	 	this.address = newAddress;
	} 	  
	/**
	 * 属性pk_slgroup的Getter方法.属性名：受让方所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_slgroup () {
		return pk_slgroup;
	}   
	/**
	 * 属性pk_slgroup的Setter方法.属性名：受让方所属集团
	 * 创建日期:
	 * @param newPk_slgroup java.lang.String
	 */
	public void setPk_slgroup (java.lang.String newPk_slgroup ) {
	 	this.pk_slgroup = newPk_slgroup;
	} 	  
	/**
	 * 属性pk_gorg的Getter方法.属性名：标的企业名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_gorg () {
		return pk_gorg;
	}   
	/**
	 * 属性pk_gorg的Setter方法.属性名：标的企业名称
	 * 创建日期:
	 * @param newPk_gorg java.lang.String
	 */
	public void setPk_gorg (java.lang.String newPk_gorg ) {
	 	this.pk_gorg = newPk_gorg;
	} 	  
	/**
	 * 属性vcassesstype的Getter方法.属性名：资产处置方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVcassesstype () {
		return vcassesstype;
	}   
	/**
	 * 属性vcassesstype的Setter方法.属性名：资产处置方式
	 * 创建日期:
	 * @param newVcassesstype java.lang.String
	 */
	public void setVcassesstype (java.lang.String newVcassesstype ) {
	 	this.vcassesstype = newVcassesstype;
	} 	  
	/**
	 * 属性tramethod的Getter方法.属性名：成交方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTramethod () {
		return tramethod;
	}   
	/**
	 * 属性tramethod的Setter方法.属性名：成交方式
	 * 创建日期:
	 * @param newTramethod java.lang.String
	 */
	public void setTramethod (java.lang.String newTramethod ) {
	 	this.tramethod = newTramethod;
	} 	  
	/**
	 * 属性memo的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newMemo java.lang.String
	 */
	public void setMemo (java.lang.String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性traname的Getter方法.属性名：转让标的名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTraname () {
		return traname;
	}   
	/**
	 * 属性traname的Setter方法.属性名：转让标的名称
	 * 创建日期:
	 * @param newTraname java.lang.String
	 */
	public void setTraname (java.lang.String newTraname ) {
	 	this.traname = newTraname;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：自定义字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：自定义字段1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：自定义字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：自定义字段2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：自定义字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：自定义字段3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：自定义字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：自定义字段4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：自定义字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：自定义字段5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：自定义字段6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：自定义字段6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：自定义字段7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：自定义字段7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：自定义字段8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：自定义字段8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：自定义字段9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：自定义字段9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：自定义字段10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：自定义字段10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性listvalue的Getter方法.属性名：申请挂牌价格
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getListvalue () {
		return listvalue;
	}   
	/**
	 * 属性listvalue的Setter方法.属性名：申请挂牌价格
	 * 创建日期:
	 * @param newListvalue nc.vo.pub.lang.UFDouble
	 */
	public void setListvalue (nc.vo.pub.lang.UFDouble newListvalue ) {
	 	this.listvalue = newListvalue;
	} 	  
	/**
	 * 属性pk_bfirmbase_h的Getter方法.属性名：产权登记主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bfirmbase_h () {
		return pk_bfirmbase_h;
	}   
	/**
	 * 属性pk_bfirmbase_h的Setter方法.属性名：产权登记主键
	 * 创建日期:
	 * @param newPk_bfirmbase_h java.lang.String
	 */
	public void setPk_bfirmbase_h (java.lang.String newPk_bfirmbase_h ) {
	 	this.pk_bfirmbase_h = newPk_bfirmbase_h;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_main";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scappt_export_trans";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scappt_export_trans";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapptExportTransHVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pt.vos.ScapptExportTransHVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


