/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pt.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapptApplyHVO extends SuperVO {
	private java.lang.String pk_apply_h;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String billmaker;
	private nc.vo.pub.lang.UFDateTime billmakedate;
	private java.lang.String billno;
	private java.lang.String approver;
	private nc.vo.pub.lang.UFDateTime approvedate;
	private java.lang.String formstate;
	private java.lang.String formtitle;
	private java.lang.String vrequestno;
	private java.lang.String cprocesstype;
	private java.lang.String cchangetype;
	private java.lang.String ctradetype;
	private java.lang.String cgreattype;
	private java.lang.String pk_rorg;
	private java.lang.String vapproveno;
	private java.lang.String capplicant;
	private nc.vo.pub.lang.UFDateTime capplicantdate;
	private java.lang.String vdef1;
	private java.lang.String vdef2;
	private java.lang.String vdef3;
	private java.lang.String vdef4;
	private java.lang.String vdef5;
	private java.lang.String vdef6;
	private java.lang.String vdef7;
	private java.lang.String vdef8;
	private java.lang.String vdef9;
	private java.lang.String vdef10;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.scap.pt.vos.ScapptApplyBVO[] id_scappt_apply_b;
	private nc.scap.pt.vos.ScapptApplyAttachVO[] id_scappt_apply_attach;

	public static final String PK_APPLY_H = "pk_apply_h";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLMAKEDATE = "billmakedate";
	public static final String BILLNO = "billno";
	public static final String APPROVER = "approver";
	public static final String APPROVEDATE = "approvedate";
	public static final String FORMSTATE = "formstate";
	public static final String FORMTITLE = "formtitle";
	public static final String VREQUESTNO = "vrequestno";
	public static final String CPROCESSTYPE = "cprocesstype";
	public static final String CCHANGETYPE = "cchangetype";
	public static final String CTRADETYPE = "ctradetype";
	public static final String CGREATTYPE = "cgreattype";
	public static final String PK_RORG = "pk_rorg";
	public static final String VAPPROVENO = "vapproveno";
	public static final String CAPPLICANT = "capplicant";
	public static final String CAPPLICANTDATE = "capplicantdate";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF6 = "vdef6";
	public static final String VDEF7 = "vdef7";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF10 = "vdef10";
			
	/**
	 * 属性pk_apply_h的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_apply_h () {
		return pk_apply_h;
	}   
	/**
	 * 属性pk_apply_h的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_apply_h java.lang.String
	 */
	public void setPk_apply_h (java.lang.String newPk_apply_h ) {
	 	this.pk_apply_h = newPk_apply_h;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织主键
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团主键
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性billmaker的Getter方法.属性名：制单人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return billmaker;
	}   
	/**
	 * 属性billmaker的Setter方法.属性名：制单人
	 * 创建日期:
	 * @param newBillmaker java.lang.String
	 */
	public void setBillmaker (java.lang.String newBillmaker ) {
	 	this.billmaker = newBillmaker;
	} 	  
	/**
	 * 属性billmakedate的Getter方法.属性名：制单日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getBillmakedate () {
		return billmakedate;
	}   
	/**
	 * 属性billmakedate的Setter方法.属性名：制单日期
	 * 创建日期:
	 * @param newBillmakedate nc.vo.pub.lang.UFDateTime
	 */
	public void setBillmakedate (nc.vo.pub.lang.UFDateTime newBillmakedate ) {
	 	this.billmakedate = newBillmakedate;
	} 	  
	/**
	 * 属性billno的Getter方法.属性名：单据号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillno () {
		return billno;
	}   
	/**
	 * 属性billno的Setter方法.属性名：单据号
	 * 创建日期:
	 * @param newBillno java.lang.String
	 */
	public void setBillno (java.lang.String newBillno ) {
	 	this.billno = newBillno;
	} 	  
	/**
	 * 属性approver的Getter方法.属性名：审核人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprover () {
		return approver;
	}   
	/**
	 * 属性approver的Setter方法.属性名：审核人
	 * 创建日期:
	 * @param newApprover java.lang.String
	 */
	public void setApprover (java.lang.String newApprover ) {
	 	this.approver = newApprover;
	} 	  
	/**
	 * 属性approvedate的Getter方法.属性名：审核日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getApprovedate () {
		return approvedate;
	}   
	/**
	 * 属性approvedate的Setter方法.属性名：审核日期
	 * 创建日期:
	 * @param newApprovedate nc.vo.pub.lang.UFDateTime
	 */
	public void setApprovedate (nc.vo.pub.lang.UFDateTime newApprovedate ) {
	 	this.approvedate = newApprovedate;
	} 	  
	/**
	 * 属性formstate的Getter方法.属性名：单据状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormstate () {
		return formstate;
	}   
	/**
	 * 属性formstate的Setter方法.属性名：单据状态
	 * 创建日期:
	 * @param newFormstate java.lang.String
	 */
	public void setFormstate (java.lang.String newFormstate ) {
	 	this.formstate = newFormstate;
	} 	  
	/**
	 * 属性formtitle的Getter方法.属性名：单据标题
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormtitle () {
		return formtitle;
	}   
	/**
	 * 属性formtitle的Setter方法.属性名：单据标题
	 * 创建日期:
	 * @param newFormtitle java.lang.String
	 */
	public void setFormtitle (java.lang.String newFormtitle ) {
	 	this.formtitle = newFormtitle;
	} 	  
	/**
	 * 属性vrequestno的Getter方法.属性名：申请单号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVrequestno () {
		return vrequestno;
	}   
	/**
	 * 属性vrequestno的Setter方法.属性名：申请单号
	 * 创建日期:
	 * @param newVrequestno java.lang.String
	 */
	public void setVrequestno (java.lang.String newVrequestno ) {
	 	this.vrequestno = newVrequestno;
	} 	  
	/**
	 * 属性cprocesstype的Getter方法.属性名：审批流程类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCprocesstype () {
		return cprocesstype;
	}   
	/**
	 * 属性cprocesstype的Setter方法.属性名：审批流程类型
	 * 创建日期:
	 * @param newCprocesstype java.lang.String
	 */
	public void setCprocesstype (java.lang.String newCprocesstype ) {
	 	this.cprocesstype = newCprocesstype;
	} 	  
	/**
	 * 属性cchangetype的Getter方法.属性名：产权变动类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCchangetype () {
		return cchangetype;
	}   
	/**
	 * 属性cchangetype的Setter方法.属性名：产权变动类型
	 * 创建日期:
	 * @param newCchangetype java.lang.String
	 */
	public void setCchangetype (java.lang.String newCchangetype ) {
	 	this.cchangetype = newCchangetype;
	} 	  
	/**
	 * 属性ctradetype的Getter方法.属性名：产权交易方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCtradetype () {
		return ctradetype;
	}   
	/**
	 * 属性ctradetype的Setter方法.属性名：产权交易方式
	 * 创建日期:
	 * @param newCtradetype java.lang.String
	 */
	public void setCtradetype (java.lang.String newCtradetype ) {
	 	this.ctradetype = newCtradetype;
	} 	  
	/**
	 * 属性cgreattype的Getter方法.属性名：重大资产处置方式
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCgreattype () {
		return cgreattype;
	}   
	/**
	 * 属性cgreattype的Setter方法.属性名：重大资产处置方式
	 * 创建日期:
	 * @param newCgreattype java.lang.String
	 */
	public void setCgreattype (java.lang.String newCgreattype ) {
	 	this.cgreattype = newCgreattype;
	} 	  
	/**
	 * 属性pk_rorg的Getter方法.属性名：转让方
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_rorg () {
		return pk_rorg;
	}   
	/**
	 * 属性pk_rorg的Setter方法.属性名：转让方
	 * 创建日期:
	 * @param newPk_rorg java.lang.String
	 */
	public void setPk_rorg (java.lang.String newPk_rorg ) {
	 	this.pk_rorg = newPk_rorg;
	} 	  
	/**
	 * 属性vapproveno的Getter方法.属性名：批准文号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVapproveno () {
		return vapproveno;
	}   
	/**
	 * 属性vapproveno的Setter方法.属性名：批准文号
	 * 创建日期:
	 * @param newVapproveno java.lang.String
	 */
	public void setVapproveno (java.lang.String newVapproveno ) {
	 	this.vapproveno = newVapproveno;
	} 	  
	/**
	 * 属性capplicant的Getter方法.属性名：申请人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCapplicant () {
		return capplicant;
	}   
	/**
	 * 属性capplicant的Setter方法.属性名：申请人
	 * 创建日期:
	 * @param newCapplicant java.lang.String
	 */
	public void setCapplicant (java.lang.String newCapplicant ) {
	 	this.capplicant = newCapplicant;
	} 	  
	/**
	 * 属性capplicantdate的Getter方法.属性名：申请日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCapplicantdate () {
		return capplicantdate;
	}   
	/**
	 * 属性capplicantdate的Setter方法.属性名：申请日期
	 * 创建日期:
	 * @param newCapplicantdate nc.vo.pub.lang.UFDateTime
	 */
	public void setCapplicantdate (nc.vo.pub.lang.UFDateTime newCapplicantdate ) {
	 	this.capplicantdate = newCapplicantdate;
	} 	  
	/**
	 * 属性vdef1的Getter方法.属性名：自定义字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.属性名：自定义字段1
	 * 创建日期:
	 * @param newVdef1 java.lang.String
	 */
	public void setVdef1 (java.lang.String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef2的Getter方法.属性名：自定义字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.属性名：自定义字段2
	 * 创建日期:
	 * @param newVdef2 java.lang.String
	 */
	public void setVdef2 (java.lang.String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef3的Getter方法.属性名：自定义字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.属性名：自定义字段3
	 * 创建日期:
	 * @param newVdef3 java.lang.String
	 */
	public void setVdef3 (java.lang.String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef4的Getter方法.属性名：自定义字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.属性名：自定义字段4
	 * 创建日期:
	 * @param newVdef4 java.lang.String
	 */
	public void setVdef4 (java.lang.String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef5的Getter方法.属性名：自定义字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.属性名：自定义字段5
	 * 创建日期:
	 * @param newVdef5 java.lang.String
	 */
	public void setVdef5 (java.lang.String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef6的Getter方法.属性名：自定义字段6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.属性名：自定义字段6
	 * 创建日期:
	 * @param newVdef6 java.lang.String
	 */
	public void setVdef6 (java.lang.String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性vdef7的Getter方法.属性名：自定义字段7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.属性名：自定义字段7
	 * 创建日期:
	 * @param newVdef7 java.lang.String
	 */
	public void setVdef7 (java.lang.String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性vdef8的Getter方法.属性名：自定义字段8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.属性名：自定义字段8
	 * 创建日期:
	 * @param newVdef8 java.lang.String
	 */
	public void setVdef8 (java.lang.String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef9的Getter方法.属性名：自定义字段9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.属性名：自定义字段9
	 * 创建日期:
	 * @param newVdef9 java.lang.String
	 */
	public void setVdef9 (java.lang.String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef10的Getter方法.属性名：自定义字段10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.属性名：自定义字段10
	 * 创建日期:
	 * @param newVdef10 java.lang.String
	 */
	public void setVdef10 (java.lang.String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性id_scappt_apply_b的Getter方法.属性名：id_scappt_apply_b
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptApplyBVO[]
	 */
	public nc.scap.pt.vos.ScapptApplyBVO[] getId_scappt_apply_b () {
		return id_scappt_apply_b;
	}   
	/**
	 * 属性id_scappt_apply_b的Setter方法.属性名：id_scappt_apply_b
	 * 创建日期:
	 * @param newId_scappt_apply_b nc.scap.pt.vos.ScapptApplyBVO[]
	 */
	public void setId_scappt_apply_b (nc.scap.pt.vos.ScapptApplyBVO[] newId_scappt_apply_b ) {
	 	this.id_scappt_apply_b = newId_scappt_apply_b;
	} 	  
	/**
	 * 属性id_scappt_apply_attach的Getter方法.属性名：id_scappt_apply_attach
	 * 创建日期:
	 * @return nc.scap.pt.vos.ScapptApplyAttachVO[]
	 */
	public nc.scap.pt.vos.ScapptApplyAttachVO[] getId_scappt_apply_attach () {
		return id_scappt_apply_attach;
	}   
	/**
	 * 属性id_scappt_apply_attach的Setter方法.属性名：id_scappt_apply_attach
	 * 创建日期:
	 * @param newId_scappt_apply_attach nc.scap.pt.vos.ScapptApplyAttachVO[]
	 */
	public void setId_scappt_apply_attach (nc.scap.pt.vos.ScapptApplyAttachVO[] newId_scappt_apply_attach ) {
	 	this.id_scappt_apply_attach = newId_scappt_apply_attach;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_apply_h";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scappt_apply_h";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scappt_apply_h";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapptApplyHVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pt.vos.ScapptApplyHVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


