/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pub.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class AttachRoleVO extends SuperVO {
	private java.lang.String pk_attach_group;
	private java.lang.String pk_attach_role;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.Integer idx;
	private java.lang.Integer min_count;
	private java.lang.Integer max_count;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_ATTACH_GROUP = "pk_attach_group";
	public static final String PK_ATTACH_ROLE = "pk_attach_role";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String IDX = "idx";
	public static final String MIN_COUNT = "min_count";
	public static final String MAX_COUNT = "max_count";
			
	/**
	 * 属性pk_attach_group的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_attach_group () {
		return pk_attach_group;
	}   
	/**
	 * 属性pk_attach_group的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_attach_group java.lang.String
	 */
	public void setPk_attach_group (java.lang.String newPk_attach_group ) {
	 	this.pk_attach_group = newPk_attach_group;
	} 	  
	/**
	 * 属性pk_attach_role的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_attach_role () {
		return pk_attach_role;
	}   
	/**
	 * 属性pk_attach_role的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_attach_role java.lang.String
	 */
	public void setPk_attach_role (java.lang.String newPk_attach_role ) {
	 	this.pk_attach_role = newPk_attach_role;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：名称
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性idx的Getter方法.属性名：排序
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIdx () {
		return idx;
	}   
	/**
	 * 属性idx的Setter方法.属性名：排序
	 * 创建日期:
	 * @param newIdx java.lang.Integer
	 */
	public void setIdx (java.lang.Integer newIdx ) {
	 	this.idx = newIdx;
	} 	  
	/**
	 * 属性min_count的Getter方法.属性名：最少文件数量
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getMin_count () {
		return min_count;
	}   
	/**
	 * 属性min_count的Setter方法.属性名：最少文件数量
	 * 创建日期:
	 * @param newMin_count java.lang.Integer
	 */
	public void setMin_count (java.lang.Integer newMin_count ) {
	 	this.min_count = newMin_count;
	} 	  
	/**
	 * 属性max_count的Getter方法.属性名：最大文件数量
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getMax_count () {
		return max_count;
	}   
	/**
	 * 属性max_count的Setter方法.属性名：最大文件数量
	 * 创建日期:
	 * @param newMax_count java.lang.Integer
	 */
	public void setMax_count (java.lang.Integer newMax_count ) {
	 	this.max_count = newMax_count;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_attach_group";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_attach_role";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scap_attach_role";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scap_attach_role";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public AttachRoleVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pub.vos.AttachRoleVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


