
package com.sursen.interfaces.filelist.service;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IFilelistService", targetNamespace = "http://service.filelist.interfaces.sursen.com")
public class IFilelistService extends Service {

    public IFilelistService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFilelistService(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://service.filelist.interfaces.sursen.com", "IFilelistService"));
    }

    /**
     * 
     * @return
     *     returns IFilelistServicePortType
     */
    @WebEndpoint(name = "IFilelistServiceHttpPort")
    public IFilelistServicePortType getIFilelistServiceHttpPort() {
        return super.getPort(new QName("http://service.filelist.interfaces.sursen.com", "IFilelistServiceHttpPort"), IFilelistServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFilelistServicePortType
     */
    @WebEndpoint(name = "IFilelistServiceHttpPort")
    public IFilelistServicePortType getIFilelistServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.filelist.interfaces.sursen.com", "IFilelistServiceHttpPort"), IFilelistServicePortType.class, features);
    }

}
