/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pub.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapChartDsVO extends SuperVO {
	private java.lang.String pk_chart_ds;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String controller;
	private java.lang.String table_name;
	private java.lang.String source_sql;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_CHART_DS = "pk_chart_ds";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String CONTROLLER = "controller";
	public static final String TABLE_NAME = "table_name";
	public static final String SOURCE_SQL = "source_sql";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
			
	/**
	 * 属性pk_chart_ds的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_chart_ds () {
		return pk_chart_ds;
	}   
	/**
	 * 属性pk_chart_ds的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_chart_ds java.lang.String
	 */
	public void setPk_chart_ds (java.lang.String newPk_chart_ds ) {
	 	this.pk_chart_ds = newPk_chart_ds;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：名称
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性controller的Getter方法.属性名：控制类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getController () {
		return controller;
	}   
	/**
	 * 属性controller的Setter方法.属性名：控制类
	 * 创建日期:
	 * @param newController java.lang.String
	 */
	public void setController (java.lang.String newController ) {
	 	this.controller = newController;
	} 	  
	/**
	 * 属性table_name的Getter方法.属性名：来源表名
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTable_name () {
		return table_name;
	}   
	/**
	 * 属性table_name的Setter方法.属性名：来源表名
	 * 创建日期:
	 * @param newTable_name java.lang.String
	 */
	public void setTable_name (java.lang.String newTable_name ) {
	 	this.table_name = newTable_name;
	} 	  
	/**
	 * 属性source_sql的Getter方法.属性名：来源SQL
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSource_sql () {
		return source_sql;
	}   
	/**
	 * 属性source_sql的Setter方法.属性名：来源SQL
	 * 创建日期:
	 * @param newSource_sql java.lang.String
	 */
	public void setSource_sql (java.lang.String newSource_sql ) {
	 	this.source_sql = newSource_sql;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_chart_ds";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scap_chart_ds";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scap_chart_ds";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapChartDsVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pub.vos.ScapChartDsVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


