/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pub.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapMoSmsVO extends SuperVO {
	private java.lang.String pk_sms;
	private java.lang.String pk_ext;
	private java.lang.String address;
	private java.lang.String content;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_SMS = "pk_sms";
	public static final String PK_EXT = "pk_ext";
	public static final String ADDRESS = "address";
	public static final String CONTENT = "content";
			
	/**
	 * 属性pk_sms的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_sms () {
		return pk_sms;
	}   
	/**
	 * 属性pk_sms的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_sms java.lang.String
	 */
	public void setPk_sms (java.lang.String newPk_sms ) {
	 	this.pk_sms = newPk_sms;
	} 	  
	/**
	 * 属性pk_ext的Getter方法.属性名：外部扩展主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_ext () {
		return pk_ext;
	}   
	/**
	 * 属性pk_ext的Setter方法.属性名：外部扩展主键
	 * 创建日期:
	 * @param newPk_ext java.lang.String
	 */
	public void setPk_ext (java.lang.String newPk_ext ) {
	 	this.pk_ext = newPk_ext;
	} 	  
	/**
	 * 属性address的Getter方法.属性名：手机号码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAddress () {
		return address;
	}   
	/**
	 * 属性address的Setter方法.属性名：手机号码
	 * 创建日期:
	 * @param newAddress java.lang.String
	 */
	public void setAddress (java.lang.String newAddress ) {
	 	this.address = newAddress;
	} 	  
	/**
	 * 属性content的Getter方法.属性名：内容
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getContent () {
		return content;
	}   
	/**
	 * 属性content的Setter方法.属性名：内容
	 * 创建日期:
	 * @param newContent java.lang.String
	 */
	public void setContent (java.lang.String newContent ) {
	 	this.content = newContent;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_sms";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_sms_mo";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_sms_mo";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapMoSmsVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pub.vos.ScapMoSmsVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


