/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pub.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapUserChoiceVO extends SuperVO {
	private java.lang.String pk_choice_person;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String type;
	private java.lang.String remark;
	private java.lang.String pk_user;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.scap.pub.vos.ScapUserChoiceBVO[] pk_choice_b;

	public static final String PK_CHOICE_PERSON = "pk_choice_person";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String TYPE = "type";
	public static final String REMARK = "remark";
	public static final String PK_USER = "pk_user";
			
	/**
	 * 属性pk_choice_person的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_choice_person () {
		return pk_choice_person;
	}   
	/**
	 * 属性pk_choice_person的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_choice_person java.lang.String
	 */
	public void setPk_choice_person (java.lang.String newPk_choice_person ) {
	 	this.pk_choice_person = newPk_choice_person;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：名称
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性type的Getter方法.属性名：类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.属性名：类型
	 * 创建日期:
	 * @param newType java.lang.String
	 */
	public void setType (java.lang.String newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性remark的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newRemark java.lang.String
	 */
	public void setRemark (java.lang.String newRemark ) {
	 	this.remark = newRemark;
	} 	  
	/**
	 * 属性pk_choice_b的Getter方法.属性名：主表主键
	 * 创建日期:
	 * @return nc.scap.pub.vos.ScapUserChoiceBVO[]
	 */
	public nc.scap.pub.vos.ScapUserChoiceBVO[] getPk_choice_b () {
		return pk_choice_b;
	}   
	/**
	 * 属性pk_choice_b的Setter方法.属性名：主表主键
	 * 创建日期:
	 * @param newPk_choice_b nc.scap.pub.vos.ScapUserChoiceBVO[]
	 */
	public void setPk_choice_b (nc.scap.pub.vos.ScapUserChoiceBVO[] newPk_choice_b ) {
	 	this.pk_choice_b = newPk_choice_b;
	} 	  
	/**
	 * 属性pk_user的Getter方法.属性名：用户
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_user () {
		return pk_user;
	}   
	/**
	 * 属性pk_user的Setter方法.属性名：用户
	 * 创建日期:
	 * @param newPk_user java.lang.String
	 */
	public void setPk_user (java.lang.String newPk_user ) {
	 	this.pk_user = newPk_user;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_choice_person";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_userchoice";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_userchoice";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapUserChoiceVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pub.vos.ScapUserChoiceVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


