/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pub.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ScapMeetingUserVO extends SuperVO {
	private java.lang.String pk_meetingreport;
	private java.lang.String pk_meetinguser;
	private java.lang.String username;
	private java.lang.Integer gender;
	private java.lang.String nation;
	private java.lang.String usergroup;
	private java.lang.String duty;
	private java.lang.String tel;
	private java.lang.String memo;
	private java.lang.String vbdef1;
	private java.lang.String vbdef2;
	private java.lang.String vbdef3;
	private java.lang.String vbdef4;
	private java.lang.String vbdef5;
	private nc.vo.pub.lang.UFDateTime vbdef6;
	private nc.vo.pub.lang.UFBoolean vbdef7;
	private java.lang.Integer vbdef8;
	private nc.vo.pub.lang.UFDouble vbdef9;
	private nc.vo.pub.lang.UFDouble vbdef10;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_MEETINGREPORT = "pk_meetingreport";
	public static final String PK_MEETINGUSER = "pk_meetinguser";
	public static final String USERNAME = "username";
	public static final String GENDER = "gender";
	public static final String NATION = "nation";
	public static final String USERGROUP = "usergroup";
	public static final String DUTY = "duty";
	public static final String TEL = "tel";
	public static final String MEMO = "memo";
	public static final String VBDEF1 = "vbdef1";
	public static final String VBDEF2 = "vbdef2";
	public static final String VBDEF3 = "vbdef3";
	public static final String VBDEF4 = "vbdef4";
	public static final String VBDEF5 = "vbdef5";
	public static final String VBDEF6 = "vbdef6";
	public static final String VBDEF7 = "vbdef7";
	public static final String VBDEF8 = "vbdef8";
	public static final String VBDEF9 = "vbdef9";
	public static final String VBDEF10 = "vbdef10";
			
	/**
	 * 属性pk_meetingreport的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_meetingreport () {
		return pk_meetingreport;
	}   
	/**
	 * 属性pk_meetingreport的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_meetingreport java.lang.String
	 */
	public void setPk_meetingreport (java.lang.String newPk_meetingreport ) {
	 	this.pk_meetingreport = newPk_meetingreport;
	} 	  
	/**
	 * 属性pk_meetinguser的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_meetinguser () {
		return pk_meetinguser;
	}   
	/**
	 * 属性pk_meetinguser的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_meetinguser java.lang.String
	 */
	public void setPk_meetinguser (java.lang.String newPk_meetinguser ) {
	 	this.pk_meetinguser = newPk_meetinguser;
	} 	  
	/**
	 * 属性username的Getter方法.属性名：姓名
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUsername () {
		return username;
	}   
	/**
	 * 属性username的Setter方法.属性名：姓名
	 * 创建日期:
	 * @param newUsername java.lang.String
	 */
	public void setUsername (java.lang.String newUsername ) {
	 	this.username = newUsername;
	} 	  
	/**
	 * 属性gender的Getter方法.属性名：性别
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getGender () {
		return gender;
	}   
	/**
	 * 属性gender的Setter方法.属性名：性别
	 * 创建日期:
	 * @param newGender java.lang.Integer
	 */
	public void setGender (java.lang.Integer newGender ) {
	 	this.gender = newGender;
	} 	  
	/**
	 * 属性nation的Getter方法.属性名：民族
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNation () {
		return nation;
	}   
	/**
	 * 属性nation的Setter方法.属性名：民族
	 * 创建日期:
	 * @param newNation java.lang.String
	 */
	public void setNation (java.lang.String newNation ) {
	 	this.nation = newNation;
	} 	  
	/**
	 * 属性usergroup的Getter方法.属性名：所在单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUsergroup () {
		return usergroup;
	}   
	/**
	 * 属性usergroup的Setter方法.属性名：所在单位
	 * 创建日期:
	 * @param newUsergroup java.lang.String
	 */
	public void setUsergroup (java.lang.String newUsergroup ) {
	 	this.usergroup = newUsergroup;
	} 	  
	/**
	 * 属性duty的Getter方法.属性名：职务
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDuty () {
		return duty;
	}   
	/**
	 * 属性duty的Setter方法.属性名：职务
	 * 创建日期:
	 * @param newDuty java.lang.String
	 */
	public void setDuty (java.lang.String newDuty ) {
	 	this.duty = newDuty;
	} 	  
	/**
	 * 属性tel的Getter方法.属性名：电话
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTel () {
		return tel;
	}   
	/**
	 * 属性tel的Setter方法.属性名：电话
	 * 创建日期:
	 * @param newTel java.lang.String
	 */
	public void setTel (java.lang.String newTel ) {
	 	this.tel = newTel;
	} 	  
	/**
	 * 属性memo的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newMemo java.lang.String
	 */
	public void setMemo (java.lang.String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性vbdef1的Getter方法.属性名：自定义项1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbdef1 () {
		return vbdef1;
	}   
	/**
	 * 属性vbdef1的Setter方法.属性名：自定义项1
	 * 创建日期:
	 * @param newVbdef1 java.lang.String
	 */
	public void setVbdef1 (java.lang.String newVbdef1 ) {
	 	this.vbdef1 = newVbdef1;
	} 	  
	/**
	 * 属性vbdef2的Getter方法.属性名：自定义项2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbdef2 () {
		return vbdef2;
	}   
	/**
	 * 属性vbdef2的Setter方法.属性名：自定义项2
	 * 创建日期:
	 * @param newVbdef2 java.lang.String
	 */
	public void setVbdef2 (java.lang.String newVbdef2 ) {
	 	this.vbdef2 = newVbdef2;
	} 	  
	/**
	 * 属性vbdef3的Getter方法.属性名：自定义项3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbdef3 () {
		return vbdef3;
	}   
	/**
	 * 属性vbdef3的Setter方法.属性名：自定义项3
	 * 创建日期:
	 * @param newVbdef3 java.lang.String
	 */
	public void setVbdef3 (java.lang.String newVbdef3 ) {
	 	this.vbdef3 = newVbdef3;
	} 	  
	/**
	 * 属性vbdef4的Getter方法.属性名：自定义项4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbdef4 () {
		return vbdef4;
	}   
	/**
	 * 属性vbdef4的Setter方法.属性名：自定义项4
	 * 创建日期:
	 * @param newVbdef4 java.lang.String
	 */
	public void setVbdef4 (java.lang.String newVbdef4 ) {
	 	this.vbdef4 = newVbdef4;
	} 	  
	/**
	 * 属性vbdef5的Getter方法.属性名：自定义项5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbdef5 () {
		return vbdef5;
	}   
	/**
	 * 属性vbdef5的Setter方法.属性名：自定义项5
	 * 创建日期:
	 * @param newVbdef5 java.lang.String
	 */
	public void setVbdef5 (java.lang.String newVbdef5 ) {
	 	this.vbdef5 = newVbdef5;
	} 	  
	/**
	 * 属性vbdef6的Getter方法.属性名：自定义项6
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getVbdef6 () {
		return vbdef6;
	}   
	/**
	 * 属性vbdef6的Setter方法.属性名：自定义项6
	 * 创建日期:
	 * @param newVbdef6 nc.vo.pub.lang.UFDateTime
	 */
	public void setVbdef6 (nc.vo.pub.lang.UFDateTime newVbdef6 ) {
	 	this.vbdef6 = newVbdef6;
	} 	  
	/**
	 * 属性vbdef7的Getter方法.属性名：自定义项7
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getVbdef7 () {
		return vbdef7;
	}   
	/**
	 * 属性vbdef7的Setter方法.属性名：自定义项7
	 * 创建日期:
	 * @param newVbdef7 nc.vo.pub.lang.UFBoolean
	 */
	public void setVbdef7 (nc.vo.pub.lang.UFBoolean newVbdef7 ) {
	 	this.vbdef7 = newVbdef7;
	} 	  
	/**
	 * 属性vbdef8的Getter方法.属性名：自定义项8
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getVbdef8 () {
		return vbdef8;
	}   
	/**
	 * 属性vbdef8的Setter方法.属性名：自定义项8
	 * 创建日期:
	 * @param newVbdef8 java.lang.Integer
	 */
	public void setVbdef8 (java.lang.Integer newVbdef8 ) {
	 	this.vbdef8 = newVbdef8;
	} 	  
	/**
	 * 属性vbdef9的Getter方法.属性名：自定义项9
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVbdef9 () {
		return vbdef9;
	}   
	/**
	 * 属性vbdef9的Setter方法.属性名：自定义项9
	 * 创建日期:
	 * @param newVbdef9 nc.vo.pub.lang.UFDouble
	 */
	public void setVbdef9 (nc.vo.pub.lang.UFDouble newVbdef9 ) {
	 	this.vbdef9 = newVbdef9;
	} 	  
	/**
	 * 属性vbdef10的Getter方法.属性名：自定义项10
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVbdef10 () {
		return vbdef10;
	}   
	/**
	 * 属性vbdef10的Setter方法.属性名：自定义项10
	 * 创建日期:
	 * @param newVbdef10 nc.vo.pub.lang.UFDouble
	 */
	public void setVbdef10 (nc.vo.pub.lang.UFDouble newVbdef10 ) {
	 	this.vbdef10 = newVbdef10;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_meetingreport";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_meetinguser";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_meetinguser";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_meetinguser";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ScapMeetingUserVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pub.vos.ScapMeetingUserVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


