/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.scap.pub.vos;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WorkReportVO extends SuperVO {
	private java.lang.String pk_workreport;
	private java.lang.String pk_notice;
	private java.lang.String year;
	private java.lang.String month;
	private java.lang.String business_type;
	private java.lang.String report_type;
	private java.lang.String report_title;
	private java.lang.String report_content;
	private java.lang.String pk_org;
	private java.lang.String pk_org_all;
	private java.lang.String input_user;
	private nc.vo.pub.lang.UFDateTime input_date;
	private nc.vo.pub.lang.UFDateTime submit_date;
	private java.lang.String phone;
	private java.lang.String mobile;
	private java.lang.String memo;
	private java.lang.String state;
	private java.lang.Integer enablestate;
	private java.lang.String approver;
	private nc.vo.pub.lang.UFDate approve_date;
	private java.lang.String approve_opinion;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String handle_state;
	private java.lang.String pk_parent;
	private java.lang.String pk_group;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.Integer defint11;
	private java.lang.Integer defint12;
	private java.lang.Integer defint13;
	private java.lang.Integer defint14;
	private java.lang.Integer defint15;
	private nc.vo.pub.lang.UFDouble defnum16;
	private nc.vo.pub.lang.UFDouble defnum17;
	private nc.vo.pub.lang.UFDouble defnum18;
	private nc.vo.pub.lang.UFDouble defnum19;
	private nc.vo.pub.lang.UFDouble defnum20;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_WORKREPORT = "pk_workreport";
	public static final String PK_NOTICE = "pk_notice";
	public static final String YEAR = "year";
	public static final String MONTH = "month";
	public static final String BUSINESS_TYPE = "business_type";
	public static final String REPORT_TYPE = "report_type";
	public static final String REPORT_TITLE = "report_title";
	public static final String REPORT_CONTENT = "report_content";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_ALL = "pk_org_all";
	public static final String INPUT_USER = "input_user";
	public static final String INPUT_DATE = "input_date";
	public static final String SUBMIT_DATE = "submit_date";
	public static final String PHONE = "phone";
	public static final String MOBILE = "mobile";
	public static final String MEMO = "memo";
	public static final String STATE = "state";
	public static final String ENABLESTATE = "enablestate";
	public static final String APPROVER = "approver";
	public static final String APPROVE_DATE = "approve_date";
	public static final String APPROVE_OPINION = "approve_opinion";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String HANDLE_STATE = "handle_state";
	public static final String PK_PARENT = "pk_parent";
	public static final String PK_GROUP = "pk_group";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEFINT11 = "defint11";
	public static final String DEFINT12 = "defint12";
	public static final String DEFINT13 = "defint13";
	public static final String DEFINT14 = "defint14";
	public static final String DEFINT15 = "defint15";
	public static final String DEFNUM16 = "defnum16";
	public static final String DEFNUM17 = "defnum17";
	public static final String DEFNUM18 = "defnum18";
	public static final String DEFNUM19 = "defnum19";
	public static final String DEFNUM20 = "defnum20";
			
	/**
	 * 属性pk_workreport的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_workreport () {
		return pk_workreport;
	}   
	/**
	 * 属性pk_workreport的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_workreport java.lang.String
	 */
	public void setPk_workreport (java.lang.String newPk_workreport ) {
	 	this.pk_workreport = newPk_workreport;
	} 	  
	/**
	 * 属性pk_notice的Getter方法.属性名：通知
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_notice () {
		return pk_notice;
	}   
	/**
	 * 属性pk_notice的Setter方法.属性名：通知
	 * 创建日期:
	 * @param newPk_notice java.lang.String
	 */
	public void setPk_notice (java.lang.String newPk_notice ) {
	 	this.pk_notice = newPk_notice;
	} 	  
	/**
	 * 属性year的Getter方法.属性名：年度
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getYear () {
		return year;
	}   
	/**
	 * 属性year的Setter方法.属性名：年度
	 * 创建日期:
	 * @param newYear java.lang.String
	 */
	public void setYear (java.lang.String newYear ) {
	 	this.year = newYear;
	} 	  
	/**
	 * 属性month的Getter方法.属性名：月度
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMonth () {
		return month;
	}   
	/**
	 * 属性month的Setter方法.属性名：月度
	 * 创建日期:
	 * @param newMonth java.lang.String
	 */
	public void setMonth (java.lang.String newMonth ) {
	 	this.month = newMonth;
	} 	  
	/**
	 * 属性business_type的Getter方法.属性名：业务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusiness_type () {
		return business_type;
	}   
	/**
	 * 属性business_type的Setter方法.属性名：业务类型
	 * 创建日期:
	 * @param newBusiness_type java.lang.String
	 */
	public void setBusiness_type (java.lang.String newBusiness_type ) {
	 	this.business_type = newBusiness_type;
	} 	  
	/**
	 * 属性report_type的Getter方法.属性名：报告类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_type () {
		return report_type;
	}   
	/**
	 * 属性report_type的Setter方法.属性名：报告类型
	 * 创建日期:
	 * @param newReport_type java.lang.String
	 */
	public void setReport_type (java.lang.String newReport_type ) {
	 	this.report_type = newReport_type;
	} 	  
	/**
	 * 属性report_title的Getter方法.属性名：主题
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_title () {
		return report_title;
	}   
	/**
	 * 属性report_title的Setter方法.属性名：主题
	 * 创建日期:
	 * @param newReport_title java.lang.String
	 */
	public void setReport_title (java.lang.String newReport_title ) {
	 	this.report_title = newReport_title;
	} 	  
	/**
	 * 属性report_content的Getter方法.属性名：主要内容
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_content () {
		return report_content;
	}   
	/**
	 * 属性report_content的Setter方法.属性名：主要内容
	 * 创建日期:
	 * @param newReport_content java.lang.String
	 */
	public void setReport_content (java.lang.String newReport_content ) {
	 	this.report_content = newReport_content;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：填报单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：填报单位
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_org_all的Getter方法.属性名：填报单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_all () {
		return pk_org_all;
	}   
	/**
	 * 属性pk_org_all的Setter方法.属性名：填报单位
	 * 创建日期:
	 * @param newPk_org_all java.lang.String
	 */
	public void setPk_org_all (java.lang.String newPk_org_all ) {
	 	this.pk_org_all = newPk_org_all;
	} 	  
	/**
	 * 属性input_user的Getter方法.属性名：填报人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getInput_user () {
		return input_user;
	}   
	/**
	 * 属性input_user的Setter方法.属性名：填报人
	 * 创建日期:
	 * @param newInput_user java.lang.String
	 */
	public void setInput_user (java.lang.String newInput_user ) {
	 	this.input_user = newInput_user;
	} 	  
	/**
	 * 属性input_date的Getter方法.属性名：填报时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getInput_date () {
		return input_date;
	}   
	/**
	 * 属性input_date的Setter方法.属性名：填报时间
	 * 创建日期:
	 * @param newInput_date nc.vo.pub.lang.UFDateTime
	 */
	public void setInput_date (nc.vo.pub.lang.UFDateTime newInput_date ) {
	 	this.input_date = newInput_date;
	} 	  
	/**
	 * 属性submit_date的Getter方法.属性名：提交时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getSubmit_date () {
		return submit_date;
	}   
	/**
	 * 属性submit_date的Setter方法.属性名：提交时间
	 * 创建日期:
	 * @param newSubmit_date nc.vo.pub.lang.UFDateTime
	 */
	public void setSubmit_date (nc.vo.pub.lang.UFDateTime newSubmit_date ) {
	 	this.submit_date = newSubmit_date;
	} 	  
	/**
	 * 属性phone的Getter方法.属性名：办公电话
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPhone () {
		return phone;
	}   
	/**
	 * 属性phone的Setter方法.属性名：办公电话
	 * 创建日期:
	 * @param newPhone java.lang.String
	 */
	public void setPhone (java.lang.String newPhone ) {
	 	this.phone = newPhone;
	} 	  
	/**
	 * 属性mobile的Getter方法.属性名：手机
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMobile () {
		return mobile;
	}   
	/**
	 * 属性mobile的Setter方法.属性名：手机
	 * 创建日期:
	 * @param newMobile java.lang.String
	 */
	public void setMobile (java.lang.String newMobile ) {
	 	this.mobile = newMobile;
	} 	  
	/**
	 * 属性memo的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newMemo java.lang.String
	 */
	public void setMemo (java.lang.String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性state的Getter方法.属性名：填报状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getState () {
		return state;
	}   
	/**
	 * 属性state的Setter方法.属性名：填报状态
	 * 创建日期:
	 * @param newState java.lang.String
	 */
	public void setState (java.lang.String newState ) {
	 	this.state = newState;
	} 	  
	/**
	 * 属性enablestate的Getter方法.属性名：是否启用
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEnablestate () {
		return enablestate;
	}   
	/**
	 * 属性enablestate的Setter方法.属性名：是否启用
	 * 创建日期:
	 * @param newEnablestate java.lang.Integer
	 */
	public void setEnablestate (java.lang.Integer newEnablestate ) {
	 	this.enablestate = newEnablestate;
	} 	  
	/**
	 * 属性approver的Getter方法.属性名：审核人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprover () {
		return approver;
	}   
	/**
	 * 属性approver的Setter方法.属性名：审核人
	 * 创建日期:
	 * @param newApprover java.lang.String
	 */
	public void setApprover (java.lang.String newApprover ) {
	 	this.approver = newApprover;
	} 	  
	/**
	 * 属性approve_date的Getter方法.属性名：审核日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getApprove_date () {
		return approve_date;
	}   
	/**
	 * 属性approve_date的Setter方法.属性名：审核日期
	 * 创建日期:
	 * @param newApprove_date nc.vo.pub.lang.UFDate
	 */
	public void setApprove_date (nc.vo.pub.lang.UFDate newApprove_date ) {
	 	this.approve_date = newApprove_date;
	} 	  
	/**
	 * 属性approve_opinion的Getter方法.属性名：审核意见
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getApprove_opinion () {
		return approve_opinion;
	}   
	/**
	 * 属性approve_opinion的Setter方法.属性名：审核意见
	 * 创建日期:
	 * @param newApprove_opinion java.lang.String
	 */
	public void setApprove_opinion (java.lang.String newApprove_opinion ) {
	 	this.approve_opinion = newApprove_opinion;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性handle_state的Getter方法.属性名：办理情况
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getHandle_state () {
		return handle_state;
	}   
	/**
	 * 属性handle_state的Setter方法.属性名：办理情况
	 * 创建日期:
	 * @param newHandle_state java.lang.String
	 */
	public void setHandle_state (java.lang.String newHandle_state ) {
	 	this.handle_state = newHandle_state;
	} 	  
	/**
	 * 属性pk_parent的Getter方法.属性名：父PK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parent () {
		return pk_parent;
	}   
	/**
	 * 属性pk_parent的Setter方法.属性名：父PK
	 * 创建日期:
	 * @param newPk_parent java.lang.String
	 */
	public void setPk_parent (java.lang.String newPk_parent ) {
	 	this.pk_parent = newPk_parent;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：预留列1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：预留列1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：预留列2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：预留列2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：预留列3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：预留列3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：预留列4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：预留列4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：预留列5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：预留列5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：预留列6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：预留列6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：预留列7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：预留列7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：预留列8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：预留列8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：预留列9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：预留列9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：预留列10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：预留列10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性defint11的Getter方法.属性名：预留整数列11
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDefint11 () {
		return defint11;
	}   
	/**
	 * 属性defint11的Setter方法.属性名：预留整数列11
	 * 创建日期:
	 * @param newDefint11 java.lang.Integer
	 */
	public void setDefint11 (java.lang.Integer newDefint11 ) {
	 	this.defint11 = newDefint11;
	} 	  
	/**
	 * 属性defint12的Getter方法.属性名：预留整数列12
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDefint12 () {
		return defint12;
	}   
	/**
	 * 属性defint12的Setter方法.属性名：预留整数列12
	 * 创建日期:
	 * @param newDefint12 java.lang.Integer
	 */
	public void setDefint12 (java.lang.Integer newDefint12 ) {
	 	this.defint12 = newDefint12;
	} 	  
	/**
	 * 属性defint13的Getter方法.属性名：预留整数列13
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDefint13 () {
		return defint13;
	}   
	/**
	 * 属性defint13的Setter方法.属性名：预留整数列13
	 * 创建日期:
	 * @param newDefint13 java.lang.Integer
	 */
	public void setDefint13 (java.lang.Integer newDefint13 ) {
	 	this.defint13 = newDefint13;
	} 	  
	/**
	 * 属性defint14的Getter方法.属性名：预留整数列14
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDefint14 () {
		return defint14;
	}   
	/**
	 * 属性defint14的Setter方法.属性名：预留整数列14
	 * 创建日期:
	 * @param newDefint14 java.lang.Integer
	 */
	public void setDefint14 (java.lang.Integer newDefint14 ) {
	 	this.defint14 = newDefint14;
	} 	  
	/**
	 * 属性defint15的Getter方法.属性名：预留整数列15
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDefint15 () {
		return defint15;
	}   
	/**
	 * 属性defint15的Setter方法.属性名：预留整数列15
	 * 创建日期:
	 * @param newDefint15 java.lang.Integer
	 */
	public void setDefint15 (java.lang.Integer newDefint15 ) {
	 	this.defint15 = newDefint15;
	} 	  
	/**
	 * 属性defnum16的Getter方法.属性名：预留浮点列16
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDefnum16 () {
		return defnum16;
	}   
	/**
	 * 属性defnum16的Setter方法.属性名：预留浮点列16
	 * 创建日期:
	 * @param newDefnum16 nc.vo.pub.lang.UFDouble
	 */
	public void setDefnum16 (nc.vo.pub.lang.UFDouble newDefnum16 ) {
	 	this.defnum16 = newDefnum16;
	} 	  
	/**
	 * 属性defnum17的Getter方法.属性名：预留浮点列17
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDefnum17 () {
		return defnum17;
	}   
	/**
	 * 属性defnum17的Setter方法.属性名：预留浮点列17
	 * 创建日期:
	 * @param newDefnum17 nc.vo.pub.lang.UFDouble
	 */
	public void setDefnum17 (nc.vo.pub.lang.UFDouble newDefnum17 ) {
	 	this.defnum17 = newDefnum17;
	} 	  
	/**
	 * 属性defnum18的Getter方法.属性名：预留浮点列18
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDefnum18 () {
		return defnum18;
	}   
	/**
	 * 属性defnum18的Setter方法.属性名：预留浮点列18
	 * 创建日期:
	 * @param newDefnum18 nc.vo.pub.lang.UFDouble
	 */
	public void setDefnum18 (nc.vo.pub.lang.UFDouble newDefnum18 ) {
	 	this.defnum18 = newDefnum18;
	} 	  
	/**
	 * 属性defnum19的Getter方法.属性名：预留浮点列19
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDefnum19 () {
		return defnum19;
	}   
	/**
	 * 属性defnum19的Setter方法.属性名：预留浮点列19
	 * 创建日期:
	 * @param newDefnum19 nc.vo.pub.lang.UFDouble
	 */
	public void setDefnum19 (nc.vo.pub.lang.UFDouble newDefnum19 ) {
	 	this.defnum19 = newDefnum19;
	} 	  
	/**
	 * 属性defnum20的Getter方法.属性名：预留浮点列20
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDefnum20 () {
		return defnum20;
	}   
	/**
	 * 属性defnum20的Setter方法.属性名：预留浮点列20
	 * 创建日期:
	 * @param newDefnum20 nc.vo.pub.lang.UFDouble
	 */
	public void setDefnum20 (nc.vo.pub.lang.UFDouble newDefnum20 ) {
	 	this.defnum20 = newDefnum20;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_workreport";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_workreport";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_workreport";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WorkReportVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.scap.pub.vos.WorkReportVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


