/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.scapco.pub_visualorganization;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class visualOrganization extends SuperVO {
	private java.lang.String pk_visualorg;
	private java.lang.String pk_parent;
	private java.lang.String parent_name;
	private java.lang.String visualorg_name;
	private java.lang.String visualorg_code;
	private java.lang.String visualorg_type;
	private java.lang.Integer enablestate;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String report_psn;
	private java.lang.String report_org;
	private nc.vo.pub.lang.UFDate report_date;
	private java.lang.String remark;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.vo.scapco.pub_visualorganization.visualUserInfo[] id_visualuserinfo;

	public static final String PK_VISUALORG = "pk_visualorg";
	public static final String PK_PARENT = "pk_parent";
	public static final String PARENT_NAME = "parent_name";
	public static final String VISUALORG_NAME = "visualorg_name";
	public static final String VISUALORG_CODE = "visualorg_code";
	public static final String VISUALORG_TYPE = "visualorg_type";
	public static final String ENABLESTATE = "enablestate";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String REPORT_PSN = "report_psn";
	public static final String REPORT_ORG = "report_org";
	public static final String REPORT_DATE = "report_date";
	public static final String REMARK = "remark";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
			
	/**
	 * 属性pk_visualorg的Getter方法.属性名：组织主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_visualorg () {
		return pk_visualorg;
	}   
	/**
	 * 属性pk_visualorg的Setter方法.属性名：组织主键
	 * 创建日期:
	 * @param newPk_visualorg java.lang.String
	 */
	public void setPk_visualorg (java.lang.String newPk_visualorg ) {
	 	this.pk_visualorg = newPk_visualorg;
	} 	  
	/**
	 * 属性pk_parent的Getter方法.属性名：上级组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parent () {
		return pk_parent;
	}   
	/**
	 * 属性pk_parent的Setter方法.属性名：上级组织
	 * 创建日期:
	 * @param newPk_parent java.lang.String
	 */
	public void setPk_parent (java.lang.String newPk_parent ) {
	 	this.pk_parent = newPk_parent;
	} 	  
	/**
	 * 属性parent_name的Getter方法.属性名：上级组织名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getParent_name () {
		return parent_name;
	}   
	/**
	 * 属性parent_name的Setter方法.属性名：上级组织名称
	 * 创建日期:
	 * @param newParent_name java.lang.String
	 */
	public void setParent_name (java.lang.String newParent_name ) {
	 	this.parent_name = newParent_name;
	} 	  
	/**
	 * 属性visualorg_name的Getter方法.属性名：组织名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVisualorg_name () {
		return visualorg_name;
	}   
	/**
	 * 属性visualorg_name的Setter方法.属性名：组织名称
	 * 创建日期:
	 * @param newVisualorg_name java.lang.String
	 */
	public void setVisualorg_name (java.lang.String newVisualorg_name ) {
	 	this.visualorg_name = newVisualorg_name;
	} 	  
	/**
	 * 属性visualorg_code的Getter方法.属性名：组织编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVisualorg_code () {
		return visualorg_code;
	}   
	/**
	 * 属性visualorg_code的Setter方法.属性名：组织编码
	 * 创建日期:
	 * @param newVisualorg_code java.lang.String
	 */
	public void setVisualorg_code (java.lang.String newVisualorg_code ) {
	 	this.visualorg_code = newVisualorg_code;
	} 	  
	/**
	 * 属性visualorg_type的Getter方法.属性名：组织类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVisualorg_type () {
		return visualorg_type;
	}   
	/**
	 * 属性visualorg_type的Setter方法.属性名：组织类型
	 * 创建日期:
	 * @param newVisualorg_type java.lang.String
	 */
	public void setVisualorg_type (java.lang.String newVisualorg_type ) {
	 	this.visualorg_type = newVisualorg_type;
	} 	  
	/**
	 * 属性enablestate的Getter方法.属性名：是否启用
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEnablestate () {
		return enablestate;
	}   
	/**
	 * 属性enablestate的Setter方法.属性名：是否启用
	 * 创建日期:
	 * @param newEnablestate java.lang.Integer
	 */
	public void setEnablestate (java.lang.Integer newEnablestate ) {
	 	this.enablestate = newEnablestate;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性report_psn的Getter方法.属性名：填表人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_psn () {
		return report_psn;
	}   
	/**
	 * 属性report_psn的Setter方法.属性名：填表人
	 * 创建日期:
	 * @param newReport_psn java.lang.String
	 */
	public void setReport_psn (java.lang.String newReport_psn ) {
	 	this.report_psn = newReport_psn;
	} 	  
	/**
	 * 属性report_org的Getter方法.属性名：填表单位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getReport_org () {
		return report_org;
	}   
	/**
	 * 属性report_org的Setter方法.属性名：填表单位
	 * 创建日期:
	 * @param newReport_org java.lang.String
	 */
	public void setReport_org (java.lang.String newReport_org ) {
	 	this.report_org = newReport_org;
	} 	  
	/**
	 * 属性report_date的Getter方法.属性名：填报时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getReport_date () {
		return report_date;
	}   
	/**
	 * 属性report_date的Setter方法.属性名：填报时间
	 * 创建日期:
	 * @param newReport_date nc.vo.pub.lang.UFDate
	 */
	public void setReport_date (nc.vo.pub.lang.UFDate newReport_date ) {
	 	this.report_date = newReport_date;
	} 	  
	/**
	 * 属性remark的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newRemark java.lang.String
	 */
	public void setRemark (java.lang.String newRemark ) {
	 	this.remark = newRemark;
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：备用字段1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.属性名：备用字段1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：备用字段2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.属性名：备用字段2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：备用字段3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.属性名：备用字段3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：备用字段4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.属性名：备用字段4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：备用字段5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.属性名：备用字段5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：备用字段6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.属性名：备用字段6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：备用字段7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.属性名：备用字段7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：备用字段8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.属性名：备用字段8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：备用字段9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.属性名：备用字段9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：备用字段10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * 属性def10的Setter方法.属性名：备用字段10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * 属性id_visualuserinfo的Getter方法.属性名：id_visualuserinfo
	 * 创建日期:
	 * @return nc.vo.scapco.pub_visualorganization.visualUserInfo[]
	 */
	public nc.vo.scapco.pub_visualorganization.visualUserInfo[] getId_visualuserinfo () {
		return id_visualuserinfo;
	}   
	/**
	 * 属性id_visualuserinfo的Setter方法.属性名：id_visualuserinfo
	 * 创建日期:
	 * @param newId_visualuserinfo nc.vo.scapco.pub_visualorganization.visualUserInfo[]
	 */
	public void setId_visualuserinfo (nc.vo.scapco.pub_visualorganization.visualUserInfo[] newId_visualuserinfo ) {
	 	this.id_visualuserinfo = newId_visualuserinfo;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_visualorg";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "scapco_visualorganization";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "scapco_visualorganization";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public visualOrganization() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.scapco.pub_visualorganization.visualOrganization" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


